### DISCUSSION TITLE
Is it possible to use variables in config file in yaml format

### DISCUSSION THREAD

**Discussion by nakhorenko** [ClickHouse/ClickHouse#37911] [Q&A]
Hi!
I'm new to clickhouse, and my question may seem inappropriate or stupid =) anyway

I'm trying to change the clickhouse configuration xml format to yaml format, and the question is, is it possible to use variables like          {{ var }} in the configuration description?

For example: 
```
http_port: 8123
tcp_port: 9000
mysql_port: 9004
postgresql_port: 9005
interserver_http_port: 9009
interserver_http_host: somehost 
```
to 
```
http_port: 8123
tcp_port: 9000
mysql_port: 9004
postgresql_port: 9005
interserver_http_port: 9009
interserver_http_host: {{ clickhouse_host }}
```
one more 
```
remote_servers:
    
  test_cluster_tracker:
    shard:
    internal_replication: true
    replica:
      host:
        - {{ clickhouse_cluster_host }}
        - {{ clickhouse_cluster_host }}
      port: 9000
```

is it possible to define variables in the «defaults» directory for example or something like that?
