### DISCUSSION TITLE
docker-compose for laptop dev setup

### DISCUSSION THREAD

**Discussion by noorul** [ClickHouse/ClickHouse#45532] [General]
Is there a working docker-compose file that can be used on a laptop for local development?

**Comment by mdonkers** [comment]
No, we don't provide such a file / example. It depends too much on what kind of setup you'd like to accomplish, for how the docker-compose file should look like.

The Docker hub page shows how to get started with several examples: https://hub.docker.com/r/clickhouse/clickhouse-server/ . From there is shouldn't be too hard to translate to a Docker Compose file.

Do you have anything specific in mind for what the setup should look like? Or specific questions on how to configure things?

**Comment by leriel** [comment]
This should be able to get you started, along with some quality of life
```
version: '3'

services:
  ch:
    image: clickhouse/clickhouse-server:22.8.21.38-alpine
    ports:
      # enable whichever ports you need. prob just 9000 for starters
      # tcp
      - 127.0.0.1:9000:9000
      # http
      - 127.0.0.1:8123:8123
      # postgresql
      - 127.0.0.1:9005:9005
    volumes:
      # optional to persist data locally
      - ./data:/var/lib/clickhouse/
      # optional to add own config
      - ./extra-config.xml:/etc/clickhouse-server/config.d/extra-config.xml
      # optional to add users or enable settings for a default user
      - ./user.xml:/etc/clickhouse-server/users.d/user.xml
      # qol to mount own sql scripts to run them from inside container with
      # clickhouse client < /sql/myquery.sql
      - ./sql:/sql
    # adjust mem_limit and cpus to machine
    mem_limit: 12G
    cpus: 4
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

```
