### DISCUSSION TITLE
Keeper fails with Raft configuration error about hostname

### DISCUSSION THREAD

**Discussion by vladaman** [ClickHouse/ClickHouse#53656] [Q&A]
I am getting following error message - using docker

```
Application: DB::Exception: Raft configuration contains hostname 'localhost' with port '9181' which is equal to 'keeper_server.tcp_port' in server configuration
```
When I change section from localhost to keeper I same error:
```
Application: DB::Exception: Raft configuration contains hostname 'keeper' with port '9181' which is equal to 'keeper_server.tcp_port' in server configuration
```

My config:
```xml
<clickhouse>
    <logger>
        <level>error</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>50M</size>
        <count>10</count>
    </logger>

    <max_connections>4096</max_connections>
    <listen_host>0.0.0.0</listen_host> <!-- won't start without this in docker -->

    <keeper_server>
            <tcp_port>9181</tcp_port>
            <server_id>1</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/logs</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
                <!-- All settings listed in https://github.com/ClickHouse/ClickHouse/blob/master/src/Coordination/CoordinationSettings.h -->
            </coordination_settings>
            <!-- enable sanity hostname checks for cluster configuration (e.g. if localhost is used with remote endpoints) -->
            <hostname_checks_enabled>true</hostname_checks_enabled>
            <raft_configuration>
                 <server>
                    <id>1</id>
                    <!-- Internal port and hostname -->
                    <hostname>localhost</hostname>
		    <port>9181</port>
		    <can_become_leader>true</can_become_leader>
                </server>
            </raft_configuration>
    <zookeeper>
        <node>
            <host>localhost</host>
            <port>2181</port>
        </node>
    </zookeeper>
    </keeper_server>


    <openSSL>
      <server>
            <!-- Used for secure tcp port -->
            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
            <certificateFile>/etc/clickhouse-keeper/server.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-keeper/server.key</privateKeyFile>
            <!-- dhparams are optional. You can delete the <dhParamsFile> element.
                 To generate dhparams, use the following command:
                  openssl dhparam -out /etc/clickhouse-keeper/dhparam.pem 4096
                 Only file format with BEGIN DH PARAMETERS is supported.
              -->
            <dhParamsFile>/etc/clickhouse-keeper/dhparam.pem</dhParamsFile>
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>
    </openSSL>
</clickhouse>
```

docker-compose.yaml:
```yaml
version: '3'

services:
    clickhouse-keeper:
      image: clickhouse/clickhouse-keeper:23.2
      hostname: keeper
      container_name: clickhouse-keeper
      ports:
          - "2181:2181" # Zookeeper default service port.
          - "2182:2182"
          - "9181:9181" # Recommended ClickHouse Keeper port
          - "9234:9234"
      # command: "sleep 1000" # For testing only
      volumes:
          - ./config/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      networks:
        - clickhouse_net
...
```
