### DISCUSSION TITLE
Cannot set modification time to file with persistent volume in kubernetes

### DISCUSSION THREAD

**Discussion by jonaski** [ClickHouse/ClickHouse#73966] [General]
```
 (version 24.12.1.1614 (official build))
2024.12.30 09:09:01.722383 [ 706 ] {} <Error> void DB::SystemLog<DB::MetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::MetricLogElement]: Failed to flush system log system.metric_log with 9 entries up to offset 510: Code: 481. DB::ErrnoException: Cannot set modification time to file: /var/lib/clickhouse/store/702/702c03a1-c593-4d11-8472-ee1364ca4c2e/tmp_insert_202412_61_61_0/: , errno: 1, strerror: Operation not permitted. (PATH_ACCESS_DENIED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d74955b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000863c82c
2. DB::ErrnoException::ErrnoException<String const&>(int, int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000d7a023d
3. void DB::ErrnoException::throwFromPath<String const&>(int, String const&, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000d79fd28
4. DB::DiskLocal::setLastModified(String const&, Poco::Timestamp const&) @ 0x00000000115e055a
5. DB::DataPartStorageOnDiskBase::rename(String, String, std::shared_ptr<Poco::Logger>, bool, bool) @ 0x0000000012f128a1
6. DB::IMergeTreeDataPart::renameTo(String const&, bool) @ 0x0000000012f4d534
7. DB::MergeTreeData::renameTempPartAndReplaceImpl(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, DB::DataPartsLock&, std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>*, bool) @ 0x000000001304c3b8
8. DB::MergeTreeData::renameTempPartAndAdd(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, DB::DataPartsLock&, bool) @ 0x000000001304df68
9. DB::MergeTreeSink::finishDelayedChunk() @ 0x0000000013412772
10. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x00000000139cbdff
11. DB::ExceptionKeepingTransform::work() @ 0x00000000139cb84b
12. DB::ExecutionThreadContext::executeTask() @ 0x0000000013754be7
13. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000013747ec5
14. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000137477f6
15. DB::SystemLog<DB::MetricLogElement>::savingThreadFunction() @ 0x00000000122961ac
16. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::MetricLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::MetricLogElement>::startup()::'lambda'()&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000d8894e8
17. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000d825ec2
18. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000d82d27a
19. ? @ 0x00007f53b664cac3
20. ? @ 0x00007f53b66de850
 (version 24.12.1.1614 (official build))
```

I suspect this is because of /var/lib/clickhouse is mounted with CIFS:

```
clickhouse-server-6f6ffb9f99-zn4mx:/# df -hT
Filesystem           Type            Size      Used Available Use% Mounted on
overlay              overlay       123.9G     92.8G     31.0G  75% /
tmpfs                tmpfs          64.0M         0     64.0M   0% /dev
/dev/root            ext4          123.9G     92.8G     31.0G  75% /etc/hosts
/dev/root            ext4          123.9G     92.8G     31.0G  75% /dev/termination-log
/dev/root            ext4          123.9G     92.8G     31.0G  75% /etc/hostname
/dev/root            ext4          123.9G     92.8G     31.0G  75% /etc/resolv.conf
shm                  tmpfs          64.0M         0     64.0M   0% /dev/shm
//f919c40a10a6b4b16bacd69.file.core.windows.net/pvc-3976c114-31aa-483a-9e7e-b0d43d207fc4
                     cifs            5.0G     16.8M      5.0G   0% /var/lib/clickhouse
tmpfs                tmpfs          12.3G     12.0K     12.3G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                tmpfs           7.8G         0      7.8G   0% /proc/acpi
tmpfs                tmpfs          64.0M         0     64.0M   0% /proc/kcore
tmpfs                tmpfs          64.0M         0     64.0M   0% /proc/keys
tmpfs                tmpfs          64.0M         0     64.0M   0% /proc/timer_list
tmpfs                tmpfs           7.8G         0      7.8G   0% /proc/scsi
tmpfs                tmpfs           7.8G         0      7.8G   0% /sys/firmware
```

```
clickhouse-server-6f6ffb9f99-zn4mx:/# ls -la /var/lib/clickhouse/store/702/702c03a1-c593-4d11-8472-ee1364ca4c2e/
total 1
drwxrwxrwx    2 root     root             0 Dec 30 09:00 .
drwxrwxrwx    2 root     root             0 Dec 30 09:00 ..
drwxrwxrwx    2 root     root             0 Dec 30 09:00 detached
-rwxrwxrwx    1 root     root             1 Dec 30 09:00 format_version.txt
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_100_100_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_101_101_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_102_102_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_103_103_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_104_104_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_105_105_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_106_106_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_107_107_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_108_108_0
drwxrwxrwx    2 root     root             0 Dec 30 09:15 tmp_insert_202412_109_109_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_10_10_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_11_11_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_12_12_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_13_13_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_14_14_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_15_15_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_16_16_0
drwxrwxrwx    2 root     root             0 Dec 30 09:02 tmp_insert_202412_17_17_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_18_18_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_19_19_0
drwxrwxrwx    2 root     root             0 Dec 30 09:00 tmp_insert_202412_1_1_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_20_20_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_21_21_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_22_22_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_23_23_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_24_24_0
drwxrwxrwx    2 root     root             0 Dec 30 09:03 tmp_insert_202412_25_25_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_26_26_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_27_27_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_28_28_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_29_29_0
drwxrwxrwx    2 root     root             0 Dec 30 09:00 tmp_insert_202412_2_2_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_30_30_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_31_31_0
drwxrwxrwx    2 root     root             0 Dec 30 09:04 tmp_insert_202412_32_32_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_33_33_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_34_34_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_35_35_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_36_36_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_37_37_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_38_38_0
drwxrwxrwx    2 root     root             0 Dec 30 09:05 tmp_insert_202412_39_39_0
drwxrwxrwx    2 root     root             0 Dec 30 09:00 tmp_insert_202412_3_3_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_40_40_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_41_41_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_42_42_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_43_43_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_44_44_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_45_45_0
drwxrwxrwx    2 root     root             0 Dec 30 09:06 tmp_insert_202412_46_46_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_47_47_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_48_48_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_49_49_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_4_4_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_50_50_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_51_51_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_52_52_0
drwxrwxrwx    2 root     root             0 Dec 30 09:07 tmp_insert_202412_53_53_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_54_54_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_55_55_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_56_56_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_57_57_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_58_58_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_59_59_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_5_5_0
drwxrwxrwx    2 root     root             0 Dec 30 09:08 tmp_insert_202412_60_60_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_61_61_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_62_62_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_63_63_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_64_64_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_65_65_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_66_66_0
drwxrwxrwx    2 root     root             0 Dec 30 09:09 tmp_insert_202412_67_67_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_68_68_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_69_69_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_6_6_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_70_70_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_71_71_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_72_72_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_73_73_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_74_74_0
drwxrwxrwx    2 root     root             0 Dec 30 09:10 tmp_insert_202412_75_75_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_76_76_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_77_77_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_78_78_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_79_79_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_7_7_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_80_80_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_81_81_0
drwxrwxrwx    2 root     root             0 Dec 30 09:11 tmp_insert_202412_82_82_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_83_83_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_84_84_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_85_85_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_86_86_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_87_87_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_88_88_0
drwxrwxrwx    2 root     root             0 Dec 30 09:12 tmp_insert_202412_89_89_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_8_8_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_90_90_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_91_91_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_92_92_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_93_93_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_94_94_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_95_95_0
drwxrwxrwx    2 root     root             0 Dec 30 09:13 tmp_insert_202412_96_96_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_97_97_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_98_98_0
drwxrwxrwx    2 root     root             0 Dec 30 09:14 tmp_insert_202412_99_99_0
drwxrwxrwx    2 root     root             0 Dec 30 09:01 tmp_insert_202412_9_9_0
```

The persistent volume is set up like this:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      securityContext:
        fsGroup: 101
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
      initContainers:
        - name: volume-permissions
          image: {{ .Values.image }}
          imagePullPolicy: Always
          volumeMounts:
          - name: clickhouse-data
            mountPath: "/var/lib/clickhouse"
          command:
            - /bin/sh
            - -ec
            - |
              mkdir -p /var/lib/clickhouse/data
              chmod 777 /var/lib/clickhouse/data
              chown 101:101 /var/lib/clickhouse
              find /var/lib/clickhouse -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs -r chown -R 101:101
      containers:
        - name: {{ .Values.appname }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          volumeMounts:
          - name: clickhouse-data
            mountPath: "/var/lib/clickhouse"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8123
            - name: native
              protocol: TCP
              containerPort: 9000
      imagePullSecrets:
        - name: pullsecret-{{ .Values.appname }}
```
