### ISSUE TITLE
default database/user using docker

### ISSUE THREAD

**Issue by tarampampam** [ClickHouse/ClickHouse#10339]
[Postgres image](https://hub.docker.com/_/postgres) allows to create "default" database and user on container startup - this is very useful for development (it uses `POSTGRES_DB`, `POSTGRES_USER` and `POSTGRES_PASSWORD` environment variables).

Does clickhouse docker image can contains this feature?

For example, now I use this (`docker-compose` for local development):

```yaml
version: '3.2'

volumes:
  clickhouse-data:

services:
  clickhouse:
    image: yandex/clickhouse-server:20.3
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: my_db_name
      CLICKHOUSE_USER: clickhouse-user
      CLICKHOUSE_PASSWORD: secret
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse:cached
      - ./docker/clickhouse/init-defaults.sh:/docker-entrypoint-initdb.d/init-defaults.sh:ro
    ports:
      - 9000/tcp
```

And `init-defaults.sh` in `./docker/clickhouse`:

```bash
#!/usr/bin/env sh

CLICKHOUSE_DB="${CLICKHOUSE_DB:-database}";
CLICKHOUSE_USER="${CLICKHOUSE_USER:-user}";
CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD:-password}";

cat <<EOT >> /etc/clickhouse-server/users.d/user.xml
<yandex>
  <!-- Docs: <https://clickhouse.tech/docs/en/operations/settings/settings_users/> -->
  <users>
    <${CLICKHOUSE_USER}>
      <profile>default</profile>
      <networks>
        <ip>::/0</ip>
      </networks>
      <password>${CLICKHOUSE_PASSWORD}</password>
      <quota>default</quota>
    </${CLICKHOUSE_USER}>
  </users>
</yandex>
EOT
#cat /etc/clickhouse-server/users.d/user.xml;

clickhouse-client --query "CREATE DATABASE IF NOT EXISTS ${CLICKHOUSE_DB}";
```

And this works! But, it looks like "basic" feature for docker image with database. What do you think about this?
