### ISSUE TITLE
"All connection tries failed while connecting to ZooKeeper" while trying to create replicated table

### ISSUE THREAD

**Issue by zergon321** [ClickHouse/ClickHouse#13074]
I tried to create a decentralized **ClickHouse** cluster so that each node has replicated and distributed version of the same table, like this:

```python
from clickhouse_driver import Client

addresses = [
    ("127.0.0.1", "9001"),
    ("127.0.0.1", "9002"),
    ("127.0.0.1", "9003"),
    ("127.0.0.1", "9004"),
    ("127.0.0.1", "9005"),
    ("127.0.0.1", "9006")
]

if __name__ == "__main__":
    # First create all slave tables.
    for address in addresses:
        client = Client(address[0], port=address[1])

        client.execute("CREATE DATABASE IF NOT EXISTS history")

        client.execute(r'''CREATE TABLE IF NOT EXISTS history.measures_sharded(
                      timestamp DateTime,
                      parameter String,
                      value Float64)
                      ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/history.measures_sharded', '{replica}')
                      PARTITION BY parameter
                      ORDER BY timestamp''')

    # Then create all master tables.
    for address in addresses:
        client = Client(address[0], port=address[1])

        client.execute('''CREATE TABLE IF NOT EXISTS history.measures(
                          timestamp DateTime,
                          parameter String,
                          value Float64)
                          ENGINE = Distributed(example_cluster, history, measures_sharded, rand())''')
```

It works fine if I use only one **Zookeeper** node. But when I try to use many, this happens:

```
Traceback (most recent call last):
  File "create-cluster.py", line 25, in <module>
    ORDER BY timestamp''')
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 224, in execute
    columnar=columnar
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 347, in process_ordinary_query
    columnar=columnar)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 89, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 101, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 118, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 999.
Coordination::Exception. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. Addresses: 192.168.80.2:2181, 192.168.80.3:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.2:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.3:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.2:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.3:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.2:2181
Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused (version 19.14.13.4 (official build), 192.168.80.3:2181
 (Connection loss). Stack trace:

0. 0x55f6a470e474 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x55f6a824b894 Coordination::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) /usr/bin/clickhouse
2. 0x55f6a824bf27 Coordination::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
3. 0x55f6a460515b ? /usr/bin/clickhouse
4. 0x55f6a826b4d3 Coordination::ZooKeeper::ZooKeeper(std::vector<Poco::Net::SocketAddress, std::allocator<Poco::Net::SocketAddress> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Timespan, Poco::Timespan, Poco::Timespan) /usr/bin/clickhouse
5. 0x55f6a825cfb7 zkutil::ZooKeeper::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/clickhouse
6. 0x55f6a825d818 zkutil::ZooKeeper::ZooKeeper(Poco::Util::AbstractConfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/bin/clickhouse
7. 0x55f6a7938913 DB::Context::getZooKeeper() const /usr/bin/clickhouse
8. 0x55f6a7c3238c DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::ColumnsDescription const&, DB::IndicesDescription const&, DB::ConstraintsDescription const&, DB::Context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::IAST> const&, DB::MergeTreeData::MergingParams const&, std::unique_ptr<DB::MergeTreeSettings, std::default_delete<DB::MergeTreeSettings> >, bool) /usr/bin/clickhouse
9. 0x55f6a7d96379 ? /usr/bin/clickhouse
10. 0x55f6a7d97f39 std::_Function_handler<std::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&), std::shared_ptr<DB::IStorage> (*)(DB::StorageFactory::Arguments const&)>::_M_invoke(std::_Any_data const&, DB::StorageFactory::Arguments const&) /usr/bin/clickhouse
11. 0x55f6a7bb90f1 DB::StorageFactory::get(DB::ASTCreateQuery&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool, bool) const /usr/bin/clickhouse
12. 0x55f6a797b2a0 DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) /usr/bin/clickhouse
13. 0x55f6a797c327 DB::InterpreterCreateQuery::execute() /usr/bin/clickhouse
14. 0x55f6a7adb96c ? /usr/bin/clickhouse
15. 0x55f6a7adcbc0 DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) /usr/bin/clickhouse
16. 0x55f6a4786e00 DB::TCPHandler::runImpl() /usr/bin/clickhouse
17. 0x55f6a478783f DB::TCPHandler::run() /usr/bin/clickhouse
18. 0x55f6a8611fe4 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
19. 0x55f6a8612741 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
20. 0x55f6a8be4d49 Poco::PooledThread::run() /usr/bin/clickhouse
21. 0x55f6a8be2950 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
22. 0x55f6a9379094 ? /usr/bin/clickhouse
23. 0x7f8f5686d6db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
24. 0x7f8f5618a88f __clone /lib/x86_64-linux-gnu/libc-2.27.so
```

I would like to know why it happens.

My config for each one of six **ClickHouse** nodes:
```xml
<remote_servers>
        <example_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-node-1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-node-2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-node-3</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-node-4</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>ch-node-5</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>ch-node-6</host>
                    <port>9000</port>
                </replica>
            </shard>
        </example_cluster>
    </remote_servers>

    <zookeeper>
        <node index="1">
            <host>ch-zookeeper-1</host>
            <port>2181</port>
        </node>
        <node index="2">
            <host>ch-zookeeper-2</host>
            <port>2181</port>
        </node>
    </zookeeper>
```

And here's my `docker-compose.yml` which I use to deploy all that system locally:

```yaml
version: "3.7"

services:

  ch-zookeeper-1:
    container_name: ch_zookeeper_1
    image: zookeeper:3.6.1
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=ch-zookeeper-1:2888:3888,ch-zookeeper-2:2888:3888

  ch-zookeeper-2:
    container_name: ch_zookeeper_2
    image: zookeeper:3.6.1
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=ch-zookeeper-1:2888:3888,ch-zookeeper-2:2888:3888

  ch-node-1:
    container_name: ch_node_1
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9001:9000
      - 8124:8123
    volumes:
      - type: volume
        source: ch-node-1-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-1-logs
        target: /var/log/clickhouse-server
      - ./node-1-config.xml:/etc/clickhouse-server/config.xml

  ch-node-2:
    container_name: ch_node_2
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9002:9000
      - 8125:8123
    volumes:
      - type: volume
        source: ch-node-2-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-2-logs
        target: /var/log/clickhouse-server
      - ./node-2-config.xml:/etc/clickhouse-server/config.xml

  ch-node-3:
    container_name: ch_node_3
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9003:9000
      - 8126:8123
    volumes:
      - type: volume
        source: ch-node-3-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-3-logs
        target: /var/log/clickhouse-server
      - ./node-3-config.xml:/etc/clickhouse-server/config.xml

  ch-node-4:
    container_name: ch_node_4
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9004:9000
      - 8127:8123
    volumes:
      - type: volume
        source: ch-node-4-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-4-logs
        target: /var/log/clickhouse-server
      - ./node-4-config.xml:/etc/clickhouse-server/config.xml

  ch-node-5:
    container_name: ch_node_5
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9005:9000
      - 8128:8123
    volumes:
      - type: volume
        source: ch-node-5-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-5-logs
        target: /var/log/clickhouse-server
      - ./node-5-config.xml:/etc/clickhouse-server/config.xml

  ch-node-6:
    container_name: ch_node_6
    image: yandex/clickhouse-server:19.14.13.4
    depends_on:
      - ch-zookeeper-1
      - ch-zookeeper-2
    ports:
      - 9006:9000
      - 8129:8123
    volumes:
      - type: volume
        source: ch-node-6-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-node-6-logs
        target: /var/log/clickhouse-server
      - ./node-6-config.xml:/etc/clickhouse-server/config.xml

volumes:
  ch-node-1-data:
  ch-node-1-logs:
  ch-node-2-data:
  ch-node-2-logs:
  ch-node-3-data:
  ch-node-3-logs:
  ch-node-4-data:
  ch-node-4-logs:
  ch-node-5-data:
  ch-node-5-logs:
  ch-node-6-data:
  ch-node-6-logs:
```

When I remove environment variables for **Zookeeper** nodes, the exception doesn't happen, but replication doesn't work properly. So how to solve this problem?
