### ISSUE TITLE
Instruction check fail. The CPU does not support SSSE3 instruction set.

### ISSUE THREAD

**Issue by cryptoman3** [ClickHouse/ClickHouse#20237]
Clickhouse not work with docker on macOS Big Sur 11.1 (apple m1 cpu)

**docker-compose.yml:**
```
clickhouse:
    extends:
      file: .docker/clickhouse/clickhouse-compose.yml
      service: clickhouse
    restart: on-failure
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_CLIENT_PORT}:9000"
```

**clickhouse-compose.yml:**
```
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./data:/var/lib/clickhouse:rw
```
**docker log:**
```
clickhouse_1  | goroutine 1 [running]:
clickhouse_1  | runtime.systemstack_switch()
clickhouse_1  |         /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420020768 sp=0xc420020760
clickhouse_1  | runtime.main()
clickhouse_1  |         /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200207c0 sp=0xc420020768
clickhouse_1  | runtime.goexit()
clickhouse_1  |         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200207c8 sp=0xc4200207c0
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | /usr/bin/dirname: missing operand
clickhouse_1  | Try '/usr/bin/dirname --help' for more information.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | /usr/bin/dirname: missing operand
clickhouse_1  | Try '/usr/bin/dirname --help' for more information.
clickhouse_1  | Instruction check fail. The CPU does not support SSSE3 instruction set.
clickhouse_1  | runtime: failed to create new OS thread (have 2 already; errno=22)
clickhouse_1  | fatal error: newosproc
```
