### ISSUE TITLE
apt repo addition fails on ubuntu 18.04 with ansible

### ISSUE THREAD

**Issue by pdeva** [ClickHouse/ClickHouse#2763]
Ubuntu 18.04 is more strict with regards to adding apt key.

Ansible fails with msg:

```
"W:GPG error: http://repo.yandex.ru/clickhouse/deb/stable main/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C8F1E19FE0C56BD4, E:The repository 'http://repo.yandex.ru/clickhouse/deb/stable main/ Release' is not signed."
```

To reproduce, run ansible with task:
```
- name: add repo
  apt_repository:
    repo: deb http://repo.yandex.ru/clickhouse/deb/stable/ main/
    state: present

```
