### ISSUE TITLE
While inserting into clickhouse i am facing filesystem error  

### ISSUE THREAD

**Issue by Nishantarya80** [ClickHouse/ClickHouse#35036]
`DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: Permission denied [/var/lib/clickhouse/data/default/insert_select_testtable/tmp_insert_all_1_1_0/] [/var/lib/clickhouse/data/default/insert_select_testtable/all_1_1_0/].`

Clickhouse version 22.2.2
WSL2
Ubuntu 20.4

i am able to start the server with  `sudo -u clickhouse service clickhouse-server start`

**Comment by Jure-BB** [comment]
I'm having a similar issue. ClickHouse v22.3, Windows WSL2.

Going back to v21.3.20.1 solves the issue for me.

```
Cannot print extra info for Poco::Exception (version 22.3.2.1)
2022.03.30 16:04:47.153994 [ 101 ] {} <Error> void DB::SystemLog<DB::TraceLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::TraceLogElement]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Permission denied [/var/lib/clickhouse/store/2cc/2cc767b6-9195-49ab-a8ff-f218c5477f35/tmp_insert_202203_1_1_0/] [/var/lib/clickhouse/store/2cc/2cc767b6-9195-49ab-a8ff-f218c5477f35/202203_1_1_0/], Stack trace (when copying this message, always include the lines below):

0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x18dd2bed in ?
1. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x18ddcb97 in ?
2. ? @ 0x18d813c2 in /usr/bin/clickhouse
3. ? @ 0x18d80f9d in /usr/bin/clickhouse
4. ? @ 0x18d84298 in /usr/bin/clickhouse
5. std::__1::__fs::filesystem::__rename(std::__1::__fs::filesystem::path const&, std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x18d8a775 in /usr/bin/clickhouse
6. DB::DiskLocal::moveDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13f6970f in /usr/bin/clickhouse
7. DB::IMergeTreeDataPart::renameTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) const @ 0x14e1c60e in /usr/bin/clickhouse
8. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*, DB::MergeTreeDeduplicationLog*, std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x14e9b955 in /usr/bin/clickhouse
9. DB::MergeTreeData::renameTempPartAndAdd(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, DB::MergeTreeDeduplicationLog*, std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x14e9a4ca in /usr/bin/clickhouse
10. DB::MergeTreeSink::finishDelayedChunk() @ 0x14fdcd18 in /usr/bin/clickhouse
11. ? @ 0x156657e9 in /usr/bin/clickhouse
12. DB::ExceptionKeepingTransform::work() @ 0x156651a7 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x154ad143 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x154a0b9e in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x154a03c0 in /usr/bin/clickhouse
16. DB::SystemLog<DB::TraceLogElement>::flushImpl(std::__1::vector<DB::TraceLogElement, std::__1::allocator<DB::TraceLogElement> > const&, unsigned long) @ 0x147a910c in /usr/bin/clickhouse
17. DB::SystemLog<DB::TraceLogElement>::savingThreadFunction() @ 0x147a73f0 in /usr/bin/clickhouse
18. ? @ 0xa5a3471 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
20. ? @ 0xa58881d in /usr/bin/clickhouse
21. ? @ 0x7f8ded853609 in ?
22. __clone @ 0x7f8ded778163 in ?
```

In `docker-compose.yml` ClickHouse service is defined like this:
```
clickhouse:
  container_name: fp.clickhouse
  image: clickhouse/clickhouse-server:22.3
  restart: always
  ports:
    - "8123:8123"
    - "9000:9000"
  volumes:
    - ./clickhouse/data:/var/lib/clickhouse
    - ./clickhouse/log:/var/log/clickhouse-server
    - ./clickhouse/config.d:/etc/clickhouse-server/config.d
    - ./clickhouse/users.d:/etc/clickhouse-server/users.d
  ulimits:
    nofile:
      soft: 262144
      hard: 262144
```

**Comment by DongJigong** [comment]
I also got this error log detail below 
`Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: Permission denied [/var/lib/clickhouse/store/8fa/8fa725ac-3e0a-4de7-8142-afcf8b90bae6/tmp_insert_19700101_3_3_0/] [/var/lib/clickhouse/store/8fa/8fa725ac-3e0a-4de7-8142-afcf8b90bae6/19700101_3_3_0/]. (STD_EXCEPTION)`

**Comment by zyd915** [comment]
help me, I got this error to :
DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: Permission denied [/var/lib/clickhouse/store/8fa/8fa725ac-3e0a-4de7-8142-afcf8b90bae6/tmp_insert_xxxx/] [/var/lib/clickhouse/store/8fa/8fa725ac-3e0a-4de7-8142-afcf8b90bae6/xxx]. (STD_EXCEPTION)

**Comment by zyd915** [comment]
Going back to v21.3.20.1 solves the issue , thanks [Jure-BB] note!

**Comment by jeanatpi** [comment]
Hello!

Same issue here with version 22.6.3.35-alpine + running docker on windows with docker-desktop + WSL2 enabled.

`
hostname: 'pi_clickhouse'
container_name: "pi_clickhouse"
image: clickhouse/clickhouse-server:22.6.3.35-alpine
environment:
	CLICKHOUSE_USER: ${CLICKHOUSE_USER}
	CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
	CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
ports:
	- ${CLICKHOUSE_HTTP_PORT}:8123
	- ${CLICKHOUSE_TCP_PORT}:9000
ulimits:
	nofile:
		soft: 262144
		hard: 262144
volumes:
	- "./shared_volumes/pi_clickhouse:/var/lib/clickhouse"
	- "./scripts:/scripts"
	- "./data:/data"

`

**Comment by zg-tips** [comment]
> Going back to v21.3.20.1 solves the issue , thanks [Jure-BB] note!

Thank you！

**Comment by zg-tips** [comment]
> I'm having a similar issue. ClickHouse v22.3, Windows WSL2.
> 
> Going back to v21.3.20.1 solves the issue for me.
> 
> ```
> Cannot print extra info for Poco::Exception (version 22.3.2.1)
> 2022.03.30 16:04:47.153994 [ 101 ] {} <Error> void DB::SystemLog<DB::TraceLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::TraceLogElement]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Permission denied [/var/lib/clickhouse/store/2cc/2cc767b6-9195-49ab-a8ff-f218c5477f35/tmp_insert_202203_1_1_0/] [/var/lib/clickhouse/store/2cc/2cc767b6-9195-49ab-a8ff-f218c5477f35/202203_1_1_0/], Stack trace (when copying this message, always include the lines below):
> 
> 0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x18dd2bed in ?
> 1. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x18ddcb97 in ?
> 2. ? @ 0x18d813c2 in /usr/bin/clickhouse
> 3. ? @ 0x18d80f9d in /usr/bin/clickhouse
> 4. ? @ 0x18d84298 in /usr/bin/clickhouse
> 5. std::__1::__fs::filesystem::__rename(std::__1::__fs::filesystem::path const&, std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x18d8a775 in /usr/bin/clickhouse
> 6. DB::DiskLocal::moveDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13f6970f in /usr/bin/clickhouse
> 7. DB::IMergeTreeDataPart::renameTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) const @ 0x14e1c60e in /usr/bin/clickhouse
> 8. DB::MergeTreeData::renameTempPartAndReplace(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, std::__1::unique_lock<std::__1::mutex>&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >*, DB::MergeTreeDeduplicationLog*, std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x14e9b955 in /usr/bin/clickhouse
> 9. DB::MergeTreeData::renameTempPartAndAdd(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, SimpleIncrement*, DB::MergeTreeData::Transaction*, DB::MergeTreeDeduplicationLog*, std::__1::basic_string_view<char, std::__1::char_traits<char> >) @ 0x14e9a4ca in /usr/bin/clickhouse
> 10. DB::MergeTreeSink::finishDelayedChunk() @ 0x14fdcd18 in /usr/bin/clickhouse
> 11. ? @ 0x156657e9 in /usr/bin/clickhouse
> 12. DB::ExceptionKeepingTransform::work() @ 0x156651a7 in /usr/bin/clickhouse
> 13. DB::ExecutionThreadContext::executeTask() @ 0x154ad143 in /usr/bin/clickhouse
> 14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x154a0b9e in /usr/bin/clickhouse
> 15. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x154a03c0 in /usr/bin/clickhouse
> 16. DB::SystemLog<DB::TraceLogElement>::flushImpl(std::__1::vector<DB::TraceLogElement, std::__1::allocator<DB::TraceLogElement> > const&, unsigned long) @ 0x147a910c in /usr/bin/clickhouse
> 17. DB::SystemLog<DB::TraceLogElement>::savingThreadFunction() @ 0x147a73f0 in /usr/bin/clickhouse
> 18. ? @ 0xa5a3471 in /usr/bin/clickhouse
> 19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
> 20. ? @ 0xa58881d in /usr/bin/clickhouse
> 21. ? @ 0x7f8ded853609 in ?
> 22. __clone @ 0x7f8ded778163 in ?
> ```
> 
> In `docker-compose.yml` ClickHouse service is defined like this:
> 
> ```
> clickhouse:
>   container_name: fp.clickhouse
>   image: clickhouse/clickhouse-server:22.3
>   restart: always
>   ports:
>     - "8123:8123"
>     - "9000:9000"
>   volumes:
>     - ./clickhouse/data:/var/lib/clickhouse
>     - ./clickhouse/log:/var/log/clickhouse-server
>     - ./clickhouse/config.d:/etc/clickhouse-server/config.d
>     - ./clickhouse/users.d:/etc/clickhouse-server/users.d
>   ulimits:
>     nofile:
>       soft: 262144
>       hard: 262144
> ```

Thank you!!!

**Comment by vpease** [comment]
i was able to overpass this limitation of wsl2 using Docker Volumes instead of bind mounts. 
Attached my docker compose file.
version: '3.9'
services:
 clickhouse:
  container_name: superclick
  image: clickhouse/clickhouse-server:23.1.2.9-alpine
  cap_add:
    - "SYS_NICE"
    - "NET_ADMIN"
    - "IPC_LOCK"
  ulimits:
    nofile:
      soft: 262144
      hard: 262144
  volumes:
    - clickhouse:/var/lib/clickhouse
    - clickhouse-logs:/var/log/clickhouse-server
  environment:
   CLICKHOUSE_USER: 'default'
   CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
   CLICKHOUSE_PASSWORD: 'default'
  ports:
    - "8123:8123"
    - "9000:9000"
    - "9004:9004"
    - "9005:9005"
    - "9009:9009"
volumes:
  clickhouse:
   external: true
  clickhouse-logs:
   external: true


previously, volumes created with : 
docker volume create clickhouse
docker volume create clickhouse-logs

**Comment by vpease** [comment]
i was able to overpass this limitation of wsl2 using Docker Volumes instead of bind mounts. 
Attached my docker compose file.
version: '3.9'
services:
 clickhouse:
  container_name: superclick
  image: clickhouse/clickhouse-server:23.1.2.9-alpine
  cap_add:
    - "SYS_NICE"
    - "NET_ADMIN"
    - "IPC_LOCK"
  ulimits:
    nofile:
      soft: 262144
      hard: 262144
  volumes:
    - clickhouse:/var/lib/clickhouse
    - clickhouse-logs:/var/log/clickhouse-server
  environment:
   CLICKHOUSE_USER: 'default'
   CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
   CLICKHOUSE_PASSWORD: 'default'
  ports:
    - "8123:8123"
    - "9000:9000"
    - "9004:9004"
    - "9005:9005"
    - "9009:9009"
volumes:
  clickhouse:
   external: true
  clickhouse-logs:
   external: true


previously, volumes created with : 
docker volume create clickhouse
docker volume create clickhouse-logs

**Comment by alexey-milovidov** [comment]
The behavior is correct: it correctly reports "Permission denied" when the filesystem is misconfigured, e.g., the directories are in different mount points, or the filesystem does not support Unix permissions, or the filesystem reports an error for any other reason.

The workaround should be documented.

**Comment by ChafLee** [comment]
How to solve this problem? It's too irresponsible to use a reduced version to solve it

**Comment by StashOfCode** [comment]
What's the workaround?

**Comment by marklit** [comment]
It would be good if there was either detection of WSL or some sort of flag that could be passed to the server to ignore the file ownership values.

It was a big step forward for ergonomics when single-command installation was introduced two years ago. Needing to use Docker to use CH with persistent storage is a technical roadblock and will put new users off. I'm not aware of any other database software that fails to persist without the use of Docker on WSL.

ClickHouse local works out of the box with WSL and gives users an easy way to just get started but there is no persistence of data. It takes over an hour to import my taxi rides dataset into CH and get a MergeTree table setup. It would be nice to only do that once and not have to rely on dumping the dataset out to MT-formatted files to maintain persistence.

At some point, the database experts of the early 2010s move on in life. It's important to think about new users to the software and understand that every extra requirement is one competing databases might not have.

**Comment by Anutrix** [comment]
Faced the exact same issue on Ubuntu. Not WSL, just a normal device.

**Comment by den-crane** [comment]
the real reason
* https://github.com/ClickHouse/ClickHouse/issues/56288

**Comment by fresh-fx59** [comment]
> i was able to overpass this limitation of wsl2 using Docker Volumes instead of bind mounts. Attached my docker compose file. version: '3.9' services: clickhouse: container_name: superclick image: clickhouse/clickhouse-server:23.1.2.9-alpine cap_add: - "SYS_NICE" - "NET_ADMIN" - "IPC_LOCK" ulimits: nofile: soft: 262144 hard: 262144 volumes: - clickhouse:/var/lib/clickhouse - clickhouse-logs:/var/log/clickhouse-server environment: CLICKHOUSE_USER: 'default' CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 CLICKHOUSE_PASSWORD: 'default' ports: - "8123:8123" - "9000:9000" - "9004:9004" - "9005:9005" - "9009:9009" volumes: clickhouse: external: true clickhouse-logs: external: true
> 
> previously, volumes created with : docker volume create clickhouse docker volume create clickhouse-logs

used volumes only for data like this 

```
version: '3.8'
volumes:
  clickhouse:
    driver: local
services:
  clickhouse-flyway:
    image: 'clickhouse/clickhouse-server:${CHVER:-latest}'
    user: '101:101'
    container_name: clickhouse-flyway
    hostname: clickhouse-flyway
    volumes:
      - ./fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ##- ./fs/volumes/clickhouse/data:/var/lib/clickhouse
      - clickhouse:/var/lib/clickhouse
      - ./fs/volumes/clickhouse/logs:/var/log/clickhouse-server
      - ./fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8125:8123'
      - '127.0.0.1:9004:9000'
    depends_on:
      - clickhouse-flyway-keeper
  clickhouse-flyway-keeper:
    image: 'clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}'
    user: '101:101'
    container_name: clickhouse-flyway-keeper
    hostname: clickhouse-flyway-keeper
    volumes:
      - ./fs/volumes/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - '127.0.0.1:9185:9181'
```
