### ISSUE TITLE
Remove default user while using yaml configuration

### ISSUE THREAD

**Issue by DrissiReda** [ClickHouse/ClickHouse#35587]
Hello I'm trying to switch to yaml configuration. I managed to make `config.yaml` work, but now I need a `users.yaml` file.

Using the configuration from `config.yaml` sample to include the proper `users.yaml` didn't work.

Namely:

```yaml
user_directories:
    users_xml:
        # Path to configuration file with predefined users.
        path: users.yaml
    local_directory:
        # Path to folder where users created by SQL commands are stored.
        path: /var/lib/clickhouse/access/
```

I had to use:

```yaml
users_config: /etc/clickhouse-server/users.d/users.yaml
```

This works but not for multiple users file.

That's just a minor inconvenience. The real issue now is removing the default user.

Before with xml I just did this:

```xml
<clickhouse>
    <users>
        <default remove="remove"></default>
    </users>
</clickhouse>
```
So following the documentation I translated it to:

```yaml
users:
  default:
     "@remove": remove
```

This gives the error that it's expecting a password of some kind for user default, I thought it was a minor bug and it'll still delete the default user so using this :

```yaml
users:
  default:
     "@remove": remove
     password: dummy
```

Doesn't give an error, but I can login with `default:dummy` .

Any way to completely remove the default user in yaml?

Bonus: I'd like to point to a directory where clickhouse will look for user configuration.

Clickhouse version: 22.3.2.2 
Environment: Kubernetes

**Comment by den-crane** [comment]
works for me

```
cat /etc/clickhouse-server/users.d/xxxxx.yaml
users:
  default:
    "@remove": remove


clickhouse-client
ClickHouse client version 22.3.2.1.
Connecting to localhost:9000 as user default.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)
```

```
cat /var/lib/clickhouse/preprocessed_configs/users.xml
...
<!-- This file was generated automatically.
     Do not edit it: it is likely to be discarded and generated again before it's read next time.
     Files used to generate this file:
       /etc/clickhouse-server/users.xml
       /etc/clickhouse-server/users.d/access_management_default.xml
       /etc/clickhouse-server/users.d/xxxxx.yaml      -->
....
    <!-- Users and ACL. -->
    <users>
        <!-- If user name was not specified, 'default' user is used. -->



    </users>
....
```

**Comment by den-crane** [comment]
So for example, you just installed Clickhouse server the first time and during installation you pressed ENTER for a password prompt. 
Now you have 2 vendor files in `ls -l /etc/clickhouse-server/` config.xml & users.xml and empty folders `config.d`, `users.d`.

To disable default user using yaml you need to create a file in `users.d`

```yaml
# cat /etc/clickhouse-server/users.d/xxxxx.yaml
users:
  default:
    "@remove": remove
```

filename `xxxxx` is arbitrary.

----
This message 
```
ClickHouse client version 22.3.2.1.
Connecting to localhost:9000 as user default.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)
```
is irrelevant. It just means that user default cannot be identified.
