### ISSUE TITLE
Unable to load function files using configmap on k8s

### ISSUE THREAD

**Issue by ygrzjh** [ClickHouse/ClickHouse#38042]
ClickHouse Version: `22.5.1.2079`

`config.xml`
```xml
<user_defined_path>/etc/clickhouse-server/user_defined/</user_defined_path>
```
`function_test.sql`,use ConfigMap mount.
```shell
root@clickhouse-0-0:/etc/clickhouse-server/user_defined# cat function_test.sql 
CREATE FUNCTION test AS a -> (a * 2)

root@clickhouse-0-0:/etc/clickhouse-server/user_defined# ls -al
total 12
drwxrwxrwx 3 root       root       4096 Jun 14 07:44 .
drwxrwxrwx 1 clickhouse clickhouse 4096 Jun 14 07:44 ..
drwxr-xr-x 2 root       root       4096 Jun 14 07:44 ..2022_06_14_07_44_53.3010880811
lrwxrwxrwx 1 root       root         32 Jun 14 07:44 ..data -> ..2022_06_14_07_44_53.3010880811
lrwxrwxrwx 1 root       root         24 Jun 14 07:44 function_test.sql -> ..data/function_test.sql
```

UserDefinedSQLObjectsLoader.cpp -> `UserDefinedSQLObjectsLoader::loadObjects()` function, skips soft link file,Unable to load `user_defined` directory functions file.
```cpp
void UserDefinedSQLObjectsLoader::loadObjects(ContextPtr context)
{
    if (unlikely(!enable_persistence))
        return;

    LOG_DEBUG(log, "loading user defined objects");

    String dir_path = context->getUserDefinedPath();
    Poco::DirectoryIterator dir_end;
    for (Poco::DirectoryIterator it(dir_path); it != dir_end; ++it)
    {
        if (it->isLink())
            continue;

        const auto & file_name = it.name();

        /// For '.svn', '.gitignore' directory and similar.
        if (file_name.at(0) == '.')
            continue;

        if (!it->isDirectory() && endsWith(file_name, ".sql"))
        {
            std::string_view object_name = file_name;
            object_name.remove_suffix(strlen(".sql"));
            object_name.remove_prefix(strlen("function_"));
            loadUserDefinedObject(context, UserDefinedSQLObjectType::Function, object_name, dir_path + it.name());
        }
    }
}
```

**Comment by alexey-milovidov** [comment]
@kitaisreal it makes sense not to skip symlinks.

**Comment by DanRoscigno** [comment]
@ygrzjh , if your manifest looks something like this:
```
        volumeMounts:
        - name: customfunction
          mountPath: /etc/clickhouse-server/user_defined/function_test.sql
          readOnly: true
```

adding `subPath` to the mountPath should create the file into the directory, rather than symlinking.

```
        volumeMounts:
        - name: customfunction
          mountPath: /etc/clickhouse-server/user_defined/function_test.sql
          readOnly: true
          subPath: function_test.sql
```

I have done this in the past with config files that needed to be reloaded when changed, the software I was using did not detect the config file change if it was symlinked to, adding the subpath to the file fixed it for me.  Please let us know how it goes.

**Comment by ygrzjh** [comment]
@DanRoscigno Because many function files need to be loaded, configmap is used.

k8s config like this:

functions.yml
```yml
kind: ConfigMap
metadata:
  name: clickhouse-functions
data:
  function_test1.sql: |
    CREATE FUNCTION test1 AS a -> (a * 2)
  function_test2.sql: |
    CREATE FUNCTION test2 AS a -> (a * 2 * 2)
```

server.yml
```yml
      volumes:
        - name: functions
          configMap:
            name: clickhouse-functions
        .......
      containers:
         ......
          volumeMounts:
            - name: functions
              mountPath: /etc/clickhouse-server/user_defined
         ......
```
