### ISSUE TITLE
kill query cannot execute query in readonly mode with 'on cluster'

### ISSUE THREAD

**Issue by ygrzjh** [ClickHouse/ClickHouse#38891]
ClickHouse version: `22.6.2.12`

users.yaml :
```yaml
  public_ro:
    password: "test"
    networks:
      ip: '::/0'
    profile: readonly
    quota: default
    allow_databases:
      - database: public
```

exec result:
- Succeed exec kill query: ` kill query where query_id = 'test';`
```
clickhouse-1-0.clickhouse-headless.default.svc.cluster.local :) kill query where query_id = 'test';

KILL QUERY WHERE query_id = 'test' ASYNC

Query id: a2f0383a-1965-40b1-bf4f-c2535ee92f0a

Ok.

0 rows in set. Elapsed: 0.021 sec.
```

- failed exec kill query on cluster: `kill query on cluster '{cluster}'  where query_id = 'test';`
```
clickhouse-1-0.clickhouse-headless.default.svc.cluster.local :) kill query on cluster '{cluster}'  where query_id = 'test';

KILL QUERY ON CLUSTER `{cluster}` WHERE query_id = 'test' ASYNC

Query id: 0a287700-572c-4b83-b46e-b198bf0b15fd


0 rows in set. Elapsed: 0.022 sec.

Received exception from server (version 22.6.2):
Code: 164. DB::Exception: Received from localhost:9000. DB::Exception: public_ro: Cannot execute query in readonly mode. (READONLY)
```
