### ISSUE TITLE
create ReplicatedMergeTree table error.

### ISSUE THREAD

**Issue by LuPan2015** [ClickHouse/ClickHouse#40296]
- version: 22.73 
- configuration type:  config.yaml
```
ClickHouse client version 22.7.3.5 (official build).
Connecting to 10.0.0.21:9000 as user superset_user.
Connected to ClickHouse server version 22.7.3 revision 54457.

ip-10-0-0-21.ap-east-1.compute.internal :) create table test (
                                            `trip_id` UInt32,
                                            `pickup_date` String )
                                           ENGINE = ReplicatedMergeTree
                                           ORDER BY trip_id
                                           SETTINGS index_granularity = 8192, storage_policy='s3';

CREATE TABLE test
(
    `trip_id` UInt32,
    `pickup_date` String
)
ENGINE = ReplicatedMergeTree
ORDER BY trip_id
SETTINGS index_granularity = 8192, storage_policy = 's3'

Query id: 8183ab5f-d388-47ca-a477-2c6e2be5a460


0 rows in set. Elapsed: 0.077 sec.

Received exception from server (version 22.7.3):
Code: 999. DB::Exception: Received from 10.0.0.21:9000. Coordination::Exception. Coordination::Exception: Bad arguments. (KEEPER_EXCEPTION)
```

error log:
```
2022.08.17 17:49:30.842143 [ 389184 ] {45bc6169-b374-47b0-84db-073547e8a1f5} <Error> executeQuery: Code: 999. Coordination::Exception: Bad arguments. (KEEPER_EXCEPTION) (version 22.7.3.5 (official build)) (from 10.0.0.21:38879) (in query: create table test ( `trip_id` UInt32, `pickup_date` String ) ENGINE = ReplicatedMergeTree ORDER BY trip_id SETTINGS index_granularity = 8192, storage_policy='s3';), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xba37dda in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x18050795 in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error) @ 0x18050d9e in /usr/bin/clickhouse
3. zkutil::ZooKeeper::tryMulti(std::__1::vector<std::__1::shared_ptr<Coordination::Request>, std::__1::allocator<std::__1::shared_ptr<Coordination::Request> > > const&, std::__1::vector<std::__1::shared_ptr<Coordination::Response>, std::__1::allocator<std::__1::shared_ptr<Coordination::Response> > >&) @ 0x1805e182 in /usr/bin/clickhouse
4. DB::StorageReplicatedMergeTree::createTableIfNotExists(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x17212b33 in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, DB::StorageReplicatedMergeTree::RenamingRestrictions) @ 0x1720b0f3 in /usr/bin/clickhouse
6. ? @ 0x177e1f5b in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x1715d306 in /usr/bin/clickhouse
8. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x16b3a116 in /usr/bin/clickhouse
9. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x16b34df3 in /usr/bin/clickhouse
10. DB::InterpreterCreateQuery::execute() @ 0x16b3e220 in /usr/bin/clickhouse
11. ? @ 0x16ecda97 in /usr/bin/clickhouse
12. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x16ecaed5 in /usr/bin/clickhouse
13. DB::TCPHandler::runImpl() @ 0x17b4035c in /usr/bin/clickhouse
14. DB::TCPHandler::run() @ 0x17b533d9 in /usr/bin/clickhouse
15. Poco::Net::TCPServerConnection::start() @ 0x1a98c1b3 in /usr/bin/clickhouse
16. Poco::Net::TCPServerDispatcher::run() @ 0x1a98d5ad in /usr/bin/clickhouse
17. Poco::PooledThread::run() @ 0x1ab4923d in /usr/bin/clickhouse
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x1ab46882 in /usr/bin/clickhouse
19. ? @ 0x7ff254be7609 in ?
20. clone @ 0x7ff254b0e293 in ?
```

**Comment by antonio2368** [comment]
Did you define `<default_replica_path>` in your config?

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/40603#issuecomment-1227145048

**Comment by rpstw** [comment]
I can reproduce this problem with the following steps. However I'm not sure whether it's a  bug or misconfiguration.

I don't believe it is the same issue as #40603 sinceI the generated `/var/lib/clickhouse/preprocessed_configs/config.xml` seems ok.

1. create a config file `/tmp/config.yml`
```yaml
listen_host: 0.0.0.0
logger:
  level: debug

remote_servers:
  default:
    shard:
      internal_replication: true
      replica:
        host: ck1
        port: 9000

prometheus:
  endpoint: /metrics
  port: 8001
  metrics: true
  events: true
  asynchronous_metrics: true

keeper_server:
  tcp_port: 9181
  server_id: 74
  log_storage_path: /var/lib/clickhouse/coordination/log
  snapshot_storage_path: /var/lib/clickhouse/coordination/snapshots
  coordination_settings:
    operation_timeout_ms: 10000
    session_timeout_ms: 30000
    raft_logs_level: warning
  raft_configuration:
    server:
      id: 74
      hostname: ck1
      port: 9444

zookeeper:
  node:
    host: ck1
    port: 9181

macros:
  shard: 1
  replica: 2

default_replica_path: /clickhouse/tables/{shard}/{database}/{table}
default_replica_name: {replica}
```

2. start a new clickhouse-server  with docker
```shell
docker run --rm -it -h ck1 -v /tmp/config.yml:/etc/clickhouse-server/config.d/config.yml --name ck clickhouse/clickhouse-server:22.8.7.34
```

3. try create a table 
```sql
CREATE TABLE test (x Int64) ENGINE = ReplicatedMergeTree ORDER BY x
```
