### ISSUE TITLE
parsing yaml file does not meet expectations

### ISSUE THREAD

**Issue by ygrzjh** [ClickHouse/ClickHouse#40561]
ClickHouse version: `22.7.1.2484`

refer to: `tests/integration/test_config_yaml_full/configs/config.d/test_cluster_with_incorrect_pw.yaml`

yaml config
```yaml
all-replicated:
  secret: default
  shard:
    replica:
      - host: clickhouse-0-0.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-0-1.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-0-2.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-1-0.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-1-1.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-1-2.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-2-0.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-2-1.clickhouse-headless.default.svc.cluster.local
        port: '9000'
      - host: clickhouse-2-2.clickhouse-headless.default.svc.cluster.local
        port: '9000'
```

expected parsing result
```xml
    <all-replicated>
        <secret>default</secret>
        <shard>
            <replica>
                <host>clickhouse-0-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-0-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-0-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-1-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-1-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-1-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-2-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-2-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>clickhouse-2-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
        </shard>
    </all-replicated>
```

actual analysis result
```xml
    <all-replicated>
        <secret>default</secret>
        <shard>
            <replica>
                <host>clickhouse-0-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-0-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-0-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-1-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-1-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-1-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-2-0.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-2-1.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
                <host>clickhouse-2-2.clickhouse-headless.default.svc.cluster.local</host>
                <port>9000</port>
            </replica>
        </shard>
    </all-replicated>
```

**Comment by DerekChia** [comment]
I took a closer look at `test_cluster_with_incorrect_pw.yaml` and noticed that it was not written in the correct format. Have created a PR #40787 to rectify so that it generates the correct XML file.

**Comment by DerekChia** [comment]
@ygrzjh Saw your reply in #40787,  now I see the problem. Let me summarise.

The current `test_cluster_with_incorrect_pw.yaml` 
```
remote_servers:
  test_cluster_with_incorrect_pw:
    shard:
      internal_replication: true
      replica:
        - host: 127.0.0.1
          port: 9000
          password: foo
        - host: 127.0.0.2
          port: 9000
          password: foo
```

got parsed incorrectly into the following XML by ClickHouse.

```
        <test_cluster_with_incorrect_pw>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>127.0.0.1</host>
                    <port>9000</port>
                    <password>foo</password>
                    <host>127.0.0.2</host>
                    <port>9000</port>
                    <password>foo</password>
                </replica>
            </shard>
        </test_cluster_with_incorrect_pw>
```

But according to https://jsonformatter.org/yaml-to-xml, the YAML should be parsed into the following instead. This is what we want. 

```
<?xml version="1.0" encoding="UTF-8" ?>
<remote_servers>
    <test_cluster_with_incorrect_pw>
        <shard>
            <internal_replication>true</internal_replication>
            <replica>
                <host>127.0.0.1</host>
                <port>9000</port>
                <password>foo</password>
            </replica>
            <replica>
                <host>127.0.0.2</host>
                <port>9000</port>
                <password>foo</password>
            </replica>
        </shard>
    </test_cluster_with_incorrect_pw>
</remote_servers>
```

However, the following incorrect YAML with duplicating mapping key `replica`

```
remote_servers:
  test_cluster_with_incorrect_pw:
    shard:
      - internal_replication: true
        replica:
          host: 127.0.0.1
          port: 9000
          password: foo
        replica:
          host: 127.0.0.2
          port: 9000
          password: foo
```

somehow got parsed by ClickHouse correctly. 

```
        <test_cluster_with_incorrect_pw>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>127.0.0.1</host>
                    <port>9000</port>
                    <password>foo</password>
                </replica>
                <replica>
                    <host>127.0.0.2</host>
                    <port>9000</port>
                    <password>foo</password>
                </replica>
            </shard>
        </test_cluster_with_incorrect_pw>
```

Can @alesapin @Felixoid look into this please?

**Comment by Felixoid** [comment]
It looks to me like parsing of yaml configs is broken.

To get the following config:

```xml
<two_remote_shards_at_port_9001_9002>
  <shard>
    <replica>
      <host>localhost</host>
      <port>9001</port>
    </replica>
  </shard>
  <shard>
    <replica>
      <host>localhost</host>
      <port>9002</port>
    </replica>
  </shard>
</two_remote_shards_at_port_9001_9002>
```

the Yaml should be 

```yaml
two_remote_shards_at_port_9001_9002:
- shard:       
  - replica:
      host: localhost
      port: 9001
- shard:           
  - replica:       
      host: localhost
      port: 9002
```

But according to the [example](https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.yaml.example#L549-L556) it looks completely different, although it generates nonsense:

```xml
<test_cluster_two_shards>
  <shard>
    <replica>
      <host>127.0.0.1</host>
      <port>9000</port>
    </replica>
    <replica>
      <host>127.0.0.2</host>
      <port>9000</port>
    </replica>
  </shard>
</test_cluster_two_shards>
```

**Comment by Felixoid** [comment]
the problem with it, I completely lost how to get the following scheme, because yaml can't mix up the maps and lists:

```xml
<test_cluster_with_incorrect_pw>
     <shard>
         <internal_replication>true</internal_replication>
         <replica>
             <host>127.0.0.1</host>
             <port>9000</port>
             <!-- password is incorrect -->
             <password>foo</password>
         </replica>
         <replica>
             <host>127.0.0.2</host>
             <port>9000</port>
             <!-- password is incorrect -->
             <password>foo</password>
         </replica>
     </shard>
</test_cluster_with_incorrect_pw>
```

**Comment by Felixoid** [comment]
Ok, I found a format allowing to get the necessary config:

```yaml
remote_servers:
  test_cluster_with_incorrect_pw:
  - shard:
    - internal_replication: true
    - replica:
        host: 127.0.0.1
        port: 9000
        password: foo
    - replica:
        host: 127.0.0.2
        port: 9000
        password: foo
```

it produces:

```xml
<test_cluster_with_incorrect_pw>
  <shard>
    <internal_replication>true</internal_replication>
    <replica>
      <host>127.0.0.1</host>
      <port>9000</port>
      <password>foo</password>
    </replica>
    <replica>
      <host>127.0.0.2</host>
      <port>9000</port>
      <password>foo</password>
    </replica>
  </shard>
</test_cluster_with_incorrect_pw>
```

Now I am confused. It looks like it matches the format, described in [docs](https://github.com/ClickHouse/ClickHouse/blob/5b5fcc5/docs/en/operations/configuration-files.md?plain=1#L139-L145).

So, we need to take care of the tests, and make everything in order in `tests/integration/test_config_yaml_full/configs/` to match proper documentation.

**Comment by DerekChia** [comment]
Your config produces the following when parsed by https://jsonformatter.org/yaml-to-xml. Doesn't look right...

```
<?xml version="1.0" encoding="UTF-8" ?>
<remote_servers>
    <test_cluster_with_incorrect_pw>
        <shard>
            <internal_replication>true</internal_replication>
        </shard>
        <shard>
            <replica>
                <host>127.0.0.1</host>
                <port>9000</port>
                <password>foo</password>
            </replica>
        </shard>
        <shard>
            <replica>
                <host>127.0.0.2</host>
                <port>9000</port>
                <password>foo</password>
            </replica>
        </shard>
    </test_cluster_with_incorrect_pw>
</remote_servers>

```

**Comment by Felixoid** [comment]
Why do you check some 3d party instead of looking into processed clockhouse config?

**Comment by Felixoid** [comment]
How to get the processed config:

```
ClickHouse/ClickHouse/tests/integration/test_config_yaml_full/configs $ docker run -it --name=clickhouse -u clickhouse -v ${PWD}:/etc/clickhouse-server --rm clickhouse/clickhouse-server:head clickhouse-server -C /etc/clickhouse-server/config.yaml

# in another terminal

$ docker exec -i -t clickhouse cat /var/lib/clickhouse/preprocessed_configs/config.xml | xmllint --format -
```

Then you can get the final config and search for a snippet

**Comment by DerekChia** [comment]
> Why do you check some 3d party instead of looking into processed clickhouse config?

Good point. I just want to make sure ClickHouse does the parsing consistently with other tools. But I guess we got the right YAML now.

**Comment by Felixoid** [comment]
We need a comment from the devs here. I never used YAML before, but it looks to me that it's slightly inconsistent. I'd expect the following snippet works, although it doesn't

```yaml
test_cluster_with_incorrect_pw:
  shard:
  - internal_replication: true
    replica:
      - host: 127.0.0.1
        port: 9000
        password: foo
      - host: 127.0.0.2
        port: 9000
        password: foo
```
