### ISSUE TITLE
Prometheus: invalid metric type "0 gauge"

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#40887]
I deployed ClickHouse and configured Prometheus:

```xml
<prometheus>
  <endpoint>/metrics</endpoint>
  <port>30004</port>

  <metrics>true</metrics>
  <events>true</events>
  <asynchronous_metrics>true</asynchronous_metrics>
  <status_info>true</status_info>
</prometheus>
```

Here is the configuration of Prometheus:

```yaml
  # clickhouse
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['node1:30004/metrics']
```

After Prometheus is started, the following information is displayed indicating that Indicators cannot be identified:
```
invalid metric type "0 gauge"
```
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/14944242/187890976-a82b0e9b-6989-450f-9178-d1f6c413b992.png">

Is there a problem with ClickHouse metrics? I tried to change several versions of Prometheus, but all of them reported this error.

ClickHouse Version：

```
21.8
```

Prometheus Version：

```
2.38.0
```
