### ISSUE TITLE
Errors occurred when modifying column table(one shard all replicas) in the replicated database (2 shards 1 replicas).

### ISSUE THREAD

**Issue by ygrzjh** [ClickHouse/ClickHouse#42854]
Clickhouse version: `22.9.1.2603`

Two ClickHouse nodes. Errors occurred when modifying column table(one shard all replicas) in the replicated database (2 shards 1 replicas). 

SQL
```sql
clickhouse-0-0 :) ALTER TABLE demo.users_dim_local  ADD COLUMN `remark` String;

ALTER TABLE demo.users_dim_local
    ADD COLUMN `remark` String

Query id: c8e0c02d-e41f-4b61-9e72-57d6ff229fac

┌─shard─┬─replica─┬─status─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ 0     │ 0       │ OK     │                   1 │                0 │
└───────┴─────────┴────────┴─────────────────────┴──────────────────┘
↑ Progress: 1.00 rows, 37.00 B (0.05 rows/s., 1.69 B/s.)  49%
1 row in set. Elapsed: 21.838 sec.

Received exception from server (version 22.9.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: There was an error on 1|0: Cannot execute replicated DDL query, maximum retries exceeded (probably it's a bug): While executing DDLQueryStatus. (LOGICAL_ERROR)
```

Log Error
```log
2022.11.01 10:06:57.070039 [ 100 ] {} <Information> demo.users_dim_local (58734866-641a-481c-87b3-3726832e2251): Metadata changed in ZooKeeper. Applying changes locally.
2022.11.01 10:06:57.249903 [ 100 ] {} <Information> demo.users_dim_local (58734866-641a-481c-87b3-3726832e2251): Applied changes to the metadata of the table. Current metadata version: 6
2022.11.01 10:06:57.250709 [ 297 ] {aace891f-2680-4e10-bc0d-1a2b8c30aca9} <Error> executeQuery: Code: 15. DB::Exception: Cannot add column `remark`: column with this name already exists. (DUPLICATE_COLUMN) (version 22.9.1.2603 (official build)) (from 0.0.0.0:0) (in query: /* ddl_entry=query-0000001221 */ ALTER TABLE demo.users_dim_local ADD COLUMN `remark` String), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d80ba in /usr/bin/clickhouse
1. DB::AlterCommands::validate(std::__1::shared_ptr<DB::IStorage> const&, std::__1::shared_ptr<DB::Context const>) const @ 0x12512607 in /usr/bin/clickhouse
2. DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x11fbc8b1 in /usr/bin/clickhouse
3. DB::InterpreterAlterQuery::execute() @ 0x11fba232 in /usr/bin/clickhouse
4. ? @ 0x1237254b in /usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x12377273 in /usr/bin/clickhouse
6. DB::DDLWorker::tryExecuteQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x11a87688 in /usr/bin/clickhouse
7. DB::DDLWorker::tryExecuteQueryOnLeaderReplica(DB::DDLTaskBase&, std::__1::shared_ptr<DB::IStorage>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<zkutil::ZooKeeper> const&, std::__1::unique_ptr<zkutil::ZooKeeperLock, std::__1::default_delete<zkutil::ZooKeeperLock> >&) @ 0x11a8a599 in /usr/bin/clickhouse
8. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::__1::shared_ptr<zkutil::ZooKeeper> const&) @ 0x11a85e5a in /usr/bin/clickhouse
9. DB::DDLWorker::scheduleTasks(bool) @ 0x11a83a13 in /usr/bin/clickhouse
10. DB::DDLWorker::runMainThread() @ 0x11a7ced2 in /usr/bin/clickhouse
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x11a91ec7 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x797a56c in /usr/bin/clickhouse
13. ? @ 0x797fc7e in /usr/bin/clickhouse
14. ? @ 0x7f62b0fd9609 in ?
15. __clone @ 0x7f62b0efe133 in ?
```

### ClickHouse Node Config
Clickhouse cluster with 2 shards and 1 replicas.
- ClickHouse Cluster Config
```yaml
remote_servers:
  default:
    shard:
      - internal_replication: true
        replica:
          - host: clickhouse-0-0
            port: 9000
      - internal_replication: true
        replica:
          - host: clickhouse-1-0
            port: 9000
  all-replicated:
    shard:
      internal_replication: true
      replica:
        - host: clickhouse-0-0
          port: 9000
        - host: clickhouse-1-0
          port: 9000
```

- ClickHouse Node1
macros yaml config
```yaml
macros:
  index: 00
  shard: 0
  replica: 0
  cluster: default
  all: all
```

- ClickHouse Node2
```yaml
macros:
  index: 10
  shard: 1
  replica: 0
  cluster: default
  all: all
```

### DATABASE/TABLE Create sql
- Create Replicated Database (2 shards 1 replicas)
```sql
CREATE DATABASE demo on cluster 'default'
ENGINE = Replicated('/clickhouse/default/demo', '{shard}', '{replica}')
```
- Create Table (one shard all replicas)
```
CREATE TABLE demo.users_dim_local
(
    `#user_id` String ,
    `#device_id` String ,
    `#created_time` UInt64 ,
    `#updated_time` UInt64,
    `sex` String,
    `user_name` String
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{all}', '{index}', `#updated_time`)
PARTITION BY cityHash64(`#user_id`) % 64
ORDER BY `#user_id`
```
