### ISSUE TITLE
Incosistent results in a distributed view of a distributed table

### ISSUE THREAD

**Issue by ismaelestalayo** [ClickHouse/ClickHouse#42967]
**Describe the unexpected behaviour**
After creating a distributed view across my cluster which points to a distributed table, I get around half the results if the query has an if statement inside compared to executing that same query to the distributed table.

**How to reproduce**
* ClickHouse version: 22.7.3.5
* Non-default settings:
  - `use_uncompressed_cache	0`
  - `load_balancing	random`
  - `join_use_nulls	1`
  - `max_memory_usage	10000000000`
  - `max_partitions_per_insert_block	1000`

* CREATE TABLE statements for all tables involved
```sql
CREATE TABLE es_ads.savedad_TEST_local on cluster '{states}' (
    `id` String CODEC(ZSTD(3)),
    `date` UInt64 CODEC(ZSTD(3)),
    `eventname` String CODEC(ZSTD(3)),
    `adid` UInt64 CODEC(ZSTD(3))
)
ENGINE = MergeTree
ORDER BY (id)
SETTINGS index_granularity = 8192;

CREATE TABLE es_ads.savedad_TEST on cluster '{states}' (
    `id` String CODEC(ZSTD(3)),
    `date` UInt64 CODEC(ZSTD(3)),
    `eventname` String CODEC(ZSTD(3)),
    `adid` UInt64 CODEC(ZSTD(3))
)
ENGINE = Distributed('{states}', 'es_ads', 'savedad_TEST_local', rand());
```

```sql
CREATE VIEW es_ads.savedad_TEST_view on cluster '{states}' AS SELECT * FROM es_ads.savedad_TEST;
```
* Sample data for all these tables
```sql
-- the bug of this issue only happens if this INSERT INTO is executed at least twice
INSERT INTO es_ads.savedad_TEST
SELECT toString(id) as id, date, eventname, adid
FROM generateRandom('id UInt16, date Datetime, eventname Text, adid UInt8') LIMIT 50000;
```

* Queries to run that lead to unexpected result

After executing the previous INSERT INTO twice, the table has **100k entries**. The following query simply divides the random adid in groups by their modulo of 3, which should give us three groups of around **33.3k entries each**.
```sql
select adid % 3
  , COUNT()
from es_ads.savedad_TEST_view
group by adid % 3
order by adid % 3 DESC;

modulo|count|
------+-----+
     2|33202|
     1|33138|
     0|33660|
```

However, this result is is not consistent if the **sumIf** aggregation function is added, as the distributed view and distributed table give **different results**:
```sql
select adid % 3
  , COUNT()
  , sumIf(1, adid % 3 = 0) multiplesOfThree
from es_ads.savedad_TEST_view
group by adid % 3
order by adid % 3 DESC;

-- es_ads.savedad_TEST_view
modulo|count|multiplesOfThree|
------+-----+----------------+
     2|24855|               0|
     1|24807|               0|
     0|25298|           25298|

-- es_ads.savedad_TEST
modulo|count|multiplesOfThree|
------+-----+----------------+
     2|33202|               0|
     1|33138|               0|
     0|33660|           33660|
```

**Expected behavior**
The view should give the same results as the distributed table all the time (as this bug is only reproduced if the INSERT INTO is executed at least twice).

**Additional context**
Configuration of the remote servers:
```yaml
servername: twoshardstworeplicas
shards:
  - shard:
    replicas:
      - replica:
        host: "clickhouse1"
        port: 9000
        user: "{{ clickhouse_admin_user }}"
        password: "{{ clickhouse_admin_password }}"
      - replica:
        host: "clickhouse2"
        port: 9000
        user: "{{ clickhouse_admin_user }}"
        password: "{{ clickhouse_admin_password }}"
    internal_replication: false
    insert_quorum: 0
  - shard:
    replicas:
      - replica:
        host: "clickhouse3"
        port: 9000
        user: "{{ clickhouse_admin_user }}"
        password: "{{ clickhouse_admin_password }}"
      - replica:
        host: "clickhouse4"
        port: 9000
        user: "{{ clickhouse_admin_user }}"
        password: "{{ clickhouse_admin_password }}"
    internal_replication: false
    insert_quorum: 0
```
