### ISSUE TITLE
Source address from proxy protocol is not respected

### ISSUE THREAD

**Issue by bianpengyuan** [ClickHouse/ClickHouse#44063]
**Describe the unexpected behaviour**
ClickHouse seems to not respect source IP address from proxy protocol header. I can see proxy protocol `Source Address` is set correctly, but query log and text log still have the IP from previous hop, and I also cannot enforce access with HOST IP. This happens to both http and native interface, and I am using Composite protocol to configure ProxyProtocol endpoint like the following:

```yaml
    protocols:
        tcp:
            type: tcp
            port: 9000
            description: native tcp
        http:
            type: http
            port: 8123
            description: http
        tcp_over_proxy:
            type: proxy1
            impl: tcp
            port: 9011
            description: native over proxyprotocol v1
        http_over_proxy:
            type: proxy1
            impl: http
            port: 8124
            description: http over proxyprotocol v1
```

**Expected behavior**
ClickHouse takes source address from proxy protocol as source IP.
