### ISSUE TITLE
Not all rows copied by `INSERT INTO ... SELECT * FROM ...` query for Distributed tables via HTTP interface

### ISSUE THREAD

**Issue by asp437** [ClickHouse/ClickHouse#44161]
**Describe the unexpected behaviour**
If you try to copy data from one `Distributed` table to another `Distributed` table via query like:
```
INSERT INTO ... SELECT * FROM ...
```
some data may be not copied.

It is worth to mention, behaviour depend on used interface. Bug is reproduced via HTTP interface, but not via native one (`clickhouse-client` on server node).

**How to reproduce**
Server version: `22.9.5.25`

Related files gist: https://gist.github.com/asp437/d898374ef686062d1d5389097174ce99

There is a Docker Compose to start three nodes of the ClickHouse.
Cluster configuration file from gist should be placed in same folder as `docker-compose.yaml`.
Configuration defines three shards with 1 replica in each one.

SQL-query script simply generate table with 1 million of rows and copy data to another table.
After running all queries via HTTP interface, you can check number of rows via `SELECT count(*) FROM test_table_dist2`

Port `8123` is forwarded for one of the nodes to easily test HTTP interface.

**Expected behavior**
- All rows are copied
- Behaviour doesn't depend on used interface

**Comment by tavplubix** [comment]
Seems like `SYSTEM FLUSH DISTRIBUTED` is missing

**Comment by asp437** [comment]
> Seems like `SYSTEM FLUSH DISTRIBUTED` is missing

Added this statement to the end of the script. But it didn't fixed the problem.

**Comment by tavplubix** [comment]
It's still missing after `INSERT INTO test_table_dist SELECT * FROM numbers(1000000)`

**Comment by asp437** [comment]
Added one more, results are same

**Comment by den-crane** [comment]
I cannot reproduce.

I'm using docker desktop and modified yaml (removed config section to use compose up)

```
version: "3.9"
services:
  ch1:
    image: clickhouse/clickhouse-server:22.9.5.25-alpine
    volumes:
      - /Users/denis.zhuravlev/webamg/bug_d/cluster_config.xml:/etc/clickhouse-server/config.d/cluster_config.xml
    environment:
      SHARD_ID: ch1
      REPLICA_ID: ch1
      SERVER_ID: 1
    networks:
      - clickhouse
    ports:
      - "8123:8123"
  ch2:
    image: clickhouse/clickhouse-server:22.9.5.25-alpine
    volumes:
      - /Users/denis.zhuravlev/webamg/bug_d/cluster_config.xml:/etc/clickhouse-server/config.d/cluster_config.xml
    environment:
      SHARD_ID: ch2
      REPLICA_ID: ch2
      SERVER_ID: 2
    networks:
      - clickhouse
  ch3:
    image: clickhouse/clickhouse-server:22.9.5.25-alpine
    volumes:
      - /Users/denis.zhuravlev/webamg/bug_d/cluster_config.xml:/etc/clickhouse-server/config.d/cluster_config.xml
    environment:
      SHARD_ID: ch3
      REPLICA_ID: ch3
      SERVER_ID: 3
    networks:
      - clickhouse
networks:
  clickhouse:
```

```
docker-compose up
```

I run 10 times (using JDBC)

```sql
drop table if exists test_table ON CLUSTER cluster_3S_1R sync;
drop table if exists test_table_dist ON CLUSTER cluster_3S_1R sync;
drop table if exists test_table2 ON CLUSTER cluster_3S_1R sync;
drop table if exists test_table_dist2 ON CLUSTER cluster_3S_1R sync;

CREATE TABLE test_table ON CLUSTER cluster_3S_1R
(
    `id` Int
)
ENGINE = ReplicatedMergeTree
ORDER BY id;

CREATE TABLE test_table_dist ON CLUSTER cluster_3S_1R
(
    `id` Int
)
ENGINE = Distributed('cluster_3S_1R', 'default', 'test_table', id);

INSERT INTO test_table_dist SELECT * FROM numbers(1000000);

SYSTEM FLUSH DISTRIBUTED test_table_dist;

CREATE TABLE test_table2 ON CLUSTER cluster_3S_1R
(
    `id` Int
)
ENGINE = ReplicatedMergeTree
ORDER BY id;

CREATE TABLE test_table_dist2 ON CLUSTER cluster_3S_1R
(
    `id` Int
)
ENGINE = Distributed('cluster_3S_1R', 'default', 'test_table2', id);

INSERT INTO test_table_dist2 SELECT * FROM test_table_dist;

SYSTEM FLUSH DISTRIBUTED test_table_dist2;

select count() from test_table_dist2;

select fqdn() h, count() from test_table_dist2 group by h;

select fqdn() h, count() from test_table_dist group by h;
```

always got 

```
1000000

fa1bb6383260 | 333333
60d7eb340986 | 333333
4e6aaec959f5 | 333334

fa1bb6383260 | 333333
60d7eb340986 | 333333
4e6aaec959f5 | 333334
```
