### ISSUE TITLE
Idea: allow to use subnet scan for cluster discovery.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#46941]
Experimental feature to automatically form clusters from the hosts created within the same subnet if they are reachable.

**Use case**
```
remote_servers:
    cluster_name:
        shard:
            replicas_scan:
                # Attempt connections within this range
                network: '172.31.5.46/20'
                # Usual connection parameters
                port: 9440
                secure: 1
                # Optional - override connect timeout instead of using the default `connect_timeout_with_failover_ms`
                timeout_ms: 10
                # Repeat the scan after the specified number of seconds
                period: 10
```

It can be useful for the `s3Cluster` table function and parallel replicas over shared datasets.

**Alternative options**

Simply list all 4096 hosts in the cluster configuration and hope that it will work.
