### ISSUE TITLE
Crash on kubernetes without any errors

### ISSUE THREAD

**Issue by MatteoGioioso** [ClickHouse/ClickHouse#47998]
I am trying to run clickhouse on kubernetes:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  labels:
    application: clickhouse
spec:
  selector:
    matchLabels:
      application: clickhouse
  serviceName: "my-service"
  template:
    metadata:
      labels:
        application: clickhouse
    spec:
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-claim
      containers:
        - name: clickhouse
          imagePullPolicy: IfNotPresent
          image: clickhouse/clickhouse-server:latest
          volumeMounts:
            - mountPath: "/var/lib/clickhouse"
              name: my-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

```

However the container does crash without any error from the logs:

```
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
Processing configuration file '/etc/clickhouse-server/users.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
// Then it crashes
```

Without volume declaration it works without problem, the same claim works with others containers.

**Expected behavior**
Should work

**Error message and/or stacktrace**
None

---

#### Statefulset events

```
│   Normal   Pulled     14m (x4 over 15m)     kubelet            Container image "clickhouse/clickhouse-server:latest" already present on machine                                     │
│   Normal   Created    14m (x4 over 15m)     kubelet            Created container clickhouse                                                                     │
│   Normal   Started    14m (x4 over 15m)     kubelet            Started container clickhouse                                                                     │
│   Warning  BackOff    4m56s (x48 over 14m)  kubelet            Back-off restarting failed container
```

## More info

Clickhouse version: `ClickHouse server version 22.11.1.1360 (official build)`

**Comment by den-crane** [comment]
see https://altinity.com/blog/fixing-the-dreaded-clickhouse-crash-loop-on-kubernetes

>without any errors 

the error is not flushed to the stdout because pod is terminated to soon.

**Comment by MatteoGioioso** [comment]
Many thanks, that helped to find the error:

```
2023.03.26 07:01:22.045856 [ 203 ] {} <Information> SentryWriter: Sending crash reports is disabled
2023.03.26 07:01:22.055363 [ 203 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2023.03.26 07:01:22.091317 [ 203 ] {} <Information> : Starting ClickHouse 22.11.1.1360 (revision: 54468, git hash: 0d211ed19849fe44b0e43fdebe2c15d76d560a77, build id: 56C3196CFC6A72E495F2DADF428666322D9E7B8A), PID 203
2023.03.26 07:01:22.091462 [ 203 ] {} <Information> Application: starting up
2023.03.26 07:01:22.091485 [ 203 ] {} <Information> Application: OS name: Linux, version: 5.4.0-144-generic, architecture: x86_64
2023.03.26 07:01:22.093345 [ 203 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2023.03.26 07:01:22.093713 [ 203 ] {} <Warning> AsynchronousMetrics: Thermal monitor '3' exists but could not be read: errno: 61, strerror: No data available.
2023.03.26 07:01:22.093755 [ 203 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2023.03.26 07:01:22.093857 [ 203 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2023.03.26 07:01:22.093888 [ 203 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2023.03.26 07:01:22.094215 [ 203 ] {} <Warning> AsynchronousMetrics: Hardware monitor 'iwlwifi_1', sensor '' exists but could not be read: errno: 61, strerror: No data available.
2023.03.26 07:01:22.238172 [ 203 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: B9685E470135D84901442CE1F379D4F3)
2023.03.26 07:01:22.238249 [ 203 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2023.03.26 07:01:22.238697 [ 203 ] {} <Error> Application: DB::Exception: Effective user of the process (root) does not match the owner of the data (clickhouse). Run under 'sudo -u clickhouse'.
2023.03.26 07:01:22.238726 [ 203 ] {} <Information> Application: shutting down
2023.03.26 07:01:22.238735 [ 203 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2023.03.26 07:01:22.238845 [ 204 ] {} <Trace> BaseDaemon: Received signal -2
2023.03.26 07:01:22.238881 [ 204 ] {} <Information> BaseDaemon: Stop SignalListener thread

```

`<Error> Application: DB::Exception: Effective user of the process (root) does not match the owner of the data (clickhouse). Run under 'sudo -u clickhouse'.`

**Comment by MatteoGioioso** [comment]
I really don't understand why this is happening,I have even tried to add security context to the container to not run as root:

```
          securityContext:
            runAsGroup: 101
            runAsUser: 101
```

However I have permission denied:

```
<Error> Application: filesystem error: in create_directories: Permission denied ["/var/lib/clickhouse/data/system"]
```

And that directory seems to have mixed permissions:

```
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 access
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 18:07 bmserver
drwxr-xr-x  6 root       root       4096 Mar 26 07:30 cache
drwxr-xr-x  2 root       root       4096 Mar 25 17:55 clickhouse
drwxr-xr-x  4 root       root       4096 Mar 25 17:16 data
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 18:07 default
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 dictionaries_lib
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 flags
-rw-r--r--  1 root       root          0 Mar 26 07:30 flock.lock
drwxr-xr-x  2 clickhouse clickhouse 4096 Mar 25 17:16 format_schemas
drwxr-xr-x  5 root       root       4096 Mar 25 17:16 indexdb
drwxr-xr-x  2 root       root       4096 Mar 25 17:16 metadata
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 metadata_dropped
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 preprocessed_configs
drwxr-xr-x  2 root       root       4096 Mar 25 17:16 snapshots
drwxr-x--- 38 clickhouse clickhouse 4096 Mar 26 08:00 store
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 18:30 system
drwxr-xr-x  3 clickhouse clickhouse 4096 Mar 26 07:30 tmp
drwxr-xr-x  2 clickhouse clickhouse 4096 Mar 25 17:16 user_files
drwxr-x---  2 clickhouse clickhouse 4096 Mar 25 17:16 user_scripts
-rw-r-----  1 clickhouse clickhouse   36 Mar 25 17:16 uuid
```

Do you have any example on running that image with volume mounts on kubernetes?

**Comment by MatteoGioioso** [comment]
I found a temporary using init containers

```
      initContainers:
        - name: clickhouse-volume-permission
          image: bitnami/bitnami-shell:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - mountPath: "/var/lib/clickhouse"
              name: my-volume
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              chmod 700 /var/lib/clickhouse &&
              chown -R 1001:1001 /var/lib/clickhouse
``` 

Is there a better way to do it?
