### ISSUE TITLE
Attaching part for S3-backed table should not try to PutObject

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#49880]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
When using an S3-backed MergeTree, and running an `attach part...` query, CH fails when it has read only access to the node.

**How to reproduce**
* Which ClickHouse server version to use
`ClickHouse server version 23.4.1 revision 54462`

* Which interface to use, if matters
I am personally using docker locally

* Non-default settings, if any
(keys are local minio they are safe to paste here)
For writing:
```xml
<storage_configuration>
    <disks>
      <s3>
        <type>s3</type>
        <endpoint>http://minio:9000/testbucket/testch/</endpoint>
        <access_key_id>sj1UZdqSGCM9XLHh</access_key_id>
        <secret_access_key>3goX6CJDCc3pXEIyUCnXTwPt9PFfzB2V</secret_access_key>
        <send_metadata>true</send_metadata>
      </s3>
    </disks>
    <policies>
      <s3>
        <volumes>
          <s3>
            <disk>s3</disk>
          </s3>
        </volumes>
      </s3>
    </policies>
  </storage_configuration>
```

Read only node:
```xml
<storage_configuration>
    <disks>
      <s3>
        <type>s3</type>
        <endpoint>http://minio:9000/testbucket/testch/</endpoint>
        <access_key_id>gR80riaeqU5VXeuB</access_key_id>
        <secret_access_key>ERUDqDIu6ee4qbK36jMffD9buK5sshCB</secret_access_key>
        <skip_access_check>true</skip_access_check>
      </s3>
    </disks>
    <policies>
      <s3>
        <volumes>
          <s3>
            <disk>s3</disk>
            <prefer_not_to_merge>true</prefer_not_to_merge>
          </s3>
        </volumes>
      </s3>
    </policies>
  </storage_configuration>
```

* `CREATE TABLE` statements for all tables involved and queries
```sql
CREATE TABLE test_s3
(
    `id` Int64
)
ENGINE = MergeTree
PARTITION BY intDiv(id, 100)
ORDER BY id
SETTINGS storage_policy = 's3'
```

```sql
insert into test_s3 values (1), (2), (3)
```

example with docker compose (replace your uuid)
<details>
<summary>docker-compose.yml</summary>

```
version: "3.7"
name: ch-replicas
networks:
  ch_network:
    driver: bridge
volumes:
  ch-1: null
  ch-2: null
  minio_ch: null
services:
  ch-1:
    image: clickhouse/clickhouse-server
    volumes:
      - ${PWD}/ch-1.xml:/etc/clickhouse-server/config.xml
      - ch-1:/var/lib/clickhouse-server
    depends_on:
      - minio
    networks:
      - ch_network
  ch-2:
    image: clickhouse/clickhouse-server
    volumes:
      - ${PWD}/ch-2.xml:/etc/clickhouse-server/config.xml
      - ch-2:/var/lib/clickhouse-server
    depends_on:
      - minio
    networks:
      - ch_network
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_ch:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    container_name: minio_ch
    networks:
      - ch_network
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/testbucket;
      exit 0;
      "
    networks:
      - ch_network
```
note you will need to make the appropriate keys, here is IAM config for read only keys:

```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "kms:*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:GetObject",
    "s3:ListAllMyBuckets",
    "s3:ListBucket"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
```
</details>

```
docker cp ch-replicas-ch-1-1:/var/lib/clickhouse/disks/s3/store/068/0686618e-a5a6-480c-a38c-e859631bd24e/0_1_1_0 .
docker exec ch-replicas-ch-1-1 mkdir -p /var/lib/clickhouse/disks/s3/store/068/0686618e-a5a6-480c-a38c-e859631bd24e
docker exec ch-replicas-ch-1-1 chmod 777 -R /var/lib/clickhouse/disks/s3/store/068/
```

```sql
ATTACH TABLE test_s3 UUID '0686618e-a5a6-480c-a38c-e859631bd24e'
(
    `id` Int64
)
ENGINE = MergeTree
PARTITION BY intDiv(id, 100)
ORDER BY id
SETTINGS storage_policy = 's3', index_granularity = 8192
```

```
docker cp 0_1_1_0 ch-replicas-ch-1-1:/var/lib/clickhouse/disks/s3/store/068/0686618e-a5a6-480c-a38c-e859631bd24e/detached/0_1_1_0
docker exec ch-replicas-ch-1-1 chmod 777 -R /var/lib/clickhouse/disks/s3/store/068/
```

```sql
ALTER TABLE test_s3 attach part '0_1_1_0'
```

**Expected behavior**
It should not attempt to write to S3. For example when the part is manually moved into the proper file path and CH restarted, the part is attached just fine without the need to write to S3, and CH can query that part.

**Error message and/or stacktrace**
```
2023.05.15 11:33:00.000027 [ 48 ] {610604aa-0b49-4064-afd4-54998ca9b061} <Error> TCPHandler: Code: 499. DB::Exception: Message: Access Denied., Key: testch/txy/iulxtzowphuvbvybdqdvmrwqumwik, Bucket: testbucket, Object size: 1, WithPool: true. (S3_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3b83d5 in /usr/bin/clickhouse
1. ? @ 0x12a790aa in /usr/bin/clickhouse
2. DB::WriteBufferFromS3::processPutRequest(DB::WriteBufferFromS3::PutObjectTask const&) @ 0x12a78e40 in /usr/bin/clickhouse
3. ? @ 0x12a79b7d in /usr/bin/clickhouse
4. ? @ 0x12a5aa9a in /usr/bin/clickhouse
5. ? @ 0x125cbf4f in /usr/bin/clickhouse
6. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe48d6d5 in /usr/bin/clickhouse
7. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe48ff15 in /usr/bin/clickhouse
8. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe489501 in /usr/bin/clickhouse
9. ? @ 0xe48ed81 in /usr/bin/clickhouse
10. ? @ 0x7fc86b122b43 in ?
11. __clone @ 0x7fc86b1b3bb4 in ?
```

**Additional context**
Effectively creating and updating read-only CH nodes that are decoupled from the original cluster.
