### ISSUE TITLE
RabbitMQ Queue ready messages not consumed by Clickhouse table

### ISSUE THREAD

**Issue by dravadhis** [ClickHouse/ClickHouse#50855]
I have an application which uses rabbitmq to send messages across its various components. One of the exchanges among these called `unique` is a `fanout` type exchange and sends messages to 2 different queues. Now I am setting up Clickhouse in my application for making an OLAP dashboard for users. For this, I need to get the messages which are published in the `unique` exchange inside Clickhouse tables. I went through this [article](https://clickhouse.com/docs/en/engines/table-engines/integrations/rabbitmq) and setup my application according to it. All other details of my setup can be found below.

For testing the setup I am publishing messages on the `unique` exchange using the RabbitMQ Management interface (in local setups it is available at `localhost:15672`, I had this port occupied in my system so I assigned it to port `25672`, see docker compose below).  

After this, I created the table connected to rabbitmq `unique` exchange first, then published the messages and then created the MV. In this case, before creating the MV, the queue created by Clickhouse shows the message in ready status. However those messages never enter the exchange table (I inspected the table after setting `stream_like_engine_allow_direct_select = 1`). The messages remain in the queue as ready. 
Now when I create the MV, all the messages that were lying in the queue and any subsequent new messages get the `unack` status. At this point alsodo these messages do not enter the MV or the second or the first table.

I am using the [latest](https://hub.docker.com/r/clickhouse/clickhouse-server/) official docker image for clickhouse: v23.5.2.7

**How to reproduce**
I used these steps to create the table to get msgs from the exchange.
```
CREATE DATABASE lbt;

USE lbt;

CREATE TABLE IF NOT EXISTS lbt.listens_from_unique 
(
 `user_id` Int64,
 `user_name` String,
 `timestamp` UInt32,
 `track_metadata` Tuple(track_name String, additional_info Tuple(recording_mbid String), artist_name String),
 `recording_msid` String
) 
ENGINE = RabbitMQ
SETTINGS 
 rabbitmq_host_port = 'rabbitmq:5672',
 rabbitmq_exchange_name = 'unique',
 rabbitmq_exchange_type = 'fanout',
 rabbitmq_format = 'JSONEachRow';
```
I then published some messages in the `unique` exchange using this interface of RabbitMQ:
![image](https://github.com/ClickHouse/ClickHouse/assets/56121942/8068e88c-d71f-4d67-b187-7c576f2356ea)

Now I inspected the queue created by clickhouse which appears like this:
![image](https://github.com/ClickHouse/ClickHouse/assets/56121942/d4817fdd-b51c-44aa-83c9-b2fadec42089)

After this I created the second table and MV with:
```
CREATE TABLE IF NOT EXISTS lbt.olap_listens_store
(
 `user_id` Int64,
 `user_name` String,
 `timestamp` UInt32,
 `track_metadata` Tuple(track_name String, additional_info Tuple(recording_mbid String), artist_name String),
 `recording_msid` String
) 
ENGINE = MergeTree()
ORDER BY user_id;

CREATE MATERIALIZED VIEW lbt.consumer TO lbt.olap_listens_store AS SELECT * FROM lbt.listens_from_unique;
```
As soon as the MV is created, the messages get unack:
![image](https://github.com/ClickHouse/ClickHouse/assets/56121942/1cca1ca8-be35-44c1-b2bb-16d7b49bd25f)

And they are not in the MV, in the second and the first table as I inspected using SELECT queries.

**Expected behavior**
As the docs mention, the messages should have entered the exchange table and then should have been ingested into the second table. However the messages are not entering the table.

I also tried to do create all the table and MVs first and then publish messages. That directly brought me to the unack stage.

Part of Docker Compose:
```
  rabbitmq:
    image: rabbitmq:3.8.16-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq:z
    ports:
      - "127.0.0.1:25672:15672"

  # clickhouse client is not required to be included as another service.
  clickhouse_server:
    image: clickhouse/clickhouse-server
    volumes:
    # Currently clickhouse data is stored in volume. If need to access 
    # clickhouse files directly, change 'clickhouse_store' to bind mount
      - clickhouse_store:/var/lib/clickhouse
      - clickhouse_store:/var/log/clickhouse-server
      - ./services/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ./services/clickhouse/metrika.xml:/etc/clickhouse-server/config.d/metrika.xml
      - ./services/clickhouse/users.xml:/etc/clickhouse-server/config.d/users.xml
    ports:
      - "8123:8123"
```

config.xml:
```
<?xml version="1.0"?>
<clickhouse>
     <logger>
        <!-- Possible levels: https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Logger.h#L105 -->
        <level>trace</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
        <!-- <console>1</console> --> <!-- Default behavior is autodetection (log to console if not daemon mode and is tty) -->
    </logger>

    <http_port>8123</http_port>
    <path>/var/lib/clickhouse/</path>
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
    <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
    <users_config>users.xml</users_config>
    <default_profile>default</default_profile>

    <rabbitmq>
        <username>guest</username>
        <password>guest</password>
    </rabbitmq>

</clickhouse>
```
