### ISSUE TITLE
<Error> Application: Code: 425. DB::ErrnoException: Cannot getifaddrs, errno: 13, strerror: Permission denied.

### ISSUE THREAD

**Issue by lil5** [ClickHouse/ClickHouse#50892]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

docker

**Source of the ClickHouse**

postgres in conjunction with plausible analytics

**Expected result**

It to work, for some reason it works fine on my Mac but on a linux VPS, nope.

**The actual result**

Tones of errors like:

1. This seems to be a warning and not a big deal
`<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.`

2. Here is where it borks:
`2023.06.12 15:29:42.905535 [ 51 ] {} <Error> Application: Code: 425. DB::ErrnoException: Cannot getifaddrs, errno: 13, strerror: Permission denied. `

```log
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | <jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.
cl-dev-plausible-clickhouse-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
cl-dev-plausible-clickhouse-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
cl-dev-plausible-clickhouse-1  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
cl-dev-plausible-clickhouse-1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
cl-dev-plausible-clickhouse-1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
cl-dev-plausible-clickhouse-1  | 2023.06.12 15:29:42.905535 [ 51 ] {} <Error> Application: Code: 425. DB::ErrnoException: Cannot getifaddrs, errno: 13, strerror: Permission denied. (SYSTEM_ERROR), Stack trace (when copying this message, always include the lines below):
cl-dev-plausible-clickhouse-1  | 
cl-dev-plausible-clickhouse-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3b7135 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 1. ? @ 0xe3b7e73 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 2. DB::throwFromErrno(String const&, int, int) @ 0xe3b7d1e in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 3. DB::isLocalAddress(Poco::Net::IPAddress const&) @ 0xe57b6c2 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 4. DB::Cluster::Address::Address(Poco::Util::AbstractConfiguration const&, String const&, String const&, String const&, unsigned int, unsigned int) @ 0x1303b00d in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 5. DB::Cluster::Cluster(Poco::Util::AbstractConfiguration const&, DB::Settings const&, String const&, String const&) @ 0x1304160a in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 6. DB::Clusters::updateClusters(Poco::Util::AbstractConfiguration const&, DB::Settings const&, String const&, Poco::Util::AbstractConfiguration*) @ 0x1303f08b in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 7. DB::Clusters::Clusters(Poco::Util::AbstractConfiguration const&, DB::Settings const&, std::shared_ptr<DB::Macros const>, String const&) @ 0x1303e2fa in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 8. DB::Context::setClustersConfig(Poco::AutoPtr<Poco::Util::AbstractConfiguration> const&, bool, String const&) @ 0x13082736 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 9. ? @ 0xe468599 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 10. DB::ConfigReloader::reloadIfNewer(bool, bool, bool, bool) @ 0x15287b94 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 11. DB::ConfigReloader::ConfigReloader(String const&, String const&, String const&, zkutil::ZooKeeperNodeCache&&, std::shared_ptr<Poco::Event> const&, std::function<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>, bool)>&&, bool) @ 0x152863aa in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 12. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0xe44aa17 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 13. Poco::Util::Application::run() @ 0x17c701e2 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 14. DB::Server::run() @ 0xe43d4bc in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 15. Poco::Util::ServerApplication::run(int, char**) @ 0x17c83a3a in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 16. mainEntryClickHouseServer(int, char**) @ 0xe43a07c in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 17. main @ 0x8b33b73 in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  | 18. ? @ 0x7fbdf91b8d90 in ?
cl-dev-plausible-clickhouse-1  | 19. __libc_start_main @ 0x7fbdf91b8e40 in ?
cl-dev-plausible-clickhouse-1  | 20. _start @ 0x81609ee in /usr/bin/clickhouse
cl-dev-plausible-clickhouse-1  |  (version 23.4.3.48 (official build))
cl-dev-plausible-clickhouse-1  | 2023.06.12 15:29:42.905921 [ 51 ] {} <Error> Application: DB::ErrnoException: Cannot getifaddrs, errno: 13, strerror: Permission denied
```

**How to reproduce**

Create the following files and then run `docker compose up`

docker-compose.yml
```yml
version: "3.3"

name: cl-plausible

services:
  db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_USER=plausible
      - POSTGRES_PASSWORD=SAMmqTrm38dwu4osxPW7o8mAs

  clickhouse:
    image: clickhouse/clickhouse-server:22.6-alpine
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    environment:
      - CLICKHOUSE_DB=plausible
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v1.5
    command: sh -c "sleep 20 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - db
      - clickhouse
    ports:
      - 127.0.0.1:80:8000
    environment:
      - SECRET_KEY_BASE=FAdvHUr5zS1HBL2WcO8ldGriaZnUoQMBJRXnzwYAA7xqj6Hg4/JTTR4TFWsToYUvNBHvVmRp+CEbyiMzlWWJng==
      - DATABASE_URL=postgres://plausible:SAMmqTrm38dwu4osxPW7o8mAs@db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://clickhouse:8123/plausible
      - CLICKHOUSE_FLUSH_INTERVAL_MS=5000
      - CLICKHOUSE_MAX_BUFFER_SIZE=10000
      - BASE_URL=http://localhost
      - PORT=8000
      - LISTEN_IP=0.0.0.0
      - DISABLE_REGISTRATION=true

volumes:
  db-data:
  clickhouse-data:
```

clickhouse-config.xml
```xml
<clickhouse>
    <logger>
        <level>warning</level>
        <console>true</console>
    </logger>

    <!-- Stop all the unnecessary logging -->
    <query_thread_log remove="remove"/>
    <query_log remove="remove"/>
    <text_log remove="remove"/>
    <trace_log remove="remove"/>
    <metric_log remove="remove"/>
    <asynchronous_metric_log remove="remove"/>
    <session_log remove="remove"/>
    <part_log remove="remove"/>
</clickhouse>
```

clickhouse-user-config.xml
```xml
<clickhouse>
    <profiles>
        <default>
            <log_queries>0</log_queries>
            <log_query_threads>0</log_query_threads>
        </default>
    </profiles>
</clickhouse>
```
