### ISSUE TITLE
Query performance between 23.x and 22.x is quite different

### ISSUE THREAD

**Issue by wzjjack** [ClickHouse/ClickHouse#51849]
**Describe what's wrong**

See the following image

<img width="1057" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/52395237/7d77e89b-1f18-4e74-a6aa-f106d59b02d5">

There is a table named `flows`, I am going to push more than 50 million rows, everything looks fine when I push 2 -3 million rows, the query time cost is expected, 0.5 sec, and processed 2.5 million rows. But if I continue push more rows to the table, and once it reach to the 3+ million rows, the query cost rapid growth to the 15 sec. That is sooooo weird.

I am running the clickhouse under docker and use the default configurations.

Docker compose
```
version: "3.2"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23
    restart: unless-stopped
    container_name: local-clickhouse-d
    user: 1000:1000
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./db:/var/lib/clickhouse
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M
        reservations:
          memory: 200M
```

And, if I clean up the db and downgrade the clickhouse image  to `clickhouse/clickhouse-server:22-alpine`, and restarting push the rows from beginning, everything works fine, even I push 7+ million rows.

<img width="1153" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/52395237/5f3aa3e1-781f-4cc3-87a4-609ac8f395f5">

Do I missing something or need update some configurations?

BTW, there are 30+ columns in the table `flows`, and 5 skip indexes.
