### ISSUE TITLE
Clickhouse ignores memory settings from docker-compose.yml

### ISSUE THREAD

**Issue by softshape** [ClickHouse/ClickHouse#53434]
Hi all,

as clickhouse is running on the same server with our Java app, we try to restrict its memory usage via settings in docker-compose.yml -

```
  clickhouse:
     image: clickhouse/clickhouse-server:latest
     restart: always
     environment:
       CLICKHOUSE_USER: ${CLICKHOUSE_USER}
       CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
       CLICKHOUSEUSERCONFIG: max_server_memory_usage=5000000000,quotas/interval/default/duration=7200,max_partitions_per_insert_block=5000 
```

But then during the work it can consume 8-10 Gb of RAM. Looking at the settings (SELECT * FROM system.settings;) we see -

max_memory_usage = 10000000000
max_memory_usage_for_user = 0

Why clickhouse ignores our memory settings?
