### ISSUE TITLE
In high-concurrency scenarios, the performance of ClickHouse Keeper is lower than that of ZooKeeper.

### ISSUE THREAD

**Issue by countryroadscn** [ClickHouse/ClickHouse#53798]
I have built three-node clusters for both ZooKeeper and Keeper on the same machines. The performance of ZooKeeper is better than that of Keeper in high-concurrency scenarios.
Here's the version and configuration information for ZooKeeper and Keeper:
ZooKeeper:
Version: 3.5.6
config:
```
tickTime=2000
initLimit=300
syncLimit=30
maxClientCnxns=2000
maxSessionTimeout=60000000
dataDir=/data1/zookeeper_data
dataLogDir=/data1/zookeeper_wal/logs
autopurge.snapRetainCount=10
autopurge.purgeInterval=1
preAllocSize=131072
preAllocSize=131072
snapCount=3000000
leaderServes=yes
standaloneEnabled=false
clientPort=7181 
skipACL=yes
4lw.commands.whitelist=*
reconfigEnabled=true
```

Keeper:
Version: 23.7
build_options:
```
VERSION_FULL    ClickHouse 23.7.4.1
VERSION_DESCRIBE        v23.7.4.1-stable
VERSION_INTEGER 23007004
SYSTEM  Linux
VERSION_GITHASH bd9a510550c89a8d624488c9d474982d682c338d
VERSION_REVISION        54476
VERSION_DATE
BUILD_TYPE      Release
SYSTEM_PROCESSOR        x86_64
CMAKE_VERSION   3.22.1
C_COMPILER      /data1/ldb_toolchain/bin/clang-16
C_COMPILER_VERSION      16.0.6
CXX_COMPILER    /data1/ldb_toolchain/bin/clang++-16
CXX_COMPILER_VERSION    16.0.6
C_FLAGS  --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Wno-enum-constexpr-conversion  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O3 -DNDEBUG
CXX_FLAGS        --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Wno-enum-constexpr-conversion -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O3 -DNDEBUG
LINK_FLAGS       --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/data1/ldb_toolchain/bin/ld.lld-16 -rdynamic -Wl,--build-id=sha1 -no-pie -Wl,-no-pie
BUILD_COMPILE_DEFINITIONS
USE_EMBEDDED_COMPILER   1
USE_GLIBC_COMPATIBILITY ON
USE_JEMALLOC    ON
USE_ICU 1
USE_H3  1
USE_MYSQL       1
USE_RDKAFKA     1
USE_CAPNP       1
USE_BASE64      1
USE_HDFS        1
USE_SNAPPY      1
USE_PARQUET     1
USE_PROTOBUF    1
USE_BROTLI      1
USE_SSL 1
OPENSSL_VERSION 1.1.1g
OPENSSL_IS_BORING_SSL   1
USE_VECTORSCAN  ON
USE_SIMDJSON    1
USE_ODBC        1
USE_GRPC        1
USE_LDAP        1
TZDATA_VERSION  2023c
USE_KRB5        1
USE_FILELOG     1
USE_BZIP2       1
USE_AMQPCPP     1
USE_ROCKSDB     1
USE_NURAFT      1
USE_NLP 1
USE_LIBURING    1
USE_SQLITE      1
USE_LIBPQXX     1
USE_AZURE_BLOB_STORAGE  1
USE_AWS_S3      1
USE_CASSANDRA   1
USE_YAML_CPP    1
USE_SENTRY      1
USE_DATASKETCHES        1
USE_AVRO        1
USE_ARROW       1
USE_ORC 1
USE_MSGPACK     1
USE_QPL ON
GIT_HASH        d20b1c8a2b39cd6f59dd2342badbd12be2226cac
GIT_BRANCH      23.7
GIT_DATE        2023-08-07 16:28:32 +0000
GIT_COMMIT_SUBJECT      Merge pull request #53116 from ClickHouse/backport/23.7/53111
```

config:

    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>11</server_id>
        <log_storage_path>/data1/clickhouse_test_keeper/keeper_server/coordination/logs</log_storage_path>
        <snapshot_storage_path>/data2/clickhouse_test_keeper/keeper_server/coordination/snapshots</snapshot_storage_path>
        <enable_reconfiguration>true</enable_reconfiguration>

        <coordination_settings>
              <operation_timeout_ms>10000</operation_timeout_ms>
              <session_timeout_ms>30000</session_timeout_ms>
              <raft_logs_level>error</raft_logs_level>
              <quorum_reads>false</quorum_reads>
              <compress_logs>true</compress_logs>
              <force_sync>true</force_sync>
              <max_requests_batch_size>100</max_requests_batch_size>
              <compress_snapshots_with_zstd_format>false</compress_snapshots_with_zstd_format>
        </coordination_settings>

        <raft_configuration>
            <server>
                <id>11</id>
                <hostname>10.152.32.40</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>12</id>
                <hostname>10.152.32.36</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>13</id>
                <hostname>10.152.32.47</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>

Firstly, we used YCSB for performance testing. 

./bin/ycsb load zookeeper -s -threads 100 -P workloads/workloadb -p zookeeper.connectString=10.152.32.40:9181,10.152.32.47:9181,10.152.32.36:9181/benchmark -p recordcount=10000 > OutputLoad.txt

./bin/ycsb run zookeeper -s -threads 100 -P workloads/workloadb -p zookeeper.connectString=10.152.32.40:9181,10.152.32.47:9181,10.152.32.36:9181/benchmark -p operationcount=10000 -p readproportion=1 -p updateproportion=0 > OutputRun.txt

The test results are as follows:

(1) Keeper + fsync
1) load
```
[OVERALL], RunTime(ms), 11347
[OVERALL], Throughput(ops/sec), 881.2902088657795
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 40
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.35251608354631175
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 40
[TOTAL_GC_TIME_%], Time(%), 0.35251608354631175
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 1654219.52
[CLEANUP], MinLatency(us), 106880
[CLEANUP], MaxLatency(us), 4411391
[CLEANUP], 95thPercentileLatency(us), 3104767
[CLEANUP], 99thPercentileLatency(us), 4313087
[INSERT], Operations, 10000
[INSERT], AverageLatency(us), 43866.5385
[INSERT], MinLatency(us), 1520
[INSERT], MaxLatency(us), 1905663
[INSERT], 95thPercentileLatency(us), 202495
[INSERT], 99thPercentileLatency(us), 809983
[INSERT], Return=OK, 10000
```

2) run
```
[OVERALL], RunTime(ms), 11542
[OVERALL], Throughput(ops/sec), 866.4009703690868
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 43
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.3725524172587073
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 43
[TOTAL_GC_TIME_%], Time(%), 0.3725524172587073
[READ], Operations, 10000
[READ], AverageLatency(us), 56547.33
[READ], MinLatency(us), 159
[READ], MaxLatency(us), 804863
[READ], 95thPercentileLatency(us), 401151
[READ], 99thPercentileLatency(us), 505087
[READ], Return=OK, 10000
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 530993.28
[CLEANUP], MinLatency(us), 102784
[CLEANUP], MaxLatency(us), 1304575
[CLEANUP], 95thPercentileLatency(us), 912383
[CLEANUP], 99thPercentileLatency(us), 1204223
```

**Load QPS: 881, Run QPS: 866.**

(2) Keeper + no fsync
1) load
```
[OVERALL], RunTime(ms), 10821
[OVERALL], Throughput(ops/sec), 924.129008409574
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 49
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.45282321412069126
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 49
[TOTAL_GC_TIME_%], Time(%), 0.45282321412069126
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 649095.68
[CLEANUP], MinLatency(us), 101376
[CLEANUP], MaxLatency(us), 1507327
[CLEANUP], 95thPercentileLatency(us), 1306623
[CLEANUP], 99thPercentileLatency(us), 1505279
[INSERT], Operations, 10000
[INSERT], AverageLatency(us), 48110.2591
[INSERT], MinLatency(us), 522
[INSERT], MaxLatency(us), 1108991
[INSERT], 95thPercentileLatency(us), 301823
[INSERT], 99thPercentileLatency(us), 702463
[INSERT], Return=OK, 10000
```

2) run
```
[OVERALL], RunTime(ms), 12262
[OVERALL], Throughput(ops/sec), 815.5276463872125
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 16
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.13048442342195402
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 16
[TOTAL_GC_TIME_%], Time(%), 0.13048442342195402
[READ], Operations, 10000
[READ], AverageLatency(us), 61022.9226
[READ], MinLatency(us), 166
[READ], MaxLatency(us), 1008127
[READ], 95thPercentileLatency(us), 314623
[READ], 99thPercentileLatency(us), 804351
[READ], Return=OK, 10000
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 781351.68
[CLEANUP], MinLatency(us), 101248
[CLEANUP], MaxLatency(us), 1807359
[CLEANUP], 95thPercentileLatency(us), 1506303
[CLEANUP], 99thPercentileLatency(us), 1807359
```
**Load QPS: 924, Run QPS: 815.**

(3) ZooKeeper
1) load
```
[OVERALL], RunTime(ms), 10920
[OVERALL], Throughput(ops/sec), 915.7509157509157
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 82
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.7509157509157509
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 82
[TOTAL_GC_TIME_%], Time(%), 0.7509157509157509
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 4809575.68
[CLEANUP], MinLatency(us), 105792
[CLEANUP], MaxLatency(us), 9863167
[CLEANUP], 95thPercentileLatency(us), 9265151
[CLEANUP], 99thPercentileLatency(us), 9666559
[INSERT], Operations, 10000
[INSERT], AverageLatency(us), 7205.9985
[INSERT], MinLatency(us), 626
[INSERT], MaxLatency(us), 183679
[INSERT], 95thPercentileLatency(us), 15999
[INSERT], 99thPercentileLatency(us), 98943
[INSERT], Return=OK, 10000
```
 
2) run
```
[OVERALL], RunTime(ms), 11087
[OVERALL], Throughput(ops/sec), 901.9572472264815
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 25
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.22548931180662035
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 25
[TOTAL_GC_TIME_%], Time(%), 0.22548931180662035
[READ], Operations, 10000
[READ], AverageLatency(us), 17959.3214
[READ], MinLatency(us), 197
[READ], MaxLatency(us), 312319
[READ], 95thPercentileLatency(us), 74815
[READ], 99thPercentileLatency(us), 122175
[READ], Return=OK, 10000
[CLEANUP], Operations, 100
[CLEANUP], AverageLatency(us), 4053059.2
[CLEANUP], MinLatency(us), 101696
[CLEANUP], MaxLatency(us), 9199615
[CLEANUP], 95thPercentileLatency(us), 8593407
[CLEANUP], 99thPercentileLatency(us), 9101311
```
**Load QPS: 902, Run QPS: 916.**

Keeper's performance is lower than that of ZooKeeper.But it's comparable to ZooKeeper. 

Then, we used keeper-bench for performance testing. When testing ZooKeeper using the list request, an Unimplemented exception is thrown. To ensure fair test results, our testing requests do not include the list request. The configuration file of keeper-bench is as follows:
```
concurrency: 100
iterations: 10000
delay: 4
timelimit: 300
continue_on_errors: true

connections:
  secure: false
  operation_timeout_ms: 2000
  session_timeout_ms: 2000
  connection_timeout_ms: 50000

  connection:
    host: "10.152.32.40:9181"
    sessions: 20
  connection:
    host: "10.152.32.47:9181"
    sessions: 20
  connection:
    host: "10.152.32.36:9181"
    sessions: 20


generator:
  setup:
    node:
      name: "test3"
    node:
      name: "test_create"
    node:
      name: "test4"
    node:
      name: "test"
      data: "somedata"
      node:
        repeat: 4
        name:
          random_string:
            size: 15
        data:
          random_string:
            size:
              min_value: 10
              max_value: 20
      node:
        repeat: 2
        node:
          repeat: 2
          name:
            random_string:
              size: 12
        name:
          random_string:
            size: 15
        data:
          random_string:
            size:
              min_value: 10
              max_value: 20
    node:
      name: "test2"
      data: "somedata"
  requests:
    create:
      path: "/test_create"
      name_length: 10
      remove_factor: 0.5
    multi:
      size: 20
      create:
        path: "/test"
        data:
          random_string:
            size:
              min_value: 10
              max_value: 20
        remove_factor: 0.8
      set:
        weight: 2
        path: 
          - "/test3"
          - "/test4"
        path:
          children_of: "/test"
        data:
          random_string:
            size: 10
    get:
      path: 
        - "/test3"
        - "/test4"
      path:
        children_of: "/test"

    # multi:
    #   weight: 10
    #   get:
    #     path: 
    #       - "/test3"
    #       - "/test4"
    #     path:
    #       children_of: "/test"
    #   list:
    #     path: 
    #       - "/test3"
    #     path:
    #       children_of: "/test"

    # list:
    #   path: 
    #     - "/test3"
    #     - "/test4"
    #   path:
    #     children_of: "/test"


output:
  file: 
    path: "keeper_output.json"
    with_timestamp: false
  stdout: true
```

The performance of 'keeper + no fsync' is better than 'keeper + fsync', so we will only present the test results for 'keeper + no fsync' below.

The test results are as follows:

(1) concurrency=20, sessions=10
```
keeper:
    read_results: 
        "total_requests": 3310,
        "requests_per_second": 14704.686796834982,
        "bytes_per_second": 1713002.7192564314,
    write_results: 
        "total_requests": 6690,
        "requests_per_second": 10531.929338468108,
        "bytes_per_second": 9568678.136604162,


zookeeper:
    read_results: 
        "total_requests": 3294,
        "requests_per_second": 7276.104876194116,
        "bytes_per_second": 845545.6774933885,
    write_results: 
        "total_requests": 6706,
        "requests_per_second": 5974.621756149457,
        "bytes_per_second": 5861291.03949732,
```
**Keeper outperforms ZooKeeper in both read and write operations.**

(2) concurrency=50, sessions=10
```
keeper：
    read_results: 
        "total_requests": 3371,
        "requests_per_second": 17340.27808641518,
        "bytes_per_second": 2014167.6913428445,
    write_results: 
        "total_requests": 6629,
        "requests_per_second": 14595.340711044311,
        "bytes_per_second": 13160014.781607995,
zookeeper：
    read_results: 
        "total_requests": 3339,
        "requests_per_second": 20667.807244069532,
        "bytes_per_second": 2404361.099212902,
    write_results: 
        "total_requests": 6661,
        "requests_per_second": 19213.15981166546,
        "bytes_per_second": 19152757.052377654,
```
**ZooKeeper outperforms Keeper in both read and write operations.**

(3) concurrency=50, sessions=20
```
keeper：
    read_results: 
        "total_requests": 3293,
        "requests_per_second": 17255.697471833337,
        "bytes_per_second": 2008708.860908074,
    "write_results: 
        "total_requests": 6707,
        "requests_per_second": 14660.485495299921,
        "bytes_per_second": 13320671.879099148,
zookeeper：
    read_results: 
        "total_requests": 3418,
        "requests_per_second": 18936.273401228387,
        "bytes_per_second": 2206397.1806337658,
    write_results: 
        "total_requests": 6582,
        "requests_per_second": 17531.74452364716,
        "bytes_per_second": 17524353.063444619,
```
**ZooKeeper outperforms Keeper in both read and write operations.**

(4) concurrency=100, sessions=20
```
keeper：
    read_results: 
        "total_requests": 3302,
        "requests_per_second": 19769.39024243487,
        "bytes_per_second": 2296254.790200489,
    write_results: 
        "total_requests": 6698,
        "requests_per_second": 16518.49672111046,
        "bytes_per_second": 15016418.369673204,
zookeeper：
    read_results: 
        "total_requests": 3383,
        "requests_per_second": 29875.03000307846,
        "bytes_per_second": 3473389.499213959,
    write_results: 
        "total_requests": 6617,
        "requests_per_second": 28435.039342586362,
        "bytes_per_second": 27722607.747076408,
```
**At this point, the read performance of ZooKeeper is 1.58 times that of Keeper, and the write performance is 1.7 times that of Keeper.**

As the concurrency increases, ZooKeeper becomes superior to Keeper.
