### ISSUE TITLE
Clickhouse docker : Permission denied ["/opt/homebrew"]

### ISSUE THREAD

**Issue by LPauzies** [ClickHouse/ClickHouse#54573]
**Describe the unexpected behaviour**
I'm trying to build a docker compose with image from official repository and configuration exisiting inside `/etc/clickhouse-server`.

**How to reproduce**
Here is the docker compose stuff i'm using :

```
version: '3'

services:
  click_server:
    image: clickhouse/clickhouse-server
    restart: on-failure
    environment:
    - CLICKHOUSE_PASSWORD=clickhouse
    - CLICKHOUSE_USER=default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./dbfiles:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - /etc/clickhouse-server:/etc/clickhouse-server

  click_client:
    image: yandex/clickhouse-client
    restart: on-failure
    entrypoint:
      - /bin/sleep
    command:
      - infinity
```

Just do "docker compose up" targetting the compose file above.

**Expected behavior**
We should have a clickhouse container working using the configurations created in `/etc/clickhouse-server` in local.
I should be able to change the configuration, relaunch the compose and be happy.

**Error message and/or stacktrace**
Here is the stack trace I have, after setting every permissions/own correctly in `/etc/clickhouse-server` :

```
Cannot print extra info for Poco::Exception (version 23.8.2.7 (official build))
2023.09.13 10:41:58.498408 [ 1 ] {} <Error> Application: filesystem error: in create_directories: Permission denied ["/opt/homebrew"]
2023.09.13 10:42:05.414380 [ 1 ] {} <Warning> AsynchronousMetrics: Thermal monitor '5' exists but could not be read: errno: 5, strerror: Input/output error.
2023.09.13 10:42:05.418443 [ 1 ] {} <Warning> AsynchronousMetrics: Thermal monitor '7' exists but could not be read: errno: 61, strerror: No data available.
2023.09.13 10:42:05.423648 [ 1 ] {} <Warning> AsynchronousMetrics: Hardware monitor 'iwlwifi_1', sensor '1' exists but could not be read: errno: 61, strerror: No data available.
2023.09.13 10:42:05.426349 [ 1 ] {} <Warning> AsynchronousMetrics: Hardware monitor 'thinkpad', sensor '2' exists but could not be read: errno: 6, strerror: No such device or address.
2023.09.13 10:42:05.431848 [ 1 ] {} <Warning> AsynchronousMetrics: Hardware monitor 'thinkpad', sensor '8' exists but could not be read: errno: 6, strerror: No such device or address.
2023.09.13 10:42:05.592953 [ 1 ] {} <Error> Application: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/opt/homebrew"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001801b995 in /usr/bin/clickhouse
1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15000](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x000000000c64ce61 in /usr/bin/clickhouse
2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15000]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000017fd11ba in /usr/bin/clickhouse
3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<bool>::report(std::error_code const&) const (.llvm.1265764629379838660) @ 0x0000000017fd4676 in /usr/bin/clickhouse
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4e79 in /usr/bin/clickhouse
5. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4f15 in /usr/bin/clickhouse
6. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4f15 in /usr/bin/clickhouse
7. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4f15 in /usr/bin/clickhouse
8. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4f15 in /usr/bin/clickhouse
9. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017fd4f15 in /usr/bin/clickhouse
10. DB::KeeperContext::initializeDisks(Poco::Util::AbstractConfiguration const&) @ 0x000000001368bf6b in /usr/bin/clickhouse
11. DB::KeeperContext::initialize(Poco::Util::AbstractConfiguration const&, DB::KeeperDispatcher*) @ 0x000000001368af4d in /usr/bin/clickhouse
12. DB::KeeperDispatcher::initialize(Poco::Util::AbstractConfiguration const&, bool, bool, std::shared_ptr<DB::Macros const> const&) @ 0x00000000136942ca in /usr/bin/clickhouse
13. DB::Context::initializeKeeperDispatcher(bool) const @ 0x000000001162e073 in /usr/bin/clickhouse
14. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000c69b1fc in /usr/bin/clickhouse
15. Poco::Util::Application::run() @ 0x0000000015b1e706 in /usr/bin/clickhouse
16. DB::Server::run() @ 0x000000000c68bcbe in /usr/bin/clickhouse
17. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000015b2d819 in /usr/bin/clickhouse
18. mainEntryClickHouseServer(int, char**) @ 0x000000000c688a8a in /usr/bin/clickhouse
19. main @ 0x0000000007111f8f in /usr/bin/clickhouse
20. ? @ 0x00007f263da5e083 in ?
21. _start @ 0x000000000634716e in /usr/bin/clickhouse

Cannot print extra info for Poco::Exception (version 23.8.2.7 (official build))
2023.09.13 10:42:05.593034 [ 1 ] {} <Error> Application: filesystem error: in create_directories: Permission denied ["/opt/homebrew"]
```
