### ISSUE TITLE
'Cannot open file tmp[...]' during RESTORE DATABASE query

### ISSUE THREAD

**Issue by mwtrew** [ClickHouse/ClickHouse#54621]
**Describe the unexpected behaviour**
Hello, I'm using the official ClickHouse docker image and I'm having a seemingly permissions-related issue with `RESTORE DATABASE`, although I'm not sure which permissions to check.

**How to reproduce**
* Which ClickHouse server version to use: `clickhouse/clickhouse-server:22.8.13.20-alpine`
* Queries to run that lead to unexpected result: `docker exec -i events_db clickhouse-client --query "RESTORE DATABASE events_db FROM Disk('backups', 'clickhouse-db.zip') SETTINGS allow_non_empty_tables=true"`

**Expected behavior**
The database restore succeeds.

**Error message and/or stacktrace**
```
Received exception from server (version 22.8.13):
Code: 76. DB::Exception: Received from localhost:9000. DB::ErrnoException. DB::ErrnoException: Cannot open file tmp1mdaaaa, errno: 13, strerror: Permission denied. (CANNOT_OPEN_FILE)
(query: RESTORE DATABASE events_db FROM Disk('backups', 'clickhouse-db.zip') SETTINGS allow_non_empty_tables=true)
```

**Additional context**
 * `clickhouse-db.zip` was created using a `BACKUP DATABASE ...` query which ran without issue, and has open permissions.
 * Compose file:
```
version: "3.3"
services:
  events_db:
    image: clickhouse/clickhouse-server:22.8.13.20-alpine
#   ... 
    volumes:
      - event-data:/var/lib/clickhouse
      - /local/data/backup:/backups
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-backup-config.xml:/etc/clickhouse-server/config.d/backup_disk.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    container_name: events_db

  event-data:
    driver: local
# ...
```

 * Backup config:
```
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/backups/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/backups/</allowed_path>
    </backups>
</clickhouse>
```

Any advice or comments would be much appreciated.
