### ISSUE TITLE
Query Parameters are not working with custom HTTP handlers

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#55393]
I've added this to the `config.d` folder:

```
➜  config.d git:(master) ✗ cat handler.yml
http_handlers:
  defaults:
  rule:
    - url: /clickhouse
      methods: GET
      handler:
        type: predefined_query_handler
        query: "SELECT 1, {value: UInt64};"
        content_type: text/plain; charset=utf-8
```

When I query it with `curl`:

```
➜  ~ curl 'http://localhost:8123/clickhouse'
Code: 456. DB::Exception: Substitution `value` is not set. (UNKNOWN_QUERY_PARAMETER) (version 23.10.1.1)
➜  ~ curl 'http://localhost:8123/clickhouse/?param_value=1'
Code: 62. DB::Exception: Empty query. (SYNTAX_ERROR) (version 23.10.1.1)
```
