### ISSUE TITLE
MongoDB engine unstable - DB::Exception: I/O error: Failed to read from socket

### ISSUE THREAD

**Issue by coderbuzz** [ClickHouse/ClickHouse#57289]
> Please make sure that the version you're using is still supported:

Docker: clickhouse/clickhouse-server:23-alpine

1. create table ENGINE = MongoDB
2. on first several selects it is okay no problem
3. after that, on several days cannot select again with error: MongoDB DB::Exception: I/O error: Failed to read from socket

**Solution:**
1. restart server
2. OR drop and re-create table
3. but after several days it happens again

**Comment by melvynator** [comment]
Is there any logs on the ClickHouse side?

**Comment by coderbuzz** [comment]
> Is there any logs on the ClickHouse side?

Hi sorry for waiting, it need several days to reproduce and now it come, here attached the logs

[Terminal Saved Output.txt](https://github.com/ClickHouse/ClickHouse/files/13555716/Terminal.Saved.Output.txt)

Restarting the server solve the issue (*for a while)

**Comment by evillique** [comment]
What is the version of MongoDB you are using?

**Comment by coderbuzz** [comment]
> What is the version of MongoDB you are using?

MongoDB 4.4.24 Community

**Comment by jbrinksmeier** [comment]
We are experiencing this as well with mongodb 5.0.13 CE.

**Comment by jbrinksmeier** [comment]
To us, this is happening when clickhouse looses connection to mongodb once. When the link comes up again, clickhouse is not picking it up on its own, requiring a restart or recreation of the database as @coderbuzz described. Is this the same thing you're experiencing @coderbuzz? Or shall I open a separate issue on this?

**Comment by coderbuzz** [comment]
Yes apparently that was the same issue.
We still experiencing this although upgrading to CH atest version

**Comment by jbrinksmeier** [comment]
Is there a way to get POCO retrying connections, maybe for an (configurable?) interval? C++ is sadly not my strong suit^^

**Comment by jbrinksmeier** [comment]
This is reproducible with a small docker-compose, if this is helpful I may push this to a repository or post it here in this conversation

**Comment by evillique** [comment]
@jbrinksmeier It would be very helpful, thank you!

**Comment by jbrinksmeier** [comment]
alright, here goes.
Use this docker-compose.yml:
```yaml
version: '3.4'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    environment:
      CLICKHOUSE_DB: mongo
      CLICKHOUSE_PASSWORD: mongo
      CLICKHOUSE_USER: mongo
    volumes:
      - db-data:/var/lib/clickhouse:rw
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    volumes:
      - mongodb-data:/data/db:rw

volumes:
  db-data:
  mongodb-data:
```

`exec` into the mongodb container and run
```bash
$ mongo # enter mongosh
$ use hello # create test database
$ db.hello_from.insert({name: "Dandelion"}) # create a test record
```

`exec` into the clickhouse container and run:

```bash
clickhouse client -umongo --password mongo -n <<-EOSQL
  DROP DATABASE IF EXISTS mongo;
  CREATE DATABASE mongo;
  CREATE TABLE mongo.HelloFrom (
      _id String,
      name String
  ) ENGINE=MongoDB('mongodb:27017', 'hello', 'hello_from', '', '', 'connectTimeoutMS=10000');
EOSQL
```

Still in the clickhouse container, verify the connection:
```bash
clickhouse client -umongo --password mongo -n <<-EOSQL
  SELECT * from mongo.HelloFrom;
EOSQL
```

Now stop the mongodb container and bring it back on:
```bash
$ docker compose stop mongodb
$ docker compose up -d
```

In the cliickhouse container, try to query the DB once again as in the verification step, it will throw, even though the mongodb is back and reachable:
```bash
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: I/O error: Failed to read from socket. (POCO_EXCEPTION)
```
