### ISSUE TITLE
Server logging level in is displayed in numeric, not verbal format

### ISSUE THREAD

**Issue by ilyadiff** [ClickHouse/ClickHouse#57355]
**Describe the unexpected behaviour**
When I configured output format of /var/log/clickhouse-server/clickhouse-server.log to JSON, I see in result 
numeric format of logging level field instead of word-descriptive

**How to reproduce**
* Version 22.9.7.34

* Part of modfied config.yaml
```
logger:
    level: information
    log: /var/log/clickhouse-server/clickhouse-server.log
    errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
    size: 1000M
    count: 10
    formatting:
      type: json
      names:
        date_time: date_time
        thread_name: thread_name
        thread_id: thread_id
        level: level
        query_id: query_id
        logger_name: logger_name
        message: message
        source_file: source_file
        source_line: source_line
```

**Result:**
```
"date_time": "1701251707.746062",
"thread_name": "",
"thread_id": "1609392",
"level": "5",    <<<<<<<<<<<<<<<< 
"query_id": "",
"logger_name": 
....
"source_line": "557"

```
**Expected behavior**
```
"date_time": "1701251707.746062",
"thread_name": "",
"thread_id": "1609392",
"level": "Warning",    <<<<<<<<<<<<<<<< i.e. Warning, Error, Debug (or WARN, ERROR, DEBUG)
"query_id": "",
"logger_name": 
....
"source_line": "557"
```

Also I tried to configure withoun "names" section:
```
logger:
    level: information
    log: /var/log/clickhouse-server/clickhouse-server.log
    errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
    size: 1000M
    count: 10
    formatting:
      type: json
```

But it did not bring success.
I consider this abnormal behavior, or it is necessary to explicitly configure the choice of such an output format. How can this be fixed?
