### ISSUE TITLE
Distributed queries is giving inconsistency output between replicas and shards

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#57382]
I have 3 shards and 2 replicas of clickhouse cluster and also zookeeper with 3 znodes for replication in my eks cluster. In that, I created a database called "app" with the replicated engine in all shards and replicas (i.e., in all 6 pods). After I created a mergeTree table called "alerts_storage"( which is created in other shards and replicas because of the replicated database engine) for storing the data. On top of it, I have created a distributed table called "alerts" for inserting and retrieving the data evenly in all pods.

Clickhouse config:
`

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  defaults:
    replicasUseFQDN: "no"
    distributedDDL:
      profile: admin_profile
    templates:
      podTemplate: clickhouse-pod
      dataVolumeClaimTemplate: clickhouse-storage
      serviceTemplate: clickhouse-svc
  configuration:
    users:
      default/networks/host_regexp: clickhouse.svc.cluster.local$
      default/networks/ip:
        - 127.0.0.1
        - 0.0.0.0
      admin/networks/host_regexp: clickhouse.svc.cluster.local$
      admin/networks/ip:
        - 127.0.0.1
        - 0.0.0.0
      admin/k8s_secret_password: clickhouse/clickhouse-operator-altinity-clickhouse-operator/password
      admin/access_management: 1
      admin/named_collection_control: 1
      admin/show_named_collections: 1
      admin/show_named_collections_secrets: 1
      admin/profile: admin_profile
      admin/quote: admin_quote
    profiles:
      admin_profile/max_memory_usage: 600000000000
      admin_profile/readonly: 0
      admin_profile/max_insert_threads: 32
    quotas:
      admin_quota/interval/duration: 3600
      admin_quota/interval/queries: 0
      admin_quota/interval/errors: 0
      admin_quota/interval/result_rows: 0
      admin_quota/interval/read_rows: 0
      admin_quota/interval/execution_time: 0
    settings:
      disable_internal_dns_cache: 1
    files:
      conf.d/chop-generated-storage.xml: |
        <yandex>
            <storage_configuration>
                <disks>
                    <default>
                        <metadata_path>/var/lib/clickhouse/</metadata_path>
                    </default>
                    <fast_ssd>
                        <path>/mnt/fast_ssd/clickhouse/</path>
                    </fast_ssd>
                    <s3>
                        <type>s3</type>
                        <endpoint>S3 URL</endpoint>
                        <use_environment_credentials>true</use_environment_credentials>
                        <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path>
                    </s3>
                </disks>
                <policies>
                    <moving_from_hot_to_cold>
                        <volumes>
                            <default>
                                <disk>default</disk>
                            </default>
                            <hot>
                                <disk>fast_ssd</disk>
                            </hot>
                            <cold>
                                <disk>s3</disk>
                            </cold>
                        </volumes>
                    </moving_from_hot_to_cold>
            	</policies>
            </storage_configuration>
        </yandex>
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo-keeper
          port: 2181
        - host: zookeeper-1.zookeepers.zoo-keeper
          port: 2181
        - host: zookeeper-2.zookeepers.zoo-keeper
          port: 2181
    clusters:
      - name: prod-cluster
        templates:
          podTemplate: clickhouse-pod
          dataVolumeClaimTemplate: clickhouse-storage
        layout:
          shardsCount: 3
          replicasCount: 2
          shards:
            - name: shard0
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
            - name: shard1
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
            - name: shard2
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
  templates:
    serviceTemplates:
      - name: clickhouse-svc
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          externalTrafficPolicy: Cluster
          type: LoadBalancer
    podTemplates:
      - name: clickhouse-pod
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.7
              resources:
                limits:
                  cpu: "3"
                  memory: 8Gi
                requests:
                  cpu: "2"
                  memory: 6Gi
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```

`
              
 I have inserted million of data in "alerts" table in one month. But when I try select number of count() in alerts table where source='high', it giving inconsistency output in replicas and shards
 
 In 3 pods, chi-clickhouse-prod-cluster-shard0-0-0, chi-clickhouse-prod-cluster-shard1-0-0, chi-clickhouse-prod-cluster-shard2-0-0 it giving below output
 
```
 SELECT count()
FROM alerts
WHERE source = 'high'

Query id: 81a6ed42-5583-4b9d-957b-9a69bccbac40

┌─count()─┐
│    1389 │
└─────────┘

1 row in set. Elapsed: 0.232 sec. Processed 56.50 million rows, 1.02 GB (243.85 million rows/s., 4.39 GB/s.)
```

In 3 pods, chi-clickhouse-prod-cluster-shard0-1-0, chi-clickhouse-prod-cluster-shard1-1-0, chi-clickhouse-prod-cluster-shard2-1-0, it giving below output

```
SELECT count()
FROM alerts
WHERE source = 'high'

Query id: 4c07a903-7ad6-4c92-bbc2-1ac86dcf8691

┌─count()─┐
│    1489 │
└─────────┘

1 row in set. Elapsed: 0.216 sec. Processed 56.96 million rows, 1.03 GB (263.13 million rows/s., 4.74 GB/s.)
```

Why there is inconsistency in output between shards and replicas? Can anyone from clickhouse help here.. what might be cause of this issue?
