### ISSUE TITLE
Inconsistent response from https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8919F6BD2B48D754

### ISSUE THREAD

**Issue by kotik-adjust** [ClickHouse/ClickHouse#57415]
**Installation type**

Packages

**Source of the ClickHouse**

```
for i in {1..5}; do curl -s https://keyserver.ubuntu.com/pks/lookup\?op\=get\&search\=0x8919F6BD2B48D754 > $i.txt && shasum -a 256 $i.txt; done
```

**Expected result**

```
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  1.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  2.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  3.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  4.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  5.txt
```

**The actual result**

```
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  1.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  2.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  3.txt
6a7a340aafdd1b1be8b6c7d4b03aa46341a4550e1c85889a0d939ce868fee19e  4.txt
db4a4076d5714ecd746c9dca2f987f38df84a57447ee88b06a395dc63047e87a  5.txt ( <--- )
```

**How to reproduce**

See above. This is an intermittent issue, so please try multiple times.

**Why do I care?**
```
- name: Install by APT | Add repo
  ansible.builtin.deb822_repository:
    name: clickhouse
    types: deb
    uris: https://packages.clickhouse.com/deb
    suites: lts
    components: main
    architectures: amd64
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8919F6BD2B48D754"
```

From time to time Ansible flags this step as "changed" even though nothing has changed
