### ISSUE TITLE
distributed table can't query in cluster dicovery mode

### ISSUE THREAD

**Issue by gogodjzhu** [ClickHouse/ClickHouse#58030]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I trying to deploy clickhouse in cluster dicovery mode, but it seems the data can't be query out.

**How to reproduce**
* Which ClickHouse server version to use -- 23.4

I deploy test cluster by docker-compose, manifest is like below. In summary:
 - Cluster contains three node: chnode1-3, which are organized in cluster-discovery mode
 - create local table and distributed table on cluster
 - after insert a single row into local table in chnode-1, expect to query that out in chnode2 and chnode3 by distributed table. But got nothing.
 - What's more, I can get data when I using manual-config to deploy cluster.

#### docker-compose.yml
```yaml
version: '3.3'
services:
  zookeeper:
    image: zookeeper:3.4.9
    container_name: ch-zookeeper
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    environment:
      - TZ=Asia/Shanghai
      - ZOO_MY_ID=1
  chnode1:
    image: clickhouse/clickhouse-server:23.4
    container_name: chnode1
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
      - type: 'bind'
        source: './config/remote-servers.xml'
        target: '/etc/clickhouse-server/config.d/remote-servers.xml'
      - type: 'bind'
        source: './config/use-keeper.xml'
        target: '/etc/clickhouse-server/config.d/use-keeper.xml'
  chnode2:
    image: clickhouse/clickhouse-server:23.4
    container_name: chnode2
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
      - type: 'bind'
        source: './config/remote-servers.xml'
        target: '/etc/clickhouse-server/config.d/remote-servers.xml'
      - type: 'bind'
        source: './config/use-keeper.xml'
        target: '/etc/clickhouse-server/config.d/use-keeper.xml'
  chnode3:
    image: clickhouse/clickhouse-server:23.4
    container_name: chnode3
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
      - type: 'bind'
        source: './config/remote-servers.xml'
        target: '/etc/clickhouse-server/config.d/remote-servers.xml'
      - type: 'bind'
        source: './config/use-keeper.xml'
        target: '/etc/clickhouse-server/config.d/use-keeper.xml'
  ```
#### ./config/use-keeper.xml
```xml
<clickhouse>
    <zookeeper>
        <node index="1">
            <host>ch-zookeeper</host>
            <port>2181</port>
        </node>
    </zookeeper>
</clickhouse>
```

#### ./config/remote-servers.xml
```xml
<clickhouse>
    <allow_experimental_cluster_discovery>1</allow_experimental_cluster_discovery>
    <remote_servers replace="true">
        <cluster_NS_1R>
            <discovery>
                <internal_replication>false</internal_replication>
                <path>/clickhouse/discovery/cluster_NS_1R</path>
                <shard>1</shard>
            </discovery>
        </cluster_NS_1R>
    </remote_servers>
</clickhouse>
```

#### ./config/remote-servers.xml
```xml
<clickhouse>
    <remote_servers replace="true">
        <cluster_NS_1R>
            <secret>mysecretphrase</secret>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chnode1</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chnode2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>false</internal_replication>
                <replica>
                    <host>chnode3</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster_NS_1R>
    </remote_servers>
</clickhouse>
```

## Test to query from distributed table after insert into local table
```
-- on chnode1
CREATE DATABASE db1 ON CLUSTER cluster_NS_1R;

CREATE TABLE db1.table1 ON CLUSTER cluster_NS_1R
(
    `id` UInt64,
    `column1` String
)
ENGINE = MergeTree
ORDER BY id;

CREATE TABLE db1.table1_dist ON CLUSTER cluster_NS_1R
(
    `id` UInt64,
    `column1` String
)
ENGINE = Distributed('cluster_NS_1R', 'db1', 'table1', rand());

INSERT INTO db1.table1 (id, column1) VALUES (3, 'abc');

select * from db1.table1_dist; -- return one row, is ok


-- on chnode2 or chnode3
select * from db1.table1_dist; -- return none in cluster-discover mode, but ok in manual-config
```
