### ISSUE TITLE
max_distributed_connections and distributed_connections_pool_size behavior 

### ISSUE THREAD

**Issue by CMBCKSRL** [ClickHouse/ClickHouse#58144]
I have local docker-compose installation consisting of 3 CH instances: 

- 2 shards of cluster `ch_cluster` with MergeTree table `test_mt` on each of them;
- 1 node with only `Distributed` table `test_d` that looks at `test_mt` on `ch_cluster` nodes.

Like this 
```
services:
  ch1:
    image: clickhouse/clickhouse-server:23.3
    hostname: ch1
    volumes:
      - ./ch1/config.xml:/etc/clickhouse-server/config.xml
      - ./ch1/users.d:/etc/clickhouse-server/users.d
      - ./ch1/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main

  ch2:
    image: clickhouse/clickhouse-server:23.3
    hostname: ch2
    volumes:
      - ./ch2/config.xml:/etc/clickhouse-server/config.xml
      - ./ch2/users.d:/etc/clickhouse-server/users.d
      - ./ch2/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main

  ch3:
    image: clickhouse/clickhouse-server:23.3
    hostname: ch3
    volumes:
      - ./ch3/config.xml:/etc/clickhouse-server/config.xml
      - ./ch3/users.d:/etc/clickhouse-server/users.d
      - ./ch3/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - main
    depends_on:
      - ch1
      - ch2
```
And `remote_servers` on each one:
```
      <remote_servers>
        <ch_cluster>
             <shard>
                 <replica>
                     <host>ch1</host>
                     <port>9000</port>
                 </replica>
             </shard>
             <shard>
                 <replica>
                     <host>ch2</host>
                     <port>9000</port>
                 </replica>
             </shard>
        </ch_cluster>
    </remote_servers>
```

Also there are `CREATE TABLE` and `INSERT` scripts:
```
-- on ch_cluster shards (ch1 and ch2)
CREATE TABLE IF NOT EXISTS test_mt
(
    a UInt64,
    b UInt64,
    c UInt64
) ENGINE = MergeTree
ORDER BY a;

-- on ch3
CREATE TABLE IF NOT EXISTS test_d
(
    a UInt64,
    b UInt64,
    c UInt64
) ENGINE = Distributed('ch_cluster', 'default', 'test_mt', rand());

INSERT INTO test_d
SELECT number, number%5, number + 10
FROM numbers(1000);
```

Here is my querstion:
I set `distributed_connections_pool_size=1` and expect queries to `test_d` with different `max_distributed_connections` setting to be identical.

However, when I run the following `SELECT` query 
```
SELECT
    a % 5 AS new_a,
    sum(b) AS sum
FROM test_d
GROUP BY new_a
UNION ALL
SELECT
    a % 3 AS new_a,
    sum(b) AS sum
FROM test_d
GROUP BY new_a
SETTING max_distributed_connections=1;
```
and change `max_distributed_connections` to 2 and 10 values, in `query_log` I see that `thread_ids` array contains 5, 6 and 10 threads respectively.

Could you please explain this behavior?
