### ISSUE TITLE
Projection issue multiple tables

### ISSUE THREAD

**Issue by someone-ignore-please** [ClickHouse/ClickHouse#58215]
**Describe what's wrong**

I found this issue in ClickHouse, in which I have multiple tables that have the same column structure and the same projection name for each table. 

If I query from Table A using the same projection column. it returns results from the other tables if the variable is found.

**Does it reproduce on recent release?**

Yes

**How to reproduce**

* Create table A using the following schema 
```
CREATE TABLE events_house (
    `timestamp` String DEFAULT '',
    `name` String DEFAULT '',
    `party_size` Float32,
    `location` String DEFAULT '',
    `ingestionDateTime` DateTime DEFAULT now(),
    PROJECTION projection_by_name
    (
        SELECT *
        ORDER BY name
    )
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{events_house}/{shard}', '{replica}', timestamp)
PARTITION BY toYearWeek(timestamp)
PRIMARY KEY timestamp
ORDER BY (timestamp, party_size, ip)
```

```
CREATE TABLE events_company (
    `timestamp` String DEFAULT '',
    `name` String DEFAULT '',
    `party_size` Float32,
    `location` String DEFAULT '',
    `ingestionDateTime` DateTime DEFAULT now(),
    PROJECTION projection_by_name
    (
        SELECT *
        ORDER BY name
    )
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{events_company}/{shard}', '{replica}', timestamp)
PARTITION BY toYearWeek(timestamp)
PRIMARY KEY timestamp
ORDER BY (timestamp, party_size, ip)
```
* Seed the two tables and make sure you have the same name in both tables.
```
INSERT INTO events_house VALUES ('1985‑09‑25 17:45:30', 'James', 33, 'Street AB');
INSERT INTO events_house VALUES ('1985‑12‑05 17:45:30', 'Steve', 33, 'Street AB')
INSERT INTO events_house VALUES ('1985‑02‑25 17:45:30', 'James', 33, 'Street AB')

INSERT INTO events_company VALUES ('2012‑09‑25 17:45:30', 'John', 33, 'Street AB')
INSERT INTO events_company VALUES ('2000‑09‑25 17:45:30', 'James', 33, 'Street AB')
```
* Search using the name
```
SELECT * 
FROM events_house
WHERE name = "James"
```
* I'll get results from table `events_company`

**Expected behavior**

I should only get results from `events_house`

**Additional context**

I thought about writing a PR to fix the issue, but I wanted to make sure is it a bug or its expected to behave like this.

**Comment by den-crane** [comment]
What clickhouse version do you use?

I cannot reproduce it https://fiddle.clickhouse.com/e19004b8-4014-4b63-8212-ee943b66ec34

**Comment by disorientresuscitate** [comment]
I have the same issue, but my scenario is different. the data are inserted using a distributed table. I have to rename the projection name to be unique for each table to fix the issue. 

clickhouse version I used is 23.7.2.25.

**Comment by den-crane** [comment]
@disorientresuscitate  Do you have a reproducible example ? At least provide tables DDLs and queries.

https://fiddle.clickhouse.com/8b4bd271-8d0c-4231-a2ca-5099ad48e963

**Comment by den-crane** [comment]
@amosbird  Do you have an idea, are this possible?

**Comment by tavplubix** [comment]
It's nearly impossible

**Comment by amosbird** [comment]
Perhaps macro `{events_house}` and `{events_company}` are identical, which means these two tables are replicas of each other.

**Comment by someone-ignore-please** [comment]
@den-crane the version I use is 23.6.1.1524

@amosbird the two tables macro is kinda different, I use the following `/clickhouse/{uuid}/{shard}/{replica}`

**Comment by den-crane** [comment]
@someone-ignore-please reproducible example please 
23.6 is out of support

**Comment by someone-ignore-please** [comment]
@den-crane I tried to reproducible the issue using the `fiddle.clickhouse.com` but it wouldn't show.. but in my own server and using docker the same issue happened.. 

I also noticed when I search using `name LIKE 'J%mes'` it wouldn't use projection, but on `fiddle.clickhouse.com` it uses it

**Comment by den-crane** [comment]
@someone-ignore-please which version do you use with a docker? You can share docker-compose which reproduces it?
Maybe you use some specific settings? Share `select name,value from system.settings where changed`

**Comment by someone-ignore-please** [comment]
@den-crane 

```
version: '3.5'
services:
  zookeeper:
    image: clickhouse/clickhouse-keeper:23.6.1.1524
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
    ports:
      - "9181:9181"
    volumes:
      - ${PWD}/clickhouse-keeper:/etc/clickhouse-keeper
      - type: volume
        source: keeper
        target: /var/lib/clickhouse
  clickhouse01:
    image: clickhouse/clickhouse-server:23.6.1.1524
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
      - type: volume
        source: ch01
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:23.6.1.1524
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
      - type: volume
        source: ch02
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:23.6.1.1524
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
      - type: volume
        source: ch03
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:23.6.1.1524
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ${PWD}/clickhouse04:/etc/clickhouse-server
      - type: volume
        source: ch04
        target: /var/lib/clickhouse
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24

volumes:
  keeper:
  ch01:
  ch02:
  ch03:
  ch04:
```


```
SELECT
    name,
    value
FROM system.settings
WHERE changed

Query id: fc554f7a-e791-470f-b463-f3f554160227

┌─name───────────────────┬─value───────┐
│ use_uncompressed_cache │ 0           │
│ load_balancing         │ in_order    │
│ log_queries            │ 1           │
│ max_memory_usage       │ 10000000000 │
└────────────────────────┴─────────────┘

4 rows in set. Elapsed: 0.002 sec.
```
