### ISSUE TITLE
Can't remove index files from datapart using the drop index statement.

### ISSUE THREAD

**Issue by MochiXu** [ClickHouse/ClickHouse#59039]
**Describe what's wrong**

Can't remove index files from `datapart` using the `drop index` statement.
Theoretically, the `alter drop index` statement should trigger a mutation, which in the new `datapart` would remove the related `skip-index` files. However, when I delete `inverted` indexes from the table, I found that they are not deleted in the datapart (the inverted index file extension is `.gin_xx`).

**Does it reproduce on recent release?**
Yes, using release date `2024-01-05` can reproduce this bug.
image: `clickhouse/clickhouse-server:latest`
Digest: `sha256:2ff5796c67e8d588273a5f3f84184b9cdaa39a324bcf74abd3652d818d755f8c`

**How to reproduce**

* Which ClickHouse server version to use

I'm using the latest `clickhouse-server`
```bash
❯ docker pull clickhouse/clickhouse-server:latest
latest: Pulling from clickhouse/clickhouse-server
Digest: sha256:2ff5796c67e8d588273a5f3f84184b9cdaa39a324bcf74abd3652d818d755f8c
Status: Image is up to date for clickhouse/clickhouse-server:latest
docker.io/clickhouse/clickhouse-server:latest
```
Here is my `docker-compose.yaml`, you can run `docker compose up` to start it.
```yaml
version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - '8123:8123'
      - '9000:9000'
      - '8998:8998'
      - '9363:9363'
      - '9116:9116'
    ulimits:
      memlock: -1
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/data:/var/lib/clickhouse
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/log:/var/log/clickhouse-server
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/config:/etc/clickhouse-server
```
* Queries to run that lead to unexpected result

_Step1. create table for test_
```sql
DROP TABLE IF EXISTS simple_table_curd SYNC;

CREATE TABLE simple_table_curd
(
    `id` UInt64,
    `doc` String,
    INDEX text_idx doc TYPE inverted GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 2, index_granularity_bytes = '10Mi', min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0;
```

 _Step2. insert some sample data_
```sql
INSERT INTO simple_table_curd VALUES (0, 'Ancient empires rise and fall, shaping history''s course.'),(1, 'Artistic expressions reflect diverse cultural heritages.'),(2, 'Social movements transform societies, forging new paths.'),(3, 'Economies fluctuate, reflecting the complex interplay of global forces.'),(4, 'Strategic military campaigns alter the balance of power.'),(5, 'Quantum leaps redefine understanding of physical laws.'),(6, 'Chemical reactions unlock mysteries of nature.'), (7, 'Philosophical debates ponder the essence of existence.'),(8, 'Marriages blend traditions, celebrating love''s union.'),(9, 'Explorers discover uncharted territories, expanding world maps.'),(10, 'Innovations in technology drive societal progress.'),(11, 'Environmental conservation efforts protect Earth''s biodiversity.'),(12, 'Diplomatic negotiations seek to resolve international conflicts.'),(13, 'Ancient philosophies provide wisdom for modern dilemmas.'),(14, 'Economic theories debate the merits of market systems.'),(15, 'Military strategies evolve with technological advancements.'),(16, 'Physics theories delve into the universe''s mysteries.'),(17, 'Chemical compounds play crucial roles in medical breakthroughs.'),(18, 'Philosophers debate ethics in the age of artificial intelligence.'),(19, 'Wedding ceremonies across cultures symbolize lifelong commitment.');
```

 _Step3. pay attention to inverted files stored in datapart_

<img width="1497" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/42711279/1be4f9f9-33a9-4054-8569-2808e665c79a">

Datapart stored 6 index files, 2 of them is skip-index files, 4 of them is gin-index files.

 _Step4. drop inverted index_

```sql
ALTER TABLE simple_table_curd DROP INDEX text_idx;
```
<img width="1494" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/42711279/7ba28714-5de0-479b-ac69-b371a38b044a">

As you can see, the two skip-index files were deleted, but the gin-index index files were not successfully removed.

**Expected behavior**

I hope that the gin-index files can also be deleted by Alter Drop Index statement.

<img width="1499" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/42711279/e35782a5-77d4-4568-ba9b-dbb3ac94865b">
