### ISSUE TITLE
Multiple `grants` `query` tags don't work in .yml

### ISSUE THREAD

**Issue by DarkWanderer** [ClickHouse/ClickHouse#59927]
**Describe the unexpected behaviour**
Same configuration expressed as .xml and .yml produces different result

**How to reproduce**

Create 2 configuration files in clickhouse users.d directory with following content:

test1.xml:
```xml
<clickhouse>
  <users>
    <test1>
      <password>test1234</password>
      <grants>
        <query>GRANT INSERT ON system.numbers</query>
        <query>GRANT SELECT ON system.numbers</query>
      </grants>
    </test1>
  </users>
</clickhouse>
```
test2.yml:
```yml
users:
  test2:
    password: test1234
    grants:
      - query: GRANT INSERT ON system.numbers
      - query: GRANT SELECT ON system.numbers
```
Restart ClickHouse server to pick up changes

Run commands
* `SHOW GRANTS FOR test1,test2`

**Expected behavior**
Same permissions for both users

**Comment by DarkWanderer** [comment]
Correct syntax is:
```yml
users:
  test2:
    password: test1234
    grants:
      query:
        - GRANT INSERT ON system.numbers
        - GRANT SELECT ON system.numbers
```
