### ISSUE TITLE
MaterializedPostgreSQL table engine does not support schema specification

### ISSUE THREAD

**Issue by italodamato** [ClickHouse/ClickHouse#59950]
Reopening https://github.com/ClickHouse/ClickHouse/issues/29324 because non-default schema is not supported (or not documented) for MaterializedPostgreSQL table engine.

**How to reproduce**
* Create table using `MaterializedPostgreSQL Engine` and `SETTINGS materialized_postgresql_schema = 'MY_SCHEMA'`

**Expected behavior**
Create table successfully.

**Error message and/or stacktrace**
`Query 1 ERROR at Line 1: : DB::Exception: pqxx::undefined_table: ERROR:  relation "MY_TABLE" does not exist`

**Comment by jpchev** [comment]
hi there, I cannot reproduce the issue, I use:

postgresql 16.1,

the following version of ch

ClickHouse client version 24.8.4.13 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.8.4.

both in the following docker compose file

```
version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
```

the I run ```docker-compose up```
and in postgresql I run

```
psql -d my_database my_user
```

```
my_database=# alter role mfs with replication;
my_database=# create table x(a int);
my_database=# insert into x values(1);
my_database=# ALTER TABLE x ADD PRIMARY KEY (a);
```

then in ch

```
CREATE DATABASE postgres_db
ENGINE = MaterializedPostgreSQL('db:5432', 'my_database', 'my_user', 'my_password')
SETTINGS materialized_postgresql_schema = 'myschema';

use postgres_db;
```

and now I can see the replicated data (1 row) with

```
select * from x;
```

@kssenii can we close this issue?
