### ISSUE TITLE
MaterializedMySQL can't start with MySQL 8.3.0

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#60479]
MySQL 8.3.0

> log_bin_use_v1_row_events: Whether server is using version 1 binary log row events. Removed in MySQL 8.3.0.

so adding `--log-bin-use-v1-row-events=OFF` will not work

i created reproduced environments
https://gist.github.com/Slach/1db8f5ec1df586f5f6427b0188977fdd

**materialized_mysql.xml**
```
<clickhouse>
    <profiles><default><allow_experimental_database_materialized_mysql>1</allow_experimental_database_materialized_mysql></default></profiles>
</clickhouse>
```

**docker-compose.yaml**
```yaml
services:
  mysql:
    image: docker.io/mysql:${MYSQL_VERSION:-latest}
    command: --default-authentication-plugin=mysql_native_password --gtid_mode=on --enforce_gtid_consistency=ON
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin -p=root ping -h localhost
      timeout: 20s
      retries: 10
  clickhouse:
    image: docker.io/${CLICKHOUSE_IMAGE:-clickhouse/clickhouse-server}:${CLICKHOUSE_VERSION:-latest}
    links:
      - mysql
    healthcheck:
      test: clickhouse client -q "SELECT 1"
      interval: 10s
      timeout: 2s
      retries: 30
      start_period: 5s
    depends_on:
      mysql:
        condition: service_healthy
```

**reproduce.sh**
```
docker-compose pull
docker-compose down
docker-compose up -d clickhouse
docker-compose exec mysql mysql --user=root --password=qwerty -e "CREATE DATABASE mydb"
docker-compose exec clickhouse clickhouse-client -q "CREATE DATABASE mysql ENGINE = MaterializedMySQL('mysql:3306', 'mydb', 'root', 'qwerty') SETTINGS allows_query_when_mysql_lost=true, max_wait_time_when_mysql_unavailable=10000;"
```

Return error
```
Code: 695. DB::Exception: Received from localhost:9000. DB::Exception: Load job 'startup MaterializedMySQL database mysql' failed: Code: 537. DB::Exception: Illegal MySQL variables, the MaterializedMySQL engine requires log_bin_use_v1_row_events='OFF'. (ILLEGAL_MYSQL_VARIABLE),. (ASYNC_LOAD_FAILED)
(query: CREATE DATABASE mysql ENGINE = MaterializedMySQL('mysql:3306', 'mydb', 'root', 'qwerty') SETTINGS allows_query_when_mysql_lost=true, max_wait_time_when_mysql_unavailable=10000;)
```

reproduced on 23.3, 23.8, 24.1
