### ISSUE TITLE
clickhouse-keeper-client `reconfig add` - Coordination error: Bad arguments

### ISSUE THREAD

**Issue by odinsy** [ClickHouse/ClickHouse#60501]
**Describe the unexpected behaviour**
After enabling and using `reconfig` feature it's impossible to re-add Keeper instance with ID 0

**How to reproduce**
* ClickHouse Keeper 24.1.5.6
* Docker Image 24.1.5.6-alpine
```
clickhouse-keeper-client --history-file=/dev/null -h clickhouse-keeper -q "get /keeper/config"
server.0=clickhouse-keeper-0.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1
server.1=clickhouse-keeper-1.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1
server.2=clickhouse-keeper-2.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1

clickhouse-keeper-client --history-file=/dev/null -h clickhouse-keeper -q "reconfig remove 0"
server.1=clickhouse-keeper-1.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1
server.2=clickhouse-keeper-2.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1

clickhouse-keeper-client --history-file=/dev/null -h clickhouse-keeper -q "reconfig add 'server.0=clickhouse-keeper-0.clickhouse-keeper-hl.clickhouse.svc.cluster.local:9234;participant;1'"
Coordination error: Bad arguments
```

**Expected behavior**
Instance should be added

**Additional context**
- docker-compose.yaml
```
version: '3.8'
services:
  clickhouse-keeper-0:
    image: "clickhouse/clickhouse-keeper:24.1.5.6-alpine"
    user: "101:101"
    container_name: clickhouse-keeper-0
    hostname: clickhouse-keeper-0
    volumes:
     - ${PWD}/conf/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ${PWD}/conf/keeper_config_overrides.xml:/etc/clickhouse-keeper/keeper_config_overrides.xml
    ports:
        - "127.0.0.1:9181:9181"
    environment:
      - KEEPER_SERVER_ID=0
  clickhouse-keeper-1:
    image: "clickhouse/clickhouse-keeper:24.1.5.6-alpine"
    user: "101:101"
    container_name: clickhouse-keeper-1
    hostname: clickhouse-keeper-1
    volumes:
     - ${PWD}/conf/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ${PWD}/conf/keeper_config_overrides.xml:/etc/clickhouse-keeper/keeper_config_overrides.xml
    ports:
        - "127.0.0.1:9182:9181"
    environment:
      - KEEPER_SERVER_ID=1
  clickhouse-keeper-2:
    image: "clickhouse/clickhouse-keeper:24.1.5.6-alpine"
    user: "101:101"
    container_name: clickhouse-keeper-2
    hostname: clickhouse-keeper-2
    volumes:
     - ${PWD}/conf/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ${PWD}/conf/keeper_config_overrides.xml:/etc/clickhouse-keeper/keeper_config_overrides.xml
    ports:
        - "127.0.0.1:9183:9181"
    environment:
      - KEEPER_SERVER_ID=2
```
- conf/keeper_config.xml
```
<clickhouse>
    <include_from>/etc/clickhouse-keeper/keeper_config_overrides.xml</include_from>
    <listen_host>0.0.0.0</listen_host>

    <logger>
        <level>debug</level>
        <console>true</console>
    </logger>

    <keeper_server incl="keeper_server">
        <tcp_port>9181</tcp_port>
        <path>/var/lib/clickhouse-keeper</path>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <enable_reconfiguration>true</enable_reconfiguration>
        <four_letter_word_allow_list>*</four_letter_word_allow_list>

        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>warning</raft_logs_level>
        </coordination_settings>
    </keeper_server>

    <prometheus>
        <endpoint>/metrics</endpoint>
        <port>9363</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
        <status_info>false</status_info>
    </prometheus>
</clickhouse>
```
- conf/keeper_config_overrides.xml
```
<clickhouse>
    <keeper_server>
        <server_id from_env="KEEPER_SERVER_ID"></server_id>

        <raft_configuration>
            <server>
                <id>0</id>
                <hostname>clickhouse-keeper-0</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-1</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-2</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
- reproduce.sh
```
#!/usr/bin/env bash
set -e

docker compose -f docker-compose.yaml up -d
sleep 3
echo "### get /keeper/config ###"
docker exec -it clickhouse-keeper-2 clickhouse-keeper-client --history-file=/dev/null -q "get /keeper/config"
echo "### reconfig remove 0 ###"
docker exec -it clickhouse-keeper-2 clickhouse-keeper-client --history-file=/dev/null -q "reconfig remove 0"
echo "### reconfig add 'server.0=clickhouse-keeper-0:9234;participant;1 ###"
docker exec -it clickhouse-keeper-2 clickhouse-keeper-client --history-file=/dev/null -q "reconfig add 'server.0=clickhouse-keeper-0:9234;participant;1'"

docker compose -f docker-compose.yaml down
```

- gist for reproduce https://gist.github.com/odinsy/b3d2fb40b75c21cb0349268e784ebf89
