### ISSUE TITLE
why only one replica node in each shard have a high load？

### ISSUE THREAD

**Issue by fankuneee** [ClickHouse/ClickHouse#61716]
help！！
Why, when sending a select to a ClickHouse cluster with multiple replicas, does only one replica node in each shard have a high load, while the other replica nodes have a low load, causing the node with high load to be unavailable at times?

I have 8 ClickHouse nodes, 4 shards, and 2 replicas per shard. I'm using chproxy for load balancing across my cluster. However, the result is that in each shard, only one replica is overloaded while the other remains idle. Are there any configuration options or solutions to resolve this issue?

also the load_balancing option in my config.xml is round_robin,but it seems not working.

and I use Distributed Table Engine

clickhouse-server version:  v22.10.6.3-stable
chproxy： 1.20.1

**Comment by fankuneee** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/45652873/179f001f-1aa7-4b5c-969f-88f26e4a4e94)
hadoop2 with hadoop3 is a shard
hadoop4 with hadoop5 is a shard
hadoop6 with hadoop7 is a shard
hadoop8 with hadoop9 is a shard

the result looks like not normal
Here is the chproxy cluster config:
```
clusters:
  - name: xxxxxx
    scheme: "http"                                                  
    replicas:                                                       
      - name: "sipg_shard01"
        nodes: ["x.x.x.2:8123", "x.x.x.3:8123"]
      - name: "sipg_shard02"
        nodes: ["x.x.x.4:8123", "x.x.x.5:8123"]
      - name: "sipg_shard03"
        nodes: ["x.x.x.6:8123", "x.x.x.7:8123"]
      - name: "sipg_shard04"
        nodes: ["x.x.x.8:8123", "x.x.x.9:8123"]
    heartbeat:                                                      
      interval: 1m
      timeout: 10s
      request: "/?query=SELECT%201%2B1"
      response: "2\n"
```
is the problem with chproxy ?
