### ISSUE TITLE
Wrong response to `/js/uplot.js` and `/js/lz-string.js` while NGINX proxying

### ISSUE THREAD

**Issue by SoprachevAK** [ClickHouse/ClickHouse#61890]
**Wrong response to `/js/uplot.js` and `/js/lz-string.js` while NGINX proxying**

Static `/js/uplot.js` and `/js/lz-string.js` used by default dashboard on `/dashboard` url. When i send request it directly to CH all works fine, but when between client and CH exists fully proxing Nginx, Clickhouse successfully return wrong files. 

**Reproducing**
- `24.2.2.71` latest stable
- `24.2.1.2248`
- `head`

**Working correctly**
- `24.1.7.18`

Nginx and Clickhouse logs are empty (nothing unusual) 

Correct response body for `/js/lz-string.js`

```
var LZString=function(){ <...> LONG MINIFIED JS MODULE <...> }
```

Receiving after proxy:

```
var LZString=function(){ <...> LONG MINIFIED JS MODULE <...> }

HTTP/1.0 200 OK
Date: Mon, 25 Mar 2024 22:42:32 GMT
Connection: Close
Content-Type: text/html; charset=UTF-8
X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"9292"}

<!doctype html>
<html>
<head>
 <...> CONTENTS OF binary.html (ClickHouse Binary Viewer) <...>
</body>
</html>
```

**How to reproduce**
1. Create `docker-compose.yaml` config
``` yaml
# docker-compose.yaml
version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.2.2.71-alpine
    ports:
      - 8123:8123

  nginx:
    image: nginx:stable-alpine3.17
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9999:80
```
2. Create nginx config in same folder:
``` nginx
# nginx.conf
server {
  location / {
    proxy_pass http://clickhouse:8123;
  }

  listen 80;
}
```
3. `docker compose up`
4. `curl localhost:9999/js/lz-string.js` vs `curl localhost:8123/js/lz-string.js` returns different responses

**Additional context**

I think problem around this factory [src/Server/HTTPHandlerFactory.cpp#L254](https://github.com/ClickHouse/ClickHouse/blob/c7e4d97e5a1c5e58a0bd5a04e4aa5adce630d06b/src/Server/HTTPHandlerFactory.cpp#L254) which changed in #60389 and new handlers implementation. Also i don't found any places which can broken by proxy (like routing by browser agent)

Unfortunately i haven't time to build CH and try to fix it. 

_And last: Why you issues's template use **bold** for header instead header for header. Its looks ugly_
