### ISSUE TITLE
When sharding by dictionary value, data is not (re)distributed as intended

### ISSUE THREAD

**Issue by viapivov** [ClickHouse/ClickHouse#61970]
### Configurarion
I create two tables on clickhouse cluster (2 shards, 2 replicas):
1. `IndexDist` contains map `rowId` -> `fileId`
2. `DataByRowDist` contains map `rowId` -> `data`

To keep them consistent, I want to shard both tables by `fileId`. For this purpose I create dictionary `IndexDict` 

<details>
<summary>DDL</summary>

```sql

           CREATE TABLE IF NOT EXISTS IndexShard ON CLUSTER '{cluster}'
            (
                rowId UInt64,
                fileId UInt64
            )
            ENGINE = ReplicatedMergeTree('/clickhouse/{shard}/default/{table}', '{replica}')
            ORDER BY (fileId);

            CREATE TABLE IF NOT EXISTS IndexDist ON CLUSTER '{cluster}'
            AS IndexShard
                ENGINE = Distributed('{cluster}', 'default', IndexShard, fileId);

            CREATE DICTIONARY IF NOT EXISTS IndexDict ON CLUSTER '{cluster}'
            (
                rowId     UInt64,
                fileId UInt64xw
            )
            PRIMARY KEY rowId
            SOURCE(CLICKHOUSE(
                      db 'default'
                      table 'IndexDist'
                   invalidate_query 'select count() from IndexDist'
            )
            )
            LAYOUT(HASHED(PREALLOCATE 1))
            LIFETIME(5);

            CREATE TABLE IF NOT EXISTS DataByRowShard ON CLUSTER '{cluster}'
            (
                rowId              UInt64,
                item             String,
            )
                ENGINE = ReplicatedMergeTree('/clickhouse/{shard}/default/{table}', '{replica}')
                ORDER BY (rowId);

            CREATE TABLE IF NOT EXISTS DataByRowDist ON CLUSTER '{cluster}'
            AS DataByRowShard
                ENGINE = Distributed('{cluster}', 'default', DataByRowShard, dictGetUInt64('default.IndexDict', 'fileId', rowId));

```
</details>
<details>
<summary>Cluster config</summary>

```yml
services:
  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION}
    ports:
      - 2181
    hostname: zookeeper

  clickhouse-s1r1:
    image: ${CLICKHOUSE_IMAGE}
    hostname: clickhouse-s1r1
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./s1r1/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ./s1r1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./../../../../../log/clickhouse-s1r1-server:/var/log/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-s1r2:
    image: ${CLICKHOUSE_IMAGE}
    hostname: clickhouse-s1r2
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./s1r2/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ./s1r2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./../../../../../log/clickhouse-s1r2-server:/var/log/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-s2r1:
    image: ${CLICKHOUSE_IMAGE}
    hostname: clickhouse-s2r1
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./s2r1/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ./s2r1/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./../../../../../log/clickhouse-s2r1-server:/var/log/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-s2r2:
    image: ${CLICKHOUSE_IMAGE}
    hostname: clickhouse-s2r2
    ports:
      - 8123
      - 9000
      - 9100
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./s2r2/interserver_http_host.xml:/etc/clickhouse-server/config.d/interserver_http_host.xml
      - ./s2r2/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./../../../../../log/clickhouse-s2r2-server:/var/log/clickhouse-server
    depends_on:
      - zookeeper

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8123
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - clickhouse-s1r1
      - clickhouse-s1r2
      - clickhouse-s2r1
      - clickhouse-s2r2
```
</details>

I insert some data to the tables (via nginx:8123):

<details>
<summary> Insertion 1 </summary>

```sql
        INSERT INTO IndexDist(rowId, fileId) VALUES (1, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (2, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (3, 3);
        INSERT INTO IndexDist(rowId, fileId) VALUES (4, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (5, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (6, 3);
        INSERT INTO IndexDist(rowId, fileId) VALUES (7, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (8, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (9, 3);

        INSERT INTO DataByRowDist(rowId, item) VALUES (1, 'item1');
        INSERT INTO DataByRowDist(rowId, item) VALUES (2, 'item2');
        INSERT INTO DataByRowDist(rowId, item) VALUES (3, 'item3');
        INSERT INTO DataByRowDist(rowId, item) VALUES (4, 'item4');
        INSERT INTO DataByRowDist(rowId, item) VALUES (5, 'item5');
        INSERT INTO DataByRowDist(rowId, item) VALUES (6, 'item6');
        INSERT INTO DataByRowDist(rowId, item) VALUES (7, 'item7');
        INSERT INTO DataByRowDist(rowId, item) VALUES (8, 'item8');
        INSERT INTO DataByRowDist(rowId, item) VALUES (9, 'item9');

```
</details>

### What's wrong
I query the data periodically to make sure each `fileId` is contained in no more than one shard (also via nginx:8123):

<details>
<summary>Query</summary>

```sql
select fileId, _shard_num from DataByRowDist as D join IndexDict as I on D.rowId = I.rowId order by fileId
```
</details>

After 7 seconds, I see that the `fileId` becomes inconsistent with `_shard_num`.

A test that checks that no `fileId` is presented in more than one shard.  :
<img width="464" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/119407043/95a81c1d-1200-4c9b-9d4e-50727b341552">

### Mitigation

I found out that the data is sharded as intended if I reload the dictionary **twice** after inserting the data to the first table. I don't know how robust this solution is, but for this dataset the `fileId` stays in its own shard for 5 minutes.

<details>
<summary> Insertion 2 (that actually works ¯\_(ツ)_/¯) </summary>

```sql
        INSERT INTO IndexDist(rowId, fileId) VALUES (1, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (2, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (3, 3);
        INSERT INTO IndexDist(rowId, fileId) VALUES (4, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (5, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (6, 3);
        INSERT INTO IndexDist(rowId, fileId) VALUES (7, 1);
        INSERT INTO IndexDist(rowId, fileId) VALUES (8, 2);
        INSERT INTO IndexDist(rowId, fileId) VALUES (9, 3);

        --  It is crucial to have 2 reloads here. One reload doesn't work!
        SYSTEM RELOAD DICTIONARY IndexDict ON CLUSTER '{cluster}';
        SYSTEM RELOAD DICTIONARY IndexDict ON CLUSTER '{cluster}';

        INSERT INTO DataByRowDist(rowId, item) VALUES (1, 'item1');
        INSERT INTO DataByRowDist(rowId, item) VALUES (2, 'item2');
        INSERT INTO DataByRowDist(rowId, item) VALUES (3, 'item3');
        INSERT INTO DataByRowDist(rowId, item) VALUES (4, 'item4');
        INSERT INTO DataByRowDist(rowId, item) VALUES (5, 'item5');
        INSERT INTO DataByRowDist(rowId, item) VALUES (6, 'item6');
        INSERT INTO DataByRowDist(rowId, item) VALUES (7, 'item7');
        INSERT INTO DataByRowDist(rowId, item) VALUES (8, 'item8');
        INSERT INTO DataByRowDist(rowId, item) VALUES (9, 'item9');

```
</details>

**Does it reproduce on the most recent release?**

Haven't checked for 24.3 yet, but it is reproduced on 24.2, 24.1.6 and 24.1.8
