### ISSUE TITLE
clickhouse keeper DNS_ERROR Docker MacBook Pro

### ISSUE THREAD

**Issue by folt** [ClickHouse/ClickHouse#62022]
When starting a cluster with clickhouse keeper I get the following error:

```
Cannot print extra info for Poco::Exception (version 24.3.1.2672 (official build))
2024.03.28 07:26:29.614855 [ 1 ] {} <Warning> CloudPlacementInfo: Placement info has not been loaded
2024.03.28 07:26:37.626485 [ 1 ] {} <Warning> DNSResolver: Cannot resolve host (clickhouse-keeper-01), error 0: DNS error.
2024.03.28 07:26:37.627381 [ 1 ] {} <Error> bool DB::(anonymous namespace)::isLocalhost(const std::string &): Code: 198. DB::NetException: Not found address of host: clickhouse-keeper-01. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000000ecc0a8
1. DB::NetException::NetException<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x0000000000ebecd0
2. DB::(anonymous namespace)::resolveIPAddressImpl(String const&) (.llvm.8332504489153279672) @ 0x0000000000ebc4ec
3. DB::KeeperStateManager::parseServersConfiguration(Poco::Util::AbstractConfiguration const&, bool, bool) const @ 0x000000000090ffd4
4. DB::KeeperStateManager::KeeperStateManager(int, String const&, String const&, Poco::Util::AbstractConfiguration const&, std::shared_ptr<DB::KeeperContext>) @ 0x000000000091237c
5. DB::KeeperServer::KeeperServer(std::shared_ptr<DB::KeeperConfigurationAndSettings> const&, Poco::Util::AbstractConfiguration const&, ConcurrentBoundedQueue<DB::KeeperStorage::ResponseForSession>&, ConcurrentBoundedQueue<DB::CreateSnapshotTask>&, std::shared_ptr<DB::KeeperContext>, DB::KeeperSnapshotManagerS3&, std::function<void (unsigned long, DB::KeeperStorage::RequestForSession const&)>) @ 0x00000000008b8a14
6. DB::KeeperDispatcher::initialize(Poco::Util::AbstractConfiguration const&, bool, bool, std::shared_ptr<DB::Macros const> const&) @ 0x000000000089df40
7. DB::Context::initializeKeeperDispatcher(bool) const @ 0x0000000000af7efc
8. DB::Keeper::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000000c53ecc
9. Poco::Util::Application::run() @ 0x000000000107f4dc
10. DB::Keeper::run() @ 0x0000000000c51544
11. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000010887a4
12. mainEntryClickHouseKeeper(int, char**) @ 0x0000000000c50554
13. main @ 0x0000000000c60da0
14. ? @ 0x0000000000020e10
 (version 24.3.1.2672 (official build))

```

I use docker to run it.
Docker Desktop 4.28.0 (139021) for MacBook Pro

command run 

`docker compose up clickhouse-keeper-01 clickhouse-keeper-02 clickhouse-keeper-03 -d`

"com.clickhouse.build.version": "v24.3.1.2672-lts",

**The problems started after updating to 24.3.1. Previously, version 23.4 was used; on it, this setting does not cause any malfunctions.**

docker-compose.yml

```
version: "3.9"


x-common-keeper: &common-keeper
  image: "clickhouse/clickhouse-keeper:latest-alpine"
  networks:
    - "clickhouse-network"


services:

  clickhouse-keeper-01:
    <<: *common-keeper
    container_name: "clickhouse-keeper-01"
    hostname: "clickhouse-keeper-01"
    volumes:
     - "../config/clickhouse/clickhouse-keeper-01/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml"
     - "clickhouse-keeper-01-data:/var/log/clickhouse-keeper"
    ports:
        - "9181:9181"

  clickhouse-keeper-02:
    <<: *common-keeper
    container_name: "clickhouse-keeper-02"
    hostname: "clickhouse-keeper-02"
    volumes:
     - "../config/clickhouse/clickhouse-keeper-02/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml"
     - "clickhouse-keeper-02-data:/var/log/clickhouse-keeper"
    ports:
        - "9182:9181"

  clickhouse-keeper-03:
    <<: *common-keeper
    container_name: "clickhouse-keeper-03"
    hostname: "clickhouse-keeper-03"
    volumes:
     - "../config/clickhouse/clickhouse-keeper-03/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml"
     - "clickhouse-keeper-03-data:/var/log/clickhouse-keeper"
    ports:
        - "9183:9181"

networks:
  clickhouse-network:
    driver: "bridge"
    name: "clickhouse-network"

volumes:
  clickhouse-keeper-01-data:
  clickhouse-keeper-02-data:
  clickhouse-keeper-03-data:

```

clickhouse-keeper-01/keeper_config.xml

```
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>0.0.0.0</listen_host>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>1</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```

clickhouse-keeper-02/keeper_config.xml

```
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>0.0.0.0</listen_host>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>2</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```

clickhouse-keeper-03/keeper_config.xml

```
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>0.0.0.0</listen_host>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>3</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
