### ISSUE TITLE
Having trouble adding or changing Kafka topics.

### ISSUE THREAD

**Issue by joaozandonadatacosmos** [ClickHouse/ClickHouse#62308]
I have a ClickHouse cluster where I consume Kafka topics defined via YAML, with SSL certificates. It works perfectly, but whenever I need to modify a topic, ClickHouse only recognizes it after restarting the cluster nodes. I tried executing `SYSTEM RELOAD CONFIG` on the nodes but without success. Any tips on how to do this without needing to restart the nodes? 

example of my YAML configuration file
```yaml
kafka:
  kafka_topic:
    - name: topic1
      security_protocol: ssl
      enable_ssl_certificate_verification: false
      ssl_ca_location: /<location>/ca.pem
      ssl_key_location: /<location>/clickhouse-consumer_service.key
      ssl_certificate_location: /<location>/clickhouse-consumer_service.cert
    - name: topic2
      security_protocol: ssl
      enable_ssl_certificate_verification: false
      ssl_ca_location: /<location>/ca.pem
      ssl_key_location: /<location>/clickhouse-consumer_service.key
      ssl_certificate_location: /<location>/clickhouse-consumer_service.cert
```

ClickHouse server version: 23.7.2
Cluster size: 3 nodes
