### ISSUE TITLE
"Not found column [..] in block" with clusterAllReplicas

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#62682]
This doesn't work:
```
:) select serverUUID() as s, sum(dummy) from clusterAllReplicas(both, system.one) group by s

[...]
Received exception from server (version 24.4.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column serverUUID() in block. There are only columns: sum(__table1.dummy): While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK)
```

But this works:
```
:) select cityHash64(serverUUID()) + dummy as s, sum(dummy) from clusterAllReplicas(both, system.one) group by s

[...]
   ┌───────────────────s─┬─sum(dummy)─┐
1. │ 6220104575184213473 │          0 │
2. │ 7064952209212228648 │          0 │
   └─────────────────────┴────────────┘

2 rows in set. Elapsed: 0.006 sec. 
```

The cluster is just 2 servers running on localhost:
```
remote_servers:                                                                                                                                                                                                                        
  both:                                                                                                                                                                                                                                
    shard:                                                                                                                                                                                                                             
      replica:                                                                                                                                                                                                                         
        host: 127.0.0.1                                                                                                                                                                                                                
        port: 9000                                                                                                                                                                                                                     
      replica:                                                                                                                                                                                                                         
        host: 127.0.0.3                                                                                                                                                                                                                
        port: 9010                                                                                                                                                                                                                     
```
