### ISSUE TITLE
clickhouse-keeper cluster stops when a second node is started using docker containers

### ISSUE THREAD

**Issue by sdejong629** [ClickHouse/ClickHouse#62745]
When using the clickhouse-keeper docker container (version 24.3), when you use a custom value for the CLICKHOUSE_UID and CLICKHOUSE_GID, the raft configuration crashes when running any number of nodes bigger then 1.

When the default configuration is used, the container requires you to add USER ID en GROUP ID 101, which on ubuntu systems is reserved for the systemd-resolve user. So I assigned a custom value for CLICKHOUSE_UID and CLICKHOUSE_GID to allow local access to my filesystem.

If you use a custom UID/GID using the variables above, the error is as seen in de crash report below:

**Does it reproduce on the most recent release?**
Yes, version 24.3

**Enable crash reporting**
```
2024.04.18 07:31:54.339602 [ 1 ] {} <Error> Application: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/var/lib/clickhouse-keeper"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x00000000016f0d95
1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15000](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000000a0f901
2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15000]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x00000000016b88f7
3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<bool>::report(std::error_code const&) const (.llvm.5385572262389653489) @ 0x00000000016bbe76
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x00000000016bc673
5. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x00000000016bc715
6. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig&, String) @ 0x0000000000e7def5
7. DB::ConfigReloader::reloadIfNewer(bool, bool, bool, bool) @ 0x0000000000e91889
8. DB::ConfigReloader::ConfigReloader(std::basic_string_view<char, std::char_traits<char>>, std::vector<String, std::allocator<String>> const&, String const&, zkutil::ZooKeeperNodeCache&&, std::shared_ptr<Poco::Event> const&, std::function<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>, bool)>&&, bool) @ 0x0000000000e905ed
9. DB::Keeper::main(std::vector<String, std::allocator<String>> const&) @ 0x0000000000bff7a6
10. Poco::Util::Application::run() @ 0x00000000010c8ca6
11. DB::Keeper::run() @ 0x0000000000bfae9d
12. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000010d1e99
13. mainEntryClickHouseKeeper(int, char**) @ 0x0000000000bf9d38
14. main @ 0x0000000000c0c35d

Cannot print extra info for Poco::Exception (version 24.3.2.23 (official build))
```

**How to reproduce**
Run the clikchouse-keeper docker container on 2 different hosts with CLICKHOUSE_UID and CLICKHOUSE_GID set to 10001 for example with mounts to the local system.

* Which ClickHouse keeper version to use
24.4
* Which interface to use, if it matters
None, use logs
* Non-default settings, if any
Docker-compose
```yaml
---
version: "3.8"
services:
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:${CLICKHOUSE_KEEPER_VERSION:-latest-alpine}"
    container_name: ${CLICKHOUSE_KEEPER_NODE_NAME}
    user: "${CLICKHOUSE_UID}:${CLICKHOUSE_GID}"
    volumes:
      - ./config/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - /data/log/clickhouse-keeper:/var/log/clickhouse-keeper
      - /data/lib/clickhouse:/var/lib/clickhouse
    ports:
      - 9181:9181
      - 9234:9234
    environment:
      CLICKHOUSE_UID: ${CLICKHOUSE_UID}
      CLICKHOUSE_GID: ${CLICKHOUSE_GID}
```
**Expected behavior**

I expect the container to have the access to create the folders when needed when using a custom UID/GID. Preferably there should not even be a local user in the container, at least not at UID 101.

**Error message and/or stacktrace**

docker-compose logs
```
clickhouse-cluster-development-keeper-node-2  | Processing configuration file '/etc/clickhouse-keeper/keeper_config.xml'.
clickhouse-cluster-development-keeper-node-2  | Logging information to /var/log/clickhouse-keeper/clickhouse-keeper.log
clickhouse-cluster-development-keeper-node-2  | Logging errors to /var/log/clickhouse-keeper/clickhouse-keeper.err.log
clickhouse-cluster-development-keeper-node-2 exited with code 233
```

**Additional context**

Running the docker-compose example on 3 separate instances. I solved the current situation by pre-creating a local folder and mounting that volume to the container and setting the owner to my custom UID:GID
```
---
version: "3.8"
services:
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:${CLICKHOUSE_KEEPER_VERSION:-latest-alpine}"
    container_name: ${CLICKHOUSE_KEEPER_NODE_NAME}
    user: "${CLICKHOUSE_UID}:${CLICKHOUSE_GID}"
    volumes:
      - ./config/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - /data/log/clickhouse-keeper:/var/log/clickhouse-keeper
      - /data/lib/clickhouse:/var/lib/clickhouse
      - /data/lib/clickhouse-keeper:/var/lib/clickhouse-keeper
    ports:
      - 9181:9181
      - 9234:9234
    environment:
      CLICKHOUSE_UID: ${CLICKHOUSE_UID}
      CLICKHOUSE_GID: ${CLICKHOUSE_GID}
```
