### ISSUE TITLE
YML Input Format

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/ClickHouse#63547]
**Use case**

I recently came across a [metroline dataset](https://github.com/sergeypedan/moscow-metro) in .yml format and wondered if there would be any use for adding an input format:

```yml
-
  name: Академическая
  name_en: Akademicheskaya
  name_uniq: true
  line_uid: "6"
  latitude: 37.5733
  longitude: 55.6877
-
  name: Александровский сад
  name_en: Aleksandrovsky Sad
  name_uniq: true
  line_uid: "4"
  latitude: 37.6085
  longitude: 55.7525
-
  name: Алексеевская
  name_en: Alekseyevskaya
  name_uniq: true
  line_uid: "6"
  latitude: 37.639
  longitude: 55.8088
-

``` 

**Describe the solution you'd like**

Ability to do something like 
```
SELECT * FROM file('stations.yml', YML);
```
