### ISSUE TITLE
Clickhouse Server data is deleted when Kubernetes Cluster is restarted

### ISSUE THREAD

**Issue by chayandashora29** [ClickHouse/ClickHouse#65241]
I am creating a Clickhouse DB setup in Kubernetes cluster on Azure AKS.

**Describe the unexpected behaviour**
When the AKS cluster is restarted, all the data in the DB is wiped out. It is always refreshing the DB.

**How to reproduce**
* Use the latest Clickhouse Docker image
* Create a default Helm Chart and deploy it into the cluster using Helm install command
* Insert some data in the DB
* Stop the AKS cluster and start again
* Connect to the DB to retrieve the data.

**Expected behavior**
The data should remain in the persistant volume of the Kubernetes Statefulset

**Error message and/or stacktrace**
There is no error message, the data is getting wiped off.

**Comment by nikitamikhaylov** [comment]
It is obvious that `/var/lib/clickhouse` is not mounted to any persistent storage.

**Comment by chayandashora29** [comment]
This is the describe command output for the PV:
```
Name:            clickhouse-pv
Labels:          app.kubernetes.io/managed-by=Helm
Annotations:     meta.helm.sh/release-name: clickhouse
                 meta.helm.sh/release-namespace: default
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    
Status:          Bound
Claim:           default/clickhouse-pvc
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        1Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/clickhouse
    HostPathType:  
Events:            <none>

```
This is the describe output of the PVC:

```
Name:          clickhouse-pvc
Namespace:     default
StorageClass:  standard
Status:        Bound
Volume:        clickhouse-pv
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: clickhouse
               meta.helm.sh/release-namespace: default
               pv.kubernetes.io/bind-completed: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Events:        <none>
```
This is the volume and volume mount from the Pod:
```
     volumeMounts:                                                                                                                                                                                               
     - mountPath: /var/lib/clickhouse                                                                                                                                                                                   
       name: clickhouse-storage       

   volumes:                                                                                                                                                                                                      
   - name: clickhouse-storage                                                                                                                                                                                         
      persistentVolumeClaim:                                                                                                                                                                                             
             claimName: clickhouse-pvc     

```
