### ISSUE TITLE
CTE query may produce unexpected result.

### ISSUE THREAD

**Issue by r33s3n6** [ClickHouse/ClickHouse#65515]
**Describe what's wrong**
CTE query produces unexpected result.

**How to reproduce**

* Which ClickHouse server version to use: `24.5.3.5`
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: `distributed_product_mode='allow'`

* init database:
```sql
create database ch_main on cluster default;
use ch_main;

create table __t_hwi130st4 on cluster default ( 
  c_wpg Int32 ,
  c_s String ,
  c_i8 String ,
  c_seahk2u Float64 ,
  c_b Float64 ,
  c_w9_4ap Int32 primary key ,
  );

create table t_hwi130st4 on cluster default as __t_hwi130st4 ENGINE = Distributed(default, ch_main, __t_hwi130st4, c_w9_4ap);

alter table t_hwi130st4 on cluster default add column c_skwq8 String;

alter table __t_hwi130st4 on cluster default add column c_skwq8 String;

insert into t_hwi130st4 (c_wpg, c_s, c_i8, c_seahk2u, c_b, c_w9_4ap, c_skwq8) values 
  (-1641445293, 'v', 'wz', 1.55, 42.71, 1811182695, 'mzo35wgg3w'), 
  (1030097339, 'd', 'hl', 27.83, 255.7, 42, 'mz'), 
  (1, 'clbq1d5sc1', 'fqifv8lmmt', -2147483648.0, 21.52, -654940302, 'dvkoaf1n'), 
  (-388875437, 'mqxkt', 'z', -2147483649.5, 2.36, 32, 'wthlt');

create table __t_nh1w on cluster default ( 
  c_sfdzg Int32 ,
  c_xf Bool ,
  c_u3xs92nr4c String ,
  c_b_m Int32 primary key ,
  c_lgy Int32 ,
  );

create table t_nh1w on cluster default as __t_nh1w ENGINE = Distributed(default, ch_main, __t_nh1w, c_b_m);

insert into t_nh1w (c_sfdzg, c_xf, c_u3xs92nr4c, c_b_m, c_lgy) values 
  (251430331, coalesce((NOT NOT(cast( (1 != -39) as Nullable(Bool)))), true), 'go7h8', -30, 1940327806), 
  (1141805699, coalesce(false, true), 'v', -741275615, -88004190), 
  (734596759, coalesce((NOT NOT(cast( (-8445564921303969669 >= false) as Nullable(Bool)))), false), 'qqvalkv3u', -1865417109, -1009649105), 
  (65536, coalesce((false) 
    and ((NOT NOT(cast( (cast(null as Nullable(Decimal)) >= 318739973659284181) as Nullable(Bool))))), false), 'yc7e_3r50', -367254559, -999948046);

insert into t_nh1w (c_sfdzg, c_xf, c_u3xs92nr4c, c_b_m, c_lgy) values 
  (1365961365, coalesce(false, true), 'yk81vk2', -10, 6), 
  (-1947046247, coalesce((1109681293 is NULL), false), 'r7', -2112028332, -32345949), 
  (-1465074758, coalesce(true, true), 'f', 612512867, -944501406), 
  (801253351, coalesce((false) 
    or ((255 is NULL)), false), 'x_vx', 1891684388, 152498111);

insert into t_hwi130st4 (c_wpg, c_s, c_i8, c_seahk2u, c_b, c_w9_4ap, c_skwq8) values 
  (4096, '_', 'okduzszvk5', 99.60, 71.30, -1492433226, 'n83wjiu'), 
  (5, 'kw2krwo605', 'zlok', 64.73, -9223372036854775809.4, -37892574, 'w96307'), 
  (521992299, 'f', 'l', 54.87, 72.41, 100663045, 'or76bakt'), 
  (-31050596, 'wgtfbfq45', 'kihf_rnu7', 43.43, 59.94, 970950186, 'bz6yck_c');

insert into t_nh1w (c_sfdzg, c_xf, c_u3xs92nr4c, c_b_m, c_lgy) values 
  (-585916881, coalesce((NOT NOT(cast( (-6386902482911289510 >= -5757301626187127162) as Nullable(Bool)))), true), 'p30ev6x', -565153215, -1012338938), 
  (-897149309, coalesce((NOT NOT(cast( (-1296792187 >= -21651) as Nullable(Bool)))), true), 'rp2belxdc', 1462558685, 537511289), 
  (-1803345515, coalesce((NOT NOT(cast( (cast(null as Nullable(Decimal)) > -27567) as Nullable(Bool)))), true), 'h', 1026159363, 840036159), 
  (233184827, coalesce((NOT NOT(cast( ((((NOT NOT(cast( (1021136371 < -4) as Nullable(Bool))))) 
          or ((NOT NOT(cast( (1799203391 <= 34.28) as Nullable(Bool)))))) 
        or (true) = 64.17) as Nullable(Bool)))), true), 'hswe', -1226166248, -1622325493);
```

* Queries to run that lead to an unexpected result
```sql
WITH
cte_2 AS (
SELECT
  cast(subq_0.c3 as Nullable(String)) as c0,
  subq_0.c0 as c1
FROM
  (select  
    ref_9.c_xf as c0, 
    ref_9.c_u3xs92nr4c as c3
   from t_nh1w as ref_9
  ) as subq_0
ORDER BY
  1, 2
LIMIT 10
)
SELECT ref_20.c_s as c2
FROM t_hwi130st4 as ref_20
WHERE (ref_20.c_s in (select c0 from cte_2))
;
```
previous SQL produces:
```
mysql> WITH
    -> cte_2 AS (
    -> SELECT
    ->   cast(subq_0.c3 as Nullable(String)) as c0,
    ->   subq_0.c0 as c1
    -> FROM
    ->   (select  
    ->     ref_9.c_xf as c0, 
    ->     ref_9.c_u3xs92nr4c as c3
    ->    from t_nh1w as ref_9
    ->   ) as subq_0
    -> ORDER BY
    ->   1, 2
    -> LIMIT 10
    -> )
    -> SELECT ref_20.c_s as c2
    -> FROM t_hwi130st4 as ref_20
    -> WHERE (ref_20.c_s in (select c0 from cte_2))
    -> ;
+------+
| c2   |
+------+
| v    |
+------+
1 row in set (0.99 sec)
Read 32 rows, 508.00 B in 0.993427 sec., 32 rows/sec., 511.36 B/sec.
```
**However, the 'f' is missing in the result set**

**Expected behavior**

The 'f' appears in the CTE table:
```
mysql> SELECT
    ->   cast(subq_0.c3 as Nullable(String)) as c0,
    ->   subq_0.c0 as c1
    -> FROM
    ->   (select  
    ->     ref_9.c_xf as c0, 
    ->     ref_9.c_u3xs92nr4c as c3
    ->    from t_nh1w as ref_9
    ->   ) as subq_0
    -> ORDER BY
    ->   1, 2
    -> LIMIT 10;
+-----------+------+
| c0        | c1   |
+-----------+------+
| f         |    1 |
| go7h8     |    1 |
| h         |    1 |
| hswe      |    0 |
| p30ev6x   |    0 |
| qqvalkv3u |    0 |
| r7        |    0 |
| rp2belxdc |    0 |
| v         |    0 |
| x_vx      |    0 |
+-----------+------+
10 rows in set (1.97 sec)
Read 12 rows, 199.00 B in 1.965289 sec., 6 rows/sec., 101.26 B/sec.
```

And the 'f' exists in the table `t_hwi130st4`:
```
mysql> select 'f' in (
    ->   select ref_20.c_s as c2 
    ->   FROM t_hwi130st4 as ref_20);
+----------------------+
| in('f', _subquery_1) |
+----------------------+
|                    1 |
+----------------------+
1 row in set (2.80 sec)
Read 9 rows, 111.00 B in 2.803356 sec., 3 rows/sec., 39.60 B/sec.
```

Therefore, "f" should appear in the result set, but it is not.

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>::/0</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database logic error.
