### ISSUE TITLE
For writing to ClickHouse, is there a server-side solution for attaching the storage file after writing it? If so, is there a related k8s high availability solution?

### ISSUE THREAD

**Issue by Mrmanbanpai** [ClickHouse/ClickHouse#65966]
### Question

For my behavior of collecting traffic and storing it in the database, most of the time I need a high write volume and low latency. For the following reasons, I hope to use a hybrid mode to write to multiple points of the shard set, and achieve high availability through the replica set.

**Comment by ljluestc** [comment]
```

version: '3.8'

services:
  # Config Server Replica Set (3 nodes)
  config1:
    image: mongo:latest
    command: mongod --configsvr --replSet configReplSet --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - config1-data:/data/db

  config2:
    image: mongo:latest
    command: mongod --configsvr --replSet configReplSet --bind_ip_all
    ports:
      - "27020:27020"
    volumes:
      - config2-data:/data/db

  config3:
    image: mongo:latest
    command: mongod --configsvr --replSet configReplSet --bind_ip_all
    ports:
      - "27021:27021"
    volumes:
      - config3-data:/data/db

  # Shard 1 Replica Set (3 nodes)
  shard1-primary:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --bind_ip_all
    ports:
      - "27022:27017"
    volumes:
      - shard1-primary-data:/data/db

  shard1-secondary1:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --bind_ip_all
    ports:
      - "27023:27017"
    volumes:
      - shard1-secondary1-data:/data/db

  shard1-secondary2:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --bind_ip_all
    ports:
      - "27024:27017"
    volumes:
      - shard1-secondary2-data:/data/db

  # Shard 2 Replica Set (3 nodes)
  shard2-primary:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --bind_ip_all
    ports:
      - "27025:27017"
    volumes:
      - shard2-primary-data:/data/db

  shard2-secondary1:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --bind_ip_all
    ports:
      - "27026:27017"
    volumes:
      - shard2-secondary1-data:/data/db

  shard2-secondary2:
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --bind_ip_all
    ports:
      - "27027:27017"
    volumes:
      - shard2-secondary2-data:/data/db

  # Mongos Router
  mongos:
    image: mongo:latest
    command: mongos --configdb configReplSet/config1:27019,config2:27020,config3:27021 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - config1
      - config2
      - config3

volumes:
  config1-data:
  config2-data:
  config3-data:
  shard1-primary-data:
  shard1-secondary1-data:
  shard1-secondary2-data:
  shard2-primary-data:
  shard2-secondary1-data:
  shard2-secondary2-data:
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```
