### ISSUE TITLE
clickhouse in docker, raspberry

### ISSUE THREAD

**Issue by 1mfaasj** [ClickHouse/ClickHouse#66021]
### Question

Hi
I've got a question about clickhouse in docker. I have some trouble deploying it on a raspberry.
Do you maybe have the correct image/docker file for me? It feels like I'm missing something to get it running correctly.
the latest error is:

`2024-07-03T07:18:39.617459838Z /entrypoint.sh: line 41:    25 Illegal instruction     (core dumped) clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key='storage_configuration.disks.*.metadata_path'`

```
version: "3.3"
services:
  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.9.55
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  event-data:
    driver: local

```
