### ISSUE TITLE
`count` produces unexpected result

### ISSUE THREAD

**Issue by ycybfhb** [ClickHouse/ClickHouse#66121]
**Describe what's wrong**
`count` produces unexpected result.

**How to reproduce**

* Which ClickHouse server version to use: `24.5.3.5`
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: `distributed_product_mode='allow'`

* init database:
```sql
create database ch_main on cluster default;
use ch_main;
```
Then execute the SQL statements in `init.sql`.
[init.sql.txt](https://github.com/user-attachments/files/16108098/init.sql.txt)

* Queries to run that lead to an unexpected result
```sql
SELECT DISTINCT
  count(ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c0,
  ref_0.c_ylzjpt as c1
FROM
  t_vkx4cc as ref_0;
```

previous SQL produces:
```
mysql> SELECT DISTINCT
    ->   count(ref_0.c_zosphq2t1) over (partition by ref_0.c_hqfr9 order by ref_0.c_ylzjpt, ref_0.c_hqfr9, ref_0.c_zosphq2t1) as c0,
    ->   ref_0.c_ylzjpt as c1
    -> FROM
    ->   t_vkx4cc as ref_0;
+------+-------------+
| c0   | c1          |
+------+-------------+
|    1 | -1981899149 |
|    2 | -1650266905 |
|    3 | -1646738223 |
|    4 | -1618912877 |
|    5 | -1317193174 |
|    6 | -1219769753 |
|    7 | -1154269118 |
|    8 | -1150980622 |
|    9 | -1098155311 |
|   10 |  -841067875 |
|   11 |  -816935497 |
|   12 |  -599948807 |
|   13 |  -526570556 |
|   14 |  -504713125 |
|   15 |  -411038390 |
|   16 |  -331834394 |
|   17 |  -176934810 |
|   18 |          -2 |
|   19 |           6 |
|   20 |         255 |
|   21 |   406615258 |
|   22 |   541758331 |
|   23 |   897064234 |
|   24 |  1116921321 |
|   25 |  1207796283 |
|   26 |  1603772265 |
|   27 |  1664059402 |
|   28 |  1688303275 |
|   29 |  1913361922 |
|   30 |  1929066636 |
|   31 |  1968095908 |
|   32 |  2054878592 |
|   33 |  2125075305 |
|    1 |   720985423 |
|    2 |   745669725 |
|    1 | -2081147898 |
|    2 | -2051538534 |
|    3 | -1975508531 |
|    4 | -1700730666 |
|    5 | -1465484835 |
|    6 | -1458338029 |
|    7 | -1450619195 |
|    8 | -1365934326 |
|    9 | -1203382363 |
|   10 | -1197430632 |
|   11 | -1176267855 |
|   12 | -1020892864 |
|   13 |  -991301833 |
|   14 |  -685902265 |
|   15 |  -653505826 |
|   16 |  -451392958 |
|   17 |  -262516786 |
|   18 |  -222873194 |
|   19 |  -153185515 |
|   20 |   -74234560 |
|   21 |         -41 |
|   22 |          -6 |
|   23 |          -5 |
|   24 |          -3 |
|   25 |          15 |
|   26 |       65535 |
|   27 |    77089559 |
|   28 |   100663045 |
|   29 |   561061873 |
|   30 |   643897141 |
|   31 |   914629990 |
|   32 |  1159852204 |
|   33 |  1258218855 |
|   34 |  1459407556 |
|   35 |  1936334332 |
|   36 |  1962246186 |
|   37 |  2030467062 |
+------+-------------+
72 rows in set (0.01 sec)
Read 72 rows, 943.00 B in 0.007997 sec., 9003 rows/sec., 115.16 KiB/sec.

```

**Expected behavior**
In the returned rows, the content of the following rows is incorrect.
```
|    1 |   720985423 |
|    2 |   745669725 |
|   23 |   897064234 |
|   24 |  1116921321 |
|   25 |  1207796283 |
|   26 |  1603772265 |
|   27 |  1664059402 |
|   28 |  1688303275 |
|   29 |  1913361922 |
|   30 |  1929066636 |
|   31 |  1968095908 |
|   32 |  2054878592 |
|   33 |  2125075305 |
```
The correct rows shoule be:
```
|   23 |   720985423 |
|   24 |   745669725 |
|   25 |   897064234 |
|   26 |  1116921321 |
|   27 |  1207796283 |
|   28 |  1603772265 |
|   29 |  1664059402 |
|   30 |  1688303275 |
|   31 |  1913361922 |
|   32 |  1929066636 |
|   33 |  1968095908 |
|   34 |  2054878592 |
|   35 |  2125075305 |
```

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>
```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>10.0.0.1/8</ip>
                <ip>127.0.0.1/8</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```
keeper_config.xml:
```xml
<clickhouse replace="true">
    <logger>
        <level>information</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <listen_host>::</listen_host>
    <max_thread_pool_size>10000</max_thread_pool_size>
    <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>3</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>information</raft_logs_level>
        </coordination_settings>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>
```
#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database logic error.
