### ISSUE TITLE
Docker CH - RECURSIVE query doesn't work - UNKNOWN_TABLE

### ISSUE THREAD

**Issue by marcin-stanosek** [ClickHouse/ClickHouse#66381]
Clickhouse docker version:

```
24.4-alpine
24.5-alpine
24.6-alpine
```

Example from the documentation https://clickhouse.com/docs/en/sql-reference/statements/select/with

```
WITH RECURSIVE test_table AS (
    SELECT 1 AS number
UNION ALL
    SELECT number + 1 FROM test_table WHERE number < 100
)
SELECT sum(number) FROM test_table;
```

Result

```
Received exception from server (version 24.5.4):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table default.test_table does not exist. (UNKNOWN_TABLE)
```

Does anyone have any idea why this isn't working?

**Comment by max-vostrikov** [comment]
I've tried to reproduce it, but it works on fiddle:
https://fiddle.clickhouse.com/e8199dd8-b83e-4c58-9ce1-4e53d8e31001

I've also tried to reproduce it in a docker image `clickhouse/clickhouse-server:24.6-alpine` and 24.4-alpine, but the example query works as expected for me.

Can you provide some reproduction steps how we can reproduce this error on our side?

**Comment by marcin-stanosek** [comment]
My docker-compose.yml

```
services:

  .. some others services ...
  
  clickhouse:
    image: project/clickhouse
    build:
      context: ./docker/clickhouse
      target: project_clickhouse
      args:
        TIME_ZONE: ${CLICKHOUSE_SERVER_TIME_ZONE}
    env_file: '.env'
    environment:
      TZ: ${CLICKHOUSE_SERVER_TIME_ZONE}
      CLICKHOUSE_DB: ${TC2_CONFIG_CLICKHOUSE_DATABASE}
      CLICKHOUSE_USER: ${TC2_CONFIG_CLICKHOUSE_USERNAME}
      CLICKHOUSE_PASSWORD: ${TC2_CONFIG_CLICKHOUSE_PASSWORD}
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    networks:
      - projectNetwork

  .. some others services ...
```

My Dockerfile

```
ARG CLICKHOUSE_VER='24.5.3.5-alpine'

FROM clickhouse/clickhouse-server:${CLICKHOUSE_VER} AS project_clickhouse

ARG TIME_ZONE

RUN apk add --no-cache \
    envsubst \
    mysql-client \
    mariadb-connector-c

COPY config.sh /config.sh
RUN chmod +x /config.sh
RUN /config.sh --time-zone $TIME_ZONE
RUN rm /config.sh
```

config.sh file using in Dockerfile

```
#!/bin/bash

TIME_ZONE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --time-zone)
            TIME_ZONE="$2"
            shift 2
            ;;
    esac
done

CNF_FILE=/etc/clickhouse-server/config.d/override-server-config.xml
cat << EOF > $CNF_FILE
<clickhouse>
    <timezone replace="replace">${TIME_ZONE}</timezone>
</clickhouse>
EOF

CNF_FILE=/etc/clickhouse-server/users.d/override-default-user.xml
cat << EOF > $CNF_FILE
<clickhouse>
    <profiles>
        <default>
            <allow_experimental_analyzer>0</allow_experimental_analyzer>
        </default>
    </profiles>
    <users>
        <default>
            <profile>default</profile>
            <networks>
                <ip>127.0.0.1</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
        </default>
        <myuser>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </myuser>
    </users>
</clickhouse>
EOF
```

```
docker-compose build clickhouse
docker-compose up -d clickhouse
docker-compose exec clickhouse bash

clickhouse-client --user=myuser --password=mypassword
```
