### ISSUE TITLE
Mysql8.0 MaterializedMySQLSyncThread: Lost connection to MySQL

### ISSUE THREAD

**Issue by zhenglinsmile** [ClickHouse/ClickHouse#66814]
### server:  

```2024.07.20 23:23:28.053009 [ 6944082 ] {} <Information> MaterializedMySQLSyncThread: Lost connection to MySQL```

### client: 

```
CREATE DATABASE click_mysql
ENGINE = MaterializedMySQL('127.0.0.1:3306', 'click', 'clickhouse_user', 'ClickHouse_123')

Query id: 80298c1e-79c4-44ea-b73d-43d8160c623d

Ok.

0 rows in set. Elapsed: 0.045 sec. 

localhost :) select * from click_mysql.User;

SELECT *
FROM click_mysql.User

Query id: 4394edeb-18af-4207-bb89-bf242adfb3db

   ┌─id─┬─name─┬─age─┐
1. │  1 │ xs   │  12 │
2. │  2 │ xs1  │  21 │
   └────┴──────┴─────┘

2 rows in set. Elapsed: 0.005 sec. 

localhost :) select * from click_mysql.User;

SELECT *
FROM click_mysql.User

Query id: 58ce5144-4a88-40c0-8a00-af33541babc6


Elapsed: 0.003 sec. 

Received exception from server (version 24.7.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table click_mysql.user does not exist. Maybe you meant click_mysql.User?. (UNKNOWN_TABLE)
```

### docker compose:

  ```yaml
version: '3.0'

services:
  mysql:
    image: mysql:8.0.27
    container_name: click-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./datadir:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
  ```

### my.cnf:

    [mysqld]
    default-authentication-plugin=mysql_native_password
    log-bin=mysql-bin
    gtid_mode = ON
    enforce_gtid_consistency = ON
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql
    max_allowed_packet = 5M
    wait_timeout=28800
    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    socket=/var/run/mysqld/mysqld.sock    
    !includedir /etc/mysql/conf.d/

### init.sql:

```sql
sql
  CREATE USER clickhouse_user IDENTIFIED BY 'ClickHouse_123';
  GRANT ALL PRIVILEGES ON *.* TO 'clickhouse_user'@'%';
  FLUSH PRIVILEGES;
  create database click default character set utf8mb4 collate utf8mb4_unicode_ci;
  CREATE TABLE click.`User` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `age` int DEFAULT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
  INSERT INTO `click`.`User`(`id`, `name`, `age`) VALUES (1, 'xs', 12);
  INSERT INTO `click`.`User`(`id`, `name`, `age`) VALUES (2, 'xs1', 21);
```
