### ISSUE TITLE
24.4+ allows connection with bad CA chain

### ISSUE THREAD

**Issue by strtgbb** [ClickHouse/ClickHouse#67984]
**Describe what's wrong**

Starting in 24.4 an invalid ca chain is accepted.

**Does it reproduce on the most recent release?**
 yes

**How to reproduce**
I am running in docker-compose, here are my ssl configs:

/etc/clickhouse-server/config.d/ssl.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<clickhouse>
  <https_port>8443</https_port>
  <tcp_port_secure>9440</tcp_port_secure>
  <openSSL>
    <server>
      <certificateFile>/etc/clickhouse-server/certs/server.crt</certificateFile>
      <privateKeyFile>/etc/clickhouse-server/certs/server.key</privateKeyFile>
      <verificationMode>strict</verificationMode>
      <loadDefaultCAFile>false</loadDefaultCAFile>
      <preferServerCiphers>true</preferServerCiphers>
      <cacheSessions>true</cacheSessions>
      <caConfig>/ca_chain.crt</caConfig>
    </server>
  </openSSL>
</clickhouse>
```

/etc/clickhouse-client/config.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<config>
  <openSSL>
    <client>
      <certificateFile>/etc/clickhouse-server/certs/server.crt</certificateFile>
      <privateKeyFile>/etc/clickhouse-server/certs/server.key</privateKeyFile>
      <verificationMode>strict</verificationMode>
      <loadDefaultCAFile>false</loadDefaultCAFile>
      <preferServerCiphers>true</preferServerCiphers>
      <cacheSessions>true</cacheSessions>
      <caConfig>/ca_chain.crt</caConfig>
    </client>
  </openSSL>
</config>
```

On clickhouse1, `ca_chain.crt` is swapped for `missing_ca_chain.crt` (attached below)

Queries on 24.3 and before
```bash
docker-compose exec -it clickhouse2 clickhouse client --secure -h clickhouse1 -q "select 1"
Code: 210. DB::NetException: SSL Exception: error:10000418:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA, while reading from socket (172.19.0.2:9440): (clickhouse1:9440). (NETWORK_ERROR)

docker-compose exec -it clickhouse1 clickhouse client --secure -h clickhouse1 -q "select 1"
Code: 210. DB::NetException: SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (clickhouse1:9440). (NETWORK_ERROR)

docker-compose exec -it clickhouse2 clickhouse client --secure -h clickhouse2 -q "select 1"
1

docker-compose exec -it clickhouse1 clickhouse client --secure -h clickhouse2 -q "select 1"
Code: 210. DB::NetException: SSL Exception: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (clickhouse2:9440). (NETWORK_ERROR)
```

Queries on 24.4 and later
```bash
docker-compose exec -it clickhouse2 clickhouse client --secure -h clickhouse1 -q "select 1"
1

docker-compose exec -it clickhouse1 clickhouse client --secure -h clickhouse1 -q "select 1"
Code: 210. DB::NetException: SSL Exception: error:0A000086:SSL routines::certificate verify failed (clickhouse1:9440). (NETWORK_ERROR)

docker-compose exec -it clickhouse2 clickhouse client --secure -h clickhouse2 -q "select 1"
1

docker-compose exec -it clickhouse1 clickhouse client --secure -h clickhouse2 -q "select 1"
1
```

**Expected behavior**

Connections that fail on 24.3 and prior should still fail on 24.4 and later

**Additional context**
certificates involved:
[certificates.zip](https://github.com/user-attachments/files/16527464/certificates.zip)

**Comment by rschu1ze** [comment]
The invalid certificate chain was rejected for me, but maybe my setup is wrong.

The repro is slightly ambiguous. Could you please
- post what is in `<openSSL><server>[...]</server><openSSL>` on server1 (verbatim, please no placeholders like "server.key")
- post what is in `<openSSL><server>[...]</server><openSSL>` on server2 (verbatim, please no placeholders like "server.key")
- post what is in `<openSSL><client>[...]</client><openSSL>` on server1 (verbatim, please no placeholders like "server.key")
- post what is in `<openSSL><client>[...]</client><openSSL>` on server2 (verbatim, please no placeholders like "server.key")
- attach _all_ `.crt` and `.key` files, with unambiguous names that allow a mapping to the XML where they are referenced

?

**Comment by strtgbb** [comment]
My ssl configs are verbatim, I am performing the substitution with docker compose, I should have shared that config as well.

docker-compose.yml
```yml
version: '2.3'

services:
  clickhouse1: 
    image: clickhouse/clickhouse-server:24.6
    init: true
    ports:
      - "8123:8123"
      - "8443:8443"
      - "9440:9440"
      - "9000:9000"
      - "9019:9019"
      - "9100:9100"
    volumes:
      - "./config.d:/etc/clickhouse-server/config.d"
      - "./ssl_client.xml:/etc/clickhouse-client/config.xml"
      - "./missing-ca-chain-certs/clickhouse1.key:/etc/clickhouse-server/certs/server.key"
      - "./missing-ca-chain-certs/clickhouse1.crt:/etc/clickhouse-server/certs/server.crt"
      # - "./missing-ca-chain-certs/ca_chain.crt:/ca_chain.crt"
      - "./missing-ca-chain-certs/missing_ca_chain.crt:/ca_chain.crt"
      - "./logs/clickhouse1:/var/log/clickhouse-server"
      
  clickhouse2: 
    image: clickhouse/clickhouse-server:24.6
    init: true
    volumes:
      - "./config.d:/etc/clickhouse-server/config.d"
      - "./ssl_client.xml:/etc/clickhouse-client/config.xml"
      - "./missing-ca-chain-certs/clickhouse2.crt:/etc/clickhouse-server/certs/server.crt"
      - "./missing-ca-chain-certs/clickhouse2.key:/etc/clickhouse-server/certs/server.key"
      - "./missing-ca-chain-certs/ca_chain.crt:/ca_chain.crt"
      - "./logs/clickhouse2:/var/log/clickhouse-server"
```


Here is my entire environment, including key files that aren't directly used.
https://github.com/strtgbb/clickhouse-compose/tree/test-missing-ca
