### ISSUE TITLE
Support custom metrics collection without authentication

### ISSUE THREAD

**Issue by MikeAmputer** [ClickHouse/ClickHouse#67982]
Discussed in #54959

**Problem:**

Currently, a user account should be created and exposed for custom metrics collection through `http_handlers`.
This complicates Prometheus scraping because authentication and targets configurations are managed on different levels (which forces to create different scrape jobs for targets with different credentials):

```yaml
scrape_configs:
  - job_name: ch_custom_metrics
    scrape_interval: 30s
    metrics_path: '/my_metrics'
    static_configs:
      - targets:
        - '1-clickhouse:8123'
        - '2-clickhouse:8123'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'
```

Also, this behavior differs from built-in prometheus endpoint `/metrics`.

**Proposed Solutions:**

 - Introduce a new handler type, `metrics`, similar to `predefined_query_handler`, but without requiring authentication.
 - Alternatively, a new parameter such as `<require_auth>false</require_auth>` could be added to http handler rules.
 - Or, add predefined custom query execution option to [prometheus configuration section](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#prometheus)
