### ISSUE TITLE
Will Updating the ClickHouse Server Image to 24.8 version in an EKS Cluster Cause Data Loss?

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#68722]
### Company or project name

clickhouse cluster in aws eks

### Question

Let assume I have a clickhouse cluster with 3 shards and 2 replicas in my eks cluster with this image clickhouse/clickhouse-server:23.7. I want to update the clickhouse server image to the latest image version(clickhouse/clickhouse-server:24.8). If I directly edit the image in podtemplate and deployed the clickhouse with updated image(clickhouse/clickhouse-server:24.8), will cause any data loss in exisiting tablesbecause of image changes?

My existing Clickhouse config:
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  defaults:
    replicasUseFQDN: "no"
    distributedDDL:
      profile: admin_profile
    templates:
      podTemplate: clickhouse-pod
      dataVolumeClaimTemplate: clickhouse-storage
      serviceTemplate: clickhouse-svc
  configuration:
    users:
      default/networks/host_regexp: clickhouse.svc.cluster.local$
      default/networks/ip:
        - 127.0.0.1
        - 0.0.0.0
      admin/networks/host_regexp: clickhouse.svc.cluster.local$
      admin/networks/ip:
        - 127.0.0.1
        - 0.0.0.0
      admin/k8s_secret_password: clickhouse/clickhouse-operator-altinity-clickhouse-operator/password
      admin/access_management: 1
      admin/named_collection_control: 1
      admin/show_named_collections: 1
      admin/show_named_collections_secrets: 1
      admin/profile: admin_profile
      admin/quote: admin_quote
    profiles:
      admin_profile/max_memory_usage: 600000000000
      admin_profile/readonly: 0
      admin_profile/max_insert_threads: 32
    quotas:
      admin_quota/interval/duration: 3600
      admin_quota/interval/queries: 0
      admin_quota/interval/errors: 0
      admin_quota/interval/result_rows: 0
      admin_quota/interval/read_rows: 0
      admin_quota/interval/execution_time: 0
    settings:
      disable_internal_dns_cache: 1
    files:
      conf.d/chop-generated-storage.xml: |
        <yandex>
            <storage_configuration>
                <disks>
                    <default>
                        <metadata_path>/var/lib/clickhouse/</metadata_path>
                    </default>
                    <fast_ssd>
                        <path>/mnt/fast_ssd/clickhouse/</path>
                    </fast_ssd>
                    <s3>
                        <type>s3</type>
                        <endpoint>S3 URL</endpoint>
                        <use_environment_credentials>true</use_environment_credentials>
                        <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path>
                    </s3>
                </disks>
                <policies>
                    <moving_from_hot_to_cold>
                        <volumes>
                            <default>
                                <disk>default</disk>
                            </default>
                            <hot>
                                <disk>fast_ssd</disk>
                            </hot>
                            <cold>
                                <disk>s3</disk>
                            </cold>
                        </volumes>
                    </moving_from_hot_to_cold>
            	</policies>
            </storage_configuration>
        </yandex>
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo-keeper
          port: 2181
        - host: zookeeper-1.zookeepers.zoo-keeper
          port: 2181
        - host: zookeeper-2.zookeepers.zoo-keeper
          port: 2181
    clusters:
      - name: prod-cluster
        templates:
          podTemplate: clickhouse-pod
          dataVolumeClaimTemplate: clickhouse-storage
        layout:
          shardsCount: 3
          replicasCount: 2
          shards:
            - name: shard0
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
            - name: shard1
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
            - name: shard2
              internalReplication: "true"
              templates:
                podTemplate: clickhouse-pod
                dataVolumeClaimTemplate: clickhouse-storage
  templates:
    serviceTemplates:
      - name: clickhouse-svc
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          externalTrafficPolicy: Cluster
          type: LoadBalancer
    podTemplates:
      - name: clickhouse-pod
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.7
              resources:
                limits:
                  cpu: "3"
                  memory: 8Gi
                requests:
                  cpu: "2"
                  memory: 6Gi
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
```

My updated clickhouse config : 
```
    podTemplates:
      - name: clickhouse-pod
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:24.8
```
