### ISSUE TITLE
Clickhouse with Kafka Locally Cannot  read Json Data 

### ISSUE THREAD

**Issue by soumilshah1995** [ClickHouse/ClickHouse#69681]
I am trying out Clickhouse with Kafka locally 

```
version: '3'
services:

  fast-data-dev:
    image: dougdonohoe/fast-data-dev
    ports:
      - "3181:3181"
      - "3040:3040"
      - "7081:7081"
      - "7082:7082"
      - "7083:7083"
      - "7092:7092"
      - "8081:8081"
    environment:
      - ZK_PORT=3181
      - WEB_PORT=3040
      - REGISTRY_PORT=8081
      - REST_PORT=7082
      - CONNECT_PORT=7083
      - BROKER_PORT=7092
      - ADV_HOST=127.0.0.1
    networks:
      - app-network

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    depends_on:
      - fast-data-dev
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
#      - ./config.xml:/etc/clickhouse-server/config.xml
#      - ./users.xml:/etc/clickhouse-server/users.xml
    ports:
      - "9000:9000"    # ClickHouse native client port
      - "8123:8123"    # ClickHouse HTTP interface port
      - "9440:9440"    # ClickHouse secure TCP port (optional)
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


```

# Publish messages 
```
try:
    from kafka import KafkaProducer
    from faker import Faker
    import json
    from time import sleep
    import random
    import uuid
    from datetime import datetime
    print("All modules loaded ")
except Exception as e:
    print("error modules ", e)

producer = KafkaProducer(bootstrap_servers='localhost:7092')
_instance = Faker()

global faker
faker = Faker()


class DataGenerator(object):
    @staticmethod
    def get_customer_data():
        customer_data = {
            "customer_id": str(uuid.uuid4()),
            "name": faker.name(),
            "state": faker.state(),
            "city": faker.city(),
            "email": faker.email(),
            "created_at": datetime.now().isoformat().__str__(),
            "ts": str(datetime.now().timestamp()),
        }
        return customer_data

    @staticmethod
    def get_orders_data(customer_id):
        order_data = {
            "order_id": str(uuid.uuid4()),
            "name": faker.text(max_nb_chars=20),
            "order_value": str(random.randint(10, 1000)),
            "priority": random.choice(["LOW", "MEDIUM", "HIGH"]),
            "order_date": faker.date_between(start_date='-30d', end_date='today').strftime('%Y-%m-%d'),
            "customer_id": customer_id,
            "ts": str(datetime.now().timestamp()),
        }
        return order_data


for _ in range(20):
    # Generate and send customer data
    customer_data = DataGenerator.get_customer_data()
    customer_payload = json.dumps(customer_data).encode("utf-8")
    producer.send('customers_new', customer_payload)
    print("Customer Payload:", customer_payload)
    sleep(1)

    # # Generate and send order data for each customer
    # for i in range(3):  # Adjust the number of orders per customer as needed
    #     order_data = DataGenerator.get_orders_data(customer_data["customer_id"])
    #     order_payload = json.dumps(order_data).encode("utf-8")
    #     producer.send('orders', order_payload)
    #     print("Order Payload:", order_payload)
    #     sleep(1)
```

![image](https://github.com/user-attachments/assets/03e27ad4-6109-4d90-9343-27862b9c6df6)

# Query 
```
docker exec -it clickhouse-server clickhouse-client



CREATE TABLE customers_queue
(
    customer_id String,
    name String,
    state String,
    city String,
    email String,
    created_at String,
    ts String
) ENGINE = Kafka(
    'fast-data-dev:7092',
    'customers_new',
    'clickhouse_customers_group',
    'JSONEachRow'
)


SELECT *
FROM customers_queue
LIMIT 20
FORMAT Vertical
SETTINGS stream_like_engine_allow_direct_select = 1;
```
I don't see data in Clickhouse 
Query id: 3098daed-c274-412b-b493-46fd7e62ebb9

Ok.

0 rows in set. Elapsed: 15.058 sec. 

e00bd8b446b0 :)
