### ISSUE TITLE
Insertion into distributed table causes null pointer dereference

### ISSUE THREAD

**Issue by r33s3n6** [ClickHouse/ClickHouse#69839]
**Describe what's wrong**
Insertion into distributed table causes Segmentation fault

**How to reproduce**

* Which ClickHouse server version to use: `24.9.1.1(master)` 
* Which interface to use, if it matters: `MySQL Shell`
* Non-default settings, if any: 
```xml
            <distributed_product_mode>allow</distributed_product_mode>
            <allow_experimental_parallel_reading_from_replicas>1</allow_experimental_parallel_reading_from_replicas>
            <allow_experimental_inverted_index>1</allow_experimental_inverted_index>
            <allow_experimental_full_text_index>1</allow_experimental_full_text_index>
            <allow_experimental_join_condition>1</allow_experimental_join_condition>
            <allow_experimental_query_deduplication>1</allow_experimental_query_deduplication>
```

* init database:
```sql
create database ch_main on cluster default;
use ch_main;

create table __t_xl_fnvymkf on cluster default ( 
  c_nub94w6u9w Int32 not null primary key ,
  c_jw7hcyn String ,
  c_brqj String ,
  );
create table t_xl_fnvymkf on cluster default as __t_xl_fnvymkf ENGINE = Distributed(default, ch_main, __t_xl_fnvymkf, c_nub94w6u9w);
alter table t_xl_fnvymkf on cluster default add column c_ytwx1 String;

```

* Queries to run that lead to an unexpected result
```sql
insert into t_xl_fnvymkf (c_nub94w6u9w, c_jw7hcyn, c_brqj, c_ytwx1) values 
(615861137, 'fh', coalesce(case when (-944061992 between bitAnd(
      855604989, 
      502112092) and byteSwap(
      -1)) then 'edicnr' else left(
    'w9jcahwi', 
    -12649) end
  , 'q'), coalesce(case when (cast((cast(null as Nullable(Decimal)) >= (-1718188560 is NULL)) as Nullable(Bool))) then 'kgxz4v8pn' else left(
    'tep', 
    17323) end
  , 'mz3y'));
```

clickhouse log:
```
2024.09.21 09:20:59.995377 [ 728 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
2024.09.21 09:20:59.995660 [ 728 ] {} <Fatal> BaseDaemon: Changed settings: use_uncompressed_cache = false, load_balancing = 'in_order', log_queries = true, distributed_product_mode = 'allow', prefer_column_name_to_alias = true, max_memory_usage = 20000000000, allow_experimental_parallel_reading_from_replicas = 1, allow_experimental_inverted_index = true, allow_experimental_full_text_index = true, allow_experimental_join_condition = true, allow_experimental_query_deduplication = true, SQL_AUTO_IS_NULL = 0
2024.09.21 09:20:59.997386 [ 710 ] {} <Debug> SystemLog (system.crash_log): Will use existing table system.crash_log for CrashLog
2024.09.21 09:21:00.120355 [ 617 ] {ba127fdf-c689-4323-b55d-1348fcc7e64b::202409_1_206_41} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 1614 rows, containing 1021 columns (1021 merged, 0 gathered) in 0.72681494 sec., 2220.647803414718 rows/sec., 2.24 MiB/sec.
2024.09.21 09:21:00.243042 [ 617 ] {} <Debug> MemoryTracker: Peak memory usage background process to apply mutate/merge in table: 39.17 MiB.
2024.09.21 09:21:02.299599 [ 650 ] {} <Debug> system.asynchronous_metric_log (9e545725-586c-4a40-8370-840789b05a08): Removing 1 parts from filesystem (serially): Parts: [202409_177_177_0]
2024.09.21 09:21:02.300475 [ 650 ] {} <Debug> system.asynchronous_metric_log (9e545725-586c-4a40-8370-840789b05a08): Removing 1 parts from memory: Parts: [202409_177_177_0]
2024.09.21 09:21:03.501486 [ 729 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.09.21 09:21:03.501598 [ 729 ] {} <Fatal> BaseDaemon: (version 24.9.1.1, build id: C7425E0147740F55AC78B65BDBF9A1A2C42554A5, git hash: f7ca119b397c533f521fa2b20a9112b0a8944afb, architecture: x86_64) (from thread 40) Received signal 11
2024.09.21 09:21:03.501655 [ 729 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.09.21 09:21:03.501704 [ 729 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.09.21 09:21:03.501754 [ 729 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005603a5f49d2d 0x00005603a64def74 0x00007ff02306c090 0x00007ff02304b942 0x00005603a5ee626b 0x00005603a5ee7d31 0x0000560396132045 0x000056039616ac8e 0x00005603b6fac24d 0x00005603b6fb462c 0x00005603b6fa1f14 0x00005603b6f9e8dd 0x00005603b6f9c671 0x00005603b6db7726 0x00005603b6d64b78 0x00005603b6d64001 0x00005603b6d9fdce 0x00005603b6d84f31 0x00005603b6d8387c 0x00005603b6d83362 0x00005603b6d8071f 0x00005603b3a62c47 0x00005603b6b9538a 0x00005603b6b8c91d 0x00005603b800252f 0x00005603b8003117 0x00005603b7f1624b 0x00005603b7f103a8 0x00005603960e7059 0x00007ff022eb5609 0x00007ff023148353
2024.09.21 09:21:03.501794 [ 729 ] {} <Fatal> BaseDaemon: ########################################
2024.09.21 09:21:03.501861 [ 729 ] {} <Fatal> BaseDaemon: (version 24.9.1.1, build id: C7425E0147740F55AC78B65BDBF9A1A2C42554A5, git hash: f7ca119b397c533f521fa2b20a9112b0a8944afb) (from thread 40) (query_id: mysql:11:27963b05-bff0-4312-8fe4-be8492a81ded) (query: insert into t_xl_fnvymkf (c_nub94w6u9w, c_jw7hcyn, c_brqj, c_ytwx1) values 
) Received signal Segmentation fault (11)
2024.09.21 09:21:03.501919 [ 729 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.09.21 09:21:03.501954 [ 729 ] {} <Fatal> BaseDaemon: Stack trace: 0x00005603a5f49d2d 0x00005603a64def74 0x00007ff02306c090 0x00007ff02304b942 0x00005603a5ee626b 0x00005603a5ee7d31 0x0000560396132045 0x000056039616ac8e 0x00005603b6fac24d 0x00005603b6fb462c 0x00005603b6fa1f14 0x00005603b6f9e8dd 0x00005603b6f9c671 0x00005603b6db7726 0x00005603b6d64b78 0x00005603b6d64001 0x00005603b6d9fdce 0x00005603b6d84f31 0x00005603b6d8387c 0x00005603b6d83362 0x00005603b6d8071f 0x00005603b3a62c47 0x00005603b6b9538a 0x00005603b6b8c91d 0x00005603b800252f 0x00005603b8003117 0x00005603b7f1624b 0x00005603b7f103a8 0x00005603960e7059 0x00007ff022eb5609 0x00007ff023148353
2024.09.21 09:21:03.539053 [ 729 ] {} <Fatal> BaseDaemon: 0.0. inlined from ./build/./src/Common/StackTrace.cpp:380: StackTrace::tryCapture()
2024.09.21 09:21:03.539118 [ 729 ] {} <Fatal> BaseDaemon: 0. ./build/./src/Common/StackTrace.cpp:349: StackTrace::StackTrace(ucontext_t const&) @ 0x00000000152fbd2d
2024.09.21 09:21:03.581281 [ 729 ] {} <Fatal> BaseDaemon: 1. ./build/./src/Common/SignalHandlers.cpp:85: signalHandler(int, siginfo_t*, void*) @ 0x0000000015890f74
2024.09.21 09:21:03.581334 [ 729 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007ff02306c090
2024.09.21 09:21:03.581367 [ 729 ] {} <Fatal> BaseDaemon: 3. ? @ 0x00007ff02304b942
2024.09.21 09:21:03.653695 [ 729 ] {} <Fatal> BaseDaemon: 4. ./build/./src/Common/Exception.cpp:48: DB::abortOnFailedAssertion(String const&, void* const*, unsigned long, unsigned long) @ 0x000000001529826b
2024.09.21 09:21:03.719049 [ 729 ] {} <Fatal> BaseDaemon: 5.0. inlined from ./build/./src/Common/Exception.cpp:71: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
2024.09.21 09:21:03.719135 [ 729 ] {} <Fatal> BaseDaemon: 5. ./build/./src/Common/Exception.cpp:115: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000015299d31
2024.09.21 09:21:03.736717 [ 729 ] {} <Fatal> BaseDaemon: 6. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000054e4045
2024.09.21 09:21:03.754513 [ 729 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000551cc8e
2024.09.21 09:21:03.841439 [ 729 ] {} <Fatal> BaseDaemon: 8. ./build/./src/Processors/Formats/Impl/ConstantExpressionTemplate.cpp:335: DB::ConstantExpressionTemplate::TemplateStructure::TemplateStructure(std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator, DB::TokenIterator, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool, std::shared_ptr<DB::Context const>) @ 0x000000002635e24d
2024.09.21 09:21:03.941715 [ 729 ] {} <Fatal> BaseDaemon: 9.0. inlined from ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:35: DB::ConstantExpressionTemplate::TemplateStructure* std::construct_at[abi:v15007]<DB::ConstantExpressionTemplate::TemplateStructure, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&, DB::ConstantExpressionTemplate::TemplateStructure*>(DB::ConstantExpressionTemplate::TemplateStructure*, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&)
2024.09.21 09:21:03.941828 [ 729 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:298: void std::allocator_traits<std::allocator<DB::ConstantExpressionTemplate::TemplateStructure>>::construct[abi:v15007]<DB::ConstantExpressionTemplate::TemplateStructure, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&, void, void>(std::allocator<DB::ConstantExpressionTemplate::TemplateStructure>&, DB::ConstantExpressionTemplate::TemplateStructure*, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&)
2024.09.21 09:21:03.941883 [ 729 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:292: __shared_ptr_emplace<std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo> > &, DB::TokenIterator &, DB::TokenIterator &, std::shared_ptr<DB::IAST> &, const DB::IDataType &, bool &, std::shared_ptr<const DB::Context> &>
2024.09.21 09:21:03.941945 [ 729 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:953: std::shared_ptr<DB::ConstantExpressionTemplate::TemplateStructure> std::allocate_shared[abi:v15007]<DB::ConstantExpressionTemplate::TemplateStructure, std::allocator<DB::ConstantExpressionTemplate::TemplateStructure>, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&, void>(std::allocator<DB::ConstantExpressionTemplate::TemplateStructure> const&, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&)
2024.09.21 09:21:03.942002 [ 729 ] {} <Fatal> BaseDaemon: 9.4. inlined from ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:962: std::shared_ptr<DB::ConstantExpressionTemplate::TemplateStructure> std::make_shared[abi:v15007]<DB::ConstantExpressionTemplate::TemplateStructure, std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&, void>(std::vector<DB::LiteralInfo, std::allocator<DB::LiteralInfo>>&, DB::TokenIterator&, DB::TokenIterator&, std::shared_ptr<DB::IAST>&, DB::IDataType const&, bool&, std::shared_ptr<DB::Context const>&)
2024.09.21 09:21:03.942046 [ 729 ] {} <Fatal> BaseDaemon: 9. ./build/./src/Processors/Formats/Impl/ConstantExpressionTemplate.cpp:445: DB::ConstantExpressionTemplate::Cache::getFromCacheOrConstruct(std::shared_ptr<DB::IDataType const> const&, bool, DB::TokenIterator, DB::TokenIterator, std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, bool*, String const&) @ 0x000000002636662c
2024.09.21 09:21:04.026406 [ 729 ] {} <Fatal> BaseDaemon: 10. ./build/./src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:495: DB::ValuesBlockInputFormat::parseExpression(DB::IColumn&, unsigned long) @ 0x0000000026353f14
2024.09.21 09:21:04.040258 [ 648 ] {} <Debug> system.processors_profile_log (acedf2d4-c2d1-4ab0-b3c0-951a4e921961): Removing 1 parts from filesystem (serially): Parts: [202409_39_39_0]
2024.09.21 09:21:04.041000 [ 648 ] {} <Debug> system.processors_profile_log (acedf2d4-c2d1-4ab0-b3c0-951a4e921961): Removing 1 parts from memory: Parts: [202409_39_39_0]
2024.09.21 09:21:04.102645 [ 729 ] {} <Fatal> BaseDaemon: 11.0. inlined from ./build/./src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:328: DB::ValuesBlockInputFormat::tryReadValue(DB::IColumn&, unsigned long)
2024.09.21 09:21:04.102741 [ 729 ] {} <Fatal> BaseDaemon: 11. ./build/./src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:237: DB::ValuesBlockInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, unsigned long) @ 0x00000000263508dd
2024.09.21 09:21:04.179535 [ 729 ] {} <Fatal> BaseDaemon: 12. ./build/./src/Processors/Formats/Impl/ValuesBlockInputFormat.cpp:128: DB::ValuesBlockInputFormat::read() @ 0x000000002634e671
2024.09.21 09:21:04.212978 [ 729 ] {} <Fatal> BaseDaemon: 13. ./build/./src/Processors/Formats/IInputFormat.cpp:19: DB::IInputFormat::generate() @ 0x0000000026169726
2024.09.21 09:21:04.244041 [ 729 ] {} <Fatal> BaseDaemon: 14. ./build/./src/Processors/ISource.cpp:139: DB::ISource::tryGenerate() @ 0x0000000026116b78
2024.09.21 09:21:04.273833 [ 729 ] {} <Fatal> BaseDaemon: 15. ./build/./src/Processors/ISource.cpp:108: DB::ISource::work() @ 0x0000000026116001
2024.09.21 09:21:04.286957 [ 729 ] {} <Fatal> BaseDaemon: 16.0. inlined from ./build/./src/Processors/Executors/ExecutionThreadContext.cpp:47: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2024.09.21 09:21:04.287018 [ 729 ] {} <Fatal> BaseDaemon: 16. ./build/./src/Processors/Executors/ExecutionThreadContext.cpp:96: DB::ExecutionThreadContext::executeTask() @ 0x0000000026151dce
2024.09.21 09:21:04.327282 [ 729 ] {} <Fatal> BaseDaemon: 17. ./build/./src/Processors/Executors/PipelineExecutor.cpp:288: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000026136f31
2024.09.21 09:21:04.378625 [ 729 ] {} <Fatal> BaseDaemon: 18.0. inlined from ./build/./src/Processors/Executors/PipelineExecutor.cpp:254: DB::PipelineExecutor::executeSingleThread(unsigned long)
2024.09.21 09:21:04.378697 [ 729 ] {} <Fatal> BaseDaemon: 18. ./build/./src/Processors/Executors/PipelineExecutor.cpp:429: DB::PipelineExecutor::executeImpl(unsigned long, bool) @ 0x000000002613587c
2024.09.21 09:21:04.419744 [ 729 ] {} <Fatal> BaseDaemon: 19. ./build/./src/Processors/Executors/PipelineExecutor.cpp:125: DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000026135362
2024.09.21 09:21:04.432397 [ 729 ] {} <Fatal> BaseDaemon: 20. ./build/./src/Processors/Executors/CompletedPipelineExecutor.cpp:112: DB::CompletedPipelineExecutor::execute() @ 0x000000002613271f
2024.09.21 09:21:04.588723 [ 648 ] {} <Debug> system.query_log (3a40562a-eb15-4055-8ece-969661d81390): Removing 1 parts from filesystem (serially): Parts: [202409_41_41_0]
2024.09.21 09:21:04.589710 [ 648 ] {} <Debug> system.query_log (3a40562a-eb15-4055-8ece-969661d81390): Removing 1 parts from memory: Parts: [202409_41_41_0]
2024.09.21 09:21:04.594023 [ 729 ] {} <Fatal> BaseDaemon: 21. ./build/./src/Interpreters/executeQuery.cpp:1717: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x0000000022e14c47
2024.09.21 09:21:04.634939 [ 729 ] {} <Fatal> BaseDaemon: 22. ./build/./src/Server/MySQLHandler.cpp:530: DB::MySQLHandler::comQuery(DB::ReadBuffer&, bool) @ 0x0000000025f4738a
2024.09.21 09:21:04.681732 [ 729 ] {} <Fatal> BaseDaemon: 23. ./build/./src/Server/MySQLHandler.cpp:295: DB::MySQLHandler::run() @ 0x0000000025f3e91d
2024.09.21 09:21:04.685310 [ 729 ] {} <Fatal> BaseDaemon: 24. ./build/./base/poco/Net/src/TCPServerConnection.cpp:43: Poco::Net::TCPServerConnection::start() @ 0x00000000273b452f
2024.09.21 09:21:04.692148 [ 729 ] {} <Fatal> BaseDaemon: 25. ./build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x00000000273b5117
2024.09.21 09:21:04.701287 [ 729 ] {} <Fatal> BaseDaemon: 26. ./build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x00000000272c824b
2024.09.21 09:21:04.709329 [ 729 ] {} <Fatal> BaseDaemon: 27. ./base/poco/Foundation/src/Thread_POSIX.cpp:335: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000272c23a8
2024.09.21 09:21:04.726224 [ 729 ] {} <Fatal> BaseDaemon: 28. asan_thread_start(void*) @ 0x0000000005499059
2024.09.21 09:21:04.726265 [ 729 ] {} <Fatal> BaseDaemon: 29. ? @ 0x00007ff022eb5609
2024.09.21 09:21:04.726315 [ 729 ] {} <Fatal> BaseDaemon: 30. ? @ 0x00007ff023148353
2024.09.21 09:21:04.726344 [ 729 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
```

**Expected behavior**
No crash.

**Additional context**
docker compose config:
```
version: '3.8'
services:
  clickhouse-01:
    image: "my_clickhouse:latest"
    user: "101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.1
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-01/var/log/clickhouse-server:/var/log/clickhouse-server
      - /var/cores
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    # env for ASAN_OPTIONS
    environment:
      - ASAN_OPTIONS=detect_leaks=0:use_sigaltstack=false

  clickhouse-02:
    image: "my_clickhouse:latest"
    user: "101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.2
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-02/var/log/clickhouse-server:/var/log/clickhouse-server
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
    environment:
      - ASAN_OPTIONS=detect_leaks=0:use_sigaltstack=false

  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.5
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/log/clickhouse-keeper:/var/log/clickhouse-keeper
    # caps for get_mempolicy
    cap_add:
      - SYS_NICE

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.6
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    # caps for get_mempolicy
    cap_add:
      - SYS_NICE

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      cluster_2S_1R:
        ipv4_address: 10.0.7.7
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    # caps for get_mempolicy
    cap_add:
      - SYS_NICE

networks:
  cluster_2S_1R:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.7.0/24
          gateway: 10.0.7.254

```

the my_clickhouse:latest is built by:
```dockerfile
FROM clickhouse/clickhouse-server:latest

# replace
COPY ./clickhouse /usr/bin/clickhouse
```

and the binary is built by
```
CC=clang-18 CXX=clang++-18 \
cmake -B build -S . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DENABLE_LIBRARIES=OFF \
    -DSANITIZE=address

cd build
ninja clickhouse-server clickhouse-client
```

config.xml
```xml
<clickhouse replace="true">
    <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
    </logger>
    <display_name>cluster_2S_1R node 1</display_name>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <mysql_port>9004</mysql_port>
    <postgresql_port>9005</postgresql_port>
    <user_directories>
        <users_xml>
            <path>users.xml</path>
        </users_xml>
        <local_directory>
            <path>/var/lib/clickhouse/access/</path>
        </local_directory>
    </user_directories>
    <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
    </distributed_ddl>
    <remote_servers>
        <default>
            <shard>
                <replica>
                    <host>clickhouse-01</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host>clickhouse-02</host>
                    <port>9000</port>
                </replica>
            </shard>
        </default>
    </remote_servers>
    <send_crash_reports>
        <enabled>true</enabled>
    </send_crash_reports>
    <zookeeper>
        <node>
            <host>clickhouse-keeper-01</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-02</host>
            <port>9181</port>
        </node>
        <node>
            <host>clickhouse-keeper-03</host>
            <port>9181</port>
        </node>
    </zookeeper>
    <macros>
        <shard>01</shard>
        <replica>01</replica>
    </macros>
</clickhouse>

```
users.xml
```xml
<?xml version="1.0"?>
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>20000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <distributed_product_mode>allow</distributed_product_mode>
            <allow_experimental_parallel_reading_from_replicas>1</allow_experimental_parallel_reading_from_replicas>
            <allow_experimental_inverted_index>1</allow_experimental_inverted_index>
            <allow_experimental_full_text_index>1</allow_experimental_full_text_index>
            <allow_experimental_join_condition>1</allow_experimental_join_condition>
            <allow_experimental_query_deduplication>1</allow_experimental_query_deduplication>
        </default>
    </profiles>
    <users>
        <default>
            <access_management>1</access_management>
            <profile>default</profile>
            <networks>
                <ip>::/0</ip>
            </networks>
            <password></password>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
            <show_named_collections>1</show_named_collections>
            <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
    </users>
    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>

```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the potential above-mentioned vulnerability that may lead to database error.
