### ISSUE TITLE
Kafka table engine with protobuf serialization cannot handle DateTime(9)

### ISSUE THREAD

**Issue by bichselb** [ClickHouse/ClickHouse#69977]
**Describe the unexpected behaviour**

I would like to feed a kafka topic holding timestamps serialized through protobuf. Unfortunately, it seems like ClickHouse suggests using `uint64` for this purpose, and then interprets this value as "seconds since epoch". Therefore, I cannot encode timestamps at a sub-second precision.

**Why am I encoding timestamps using uint64?**

I would actually prefer a more suitable protobuf type like `google.protobuf.Timestamp`,  but running the following query suggests using uint64:

```sql
SELECT structureToProtobufSchema('
    datetime_column DateTime64(9)
') FORMAT RawBLOB
```

```text
syntax = "proto3";

message Message
{
    uint64 datetime_column = 1;
}
```

**How to reproduce**

To reproduce, simply prepare these files and run `run.sh`:

docker-compose.yml:
```yml
services:
  kafka:
    image: bitnami/kafka:3.7.1
    ports:
      - "9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    volumes:
      - clickhouse_volume:/var/lib/clickhouse
      - ./timestamp_message.proto:/var/lib/clickhouse/format_schemas/data.proto

  python:
    image: python:3.12
    working_dir: /host
    volumes:
      - .:/host
    entrypoint: ["/bin/bash", "-c", "sleep infinity"]  # keep the container running

volumes:
  clickhouse_volume:

networks:
  default:
    driver: bridge
```

timestamp_message.proto:
```proto
syntax = "proto3";

package data;

message TimestampMessage {
  uint64 timestamp_column = 1;
}
```

run.sh:
```sh
#!/bin/bash

# enable bash strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

#############
# VARIABLES #
#############

KAFKA_CONTAINER="kafka"
CLICKHOUSE_CONTAINER="clickhouse"
PYTHON_CONTAINER="python"

###########
# PREPARE #
###########

docker compose down --remove-orphans --volumes
docker compose up --build -d

echo "Waiting for Kafka to be ready..."
until docker compose exec $KAFKA_CONTAINER kafka-topics.sh --list --bootstrap-server $KAFKA_CONTAINER:9092 > /dev/null 2>&1; do
    sleep 1
done
echo "Kafka is ready."

echo "Waiting for ClickHouse to be ready..."
until docker compose exec $CLICKHOUSE_CONTAINER clickhouse-client --query "SELECT 1" > /dev/null 2>&1; do
    sleep 1
done
echo "ClickHouse is ready."

echo "Preparing python container for sending test message to kafka"
docker compose exec $PYTHON_CONTAINER pip install protobuf grpcio-tools confluent_kafka
docker compose exec $PYTHON_CONTAINER python -m grpc_tools.protoc -I. --python_out=. timestamp_message.proto

#########
# SETUP #
#########

echo "Creating Kafka topics..."
docker compose exec $KAFKA_CONTAINER kafka-topics.sh --create \
  --topic my-topic \
  --bootstrap-server $KAFKA_CONTAINER:9092 \
  --partitions 1 \
  --replication-factor 1

echo "Setting up ClickHouse tables and views..."

run_sql_command() {
    local query=$1
    docker compose exec "$CLICKHOUSE_CONTAINER" clickhouse-client --query="$query"
}

echo "Creating kafka input table"
run_sql_command "CREATE TABLE IF NOT EXISTS my_kafka_input (
    timestamp_column DateTime64(9),
) ENGINE = Kafka
SETTINGS
    kafka_broker_list = '$KAFKA_CONTAINER:9092',
    kafka_topic_list = 'my-topic',
    kafka_group_name = 'group1',
    kafka_format = 'Protobuf',
    kafka_schema = 'data:TimestampMessage',
    kafka_num_consumers = 1;
"

echo "Creating clickhouse table"
run_sql_command "CREATE TABLE IF NOT EXISTS my_table (
    timestamp_column DateTime64(9),
) ENGINE = MergeTree()
ORDER BY timestamp_column;
"

echo "Creating materialized view"
run_sql_command "CREATE MATERIALIZED VIEW IF NOT EXISTS my_kafka_view TO my_table AS
SELECT
    timestamp_column
FROM my_kafka_input;
"

########
# TEST #
########

echo "Sending test message"
docker compose exec python python send_message.py

sleep 10

# echo "Querying clickhouse input stream"
# docker compose exec clickhouse clickhouse-client --query="SET stream_like_engine_allow_direct_select = 1; SELECT * FROM my_kafka_input"

echo "Querying clickhouse table..."
docker compose exec clickhouse clickhouse-client --query="SELECT * FROM my_table"

"

########
# TEST #
########

echo "Sending test message"
docker compose exec python python send_message.py

sleep 10

# echo "Querying clickhouse input stream"
# docker compose exec clickhouse clickhouse-client --query="SET stream_like_engine_allow_direct_select = 1; SELECT * FROM my_kafka_input"

echo "Querying clickhouse table..."
docker compose exec clickhouse clickhouse-client --query="SELECT * FROM my_table"
```

send_message.py:
```python
from confluent_kafka import Producer
from datetime import datetime
from timestamp_message_pb2 import TimestampMessage
import struct

producer_config = {
    'bootstrap.servers': 'kafka:9092',
}

producer = Producer(producer_config)

# Function to handle delivery reports from Kafka
def delivery_report(err, msg):
    if err is not None:
        print(f"Message delivery failed: {err}")
    else:
        print(f"Message delivered to {msg.topic()} [{msg.partition()}]")

# Get the current datetime and convert to UNIX timestamp (seconds)
current_time = datetime.now()
timestamp_in_seconds = int(current_time.timestamp())

# Create a TimestampMessage and set the timestamp_column field
message = TimestampMessage()
message.timestamp_column = timestamp_in_seconds

# Produce the message to the Kafka topic
message_bytes = message.SerializeToString()
def varint_encode(value):
    """Encodes an integer as a variable-length integer."""
    result = bytearray()
    while value > 0x7F:
        result.append((value & 0x7F) | 0x80)
        value >>= 7
    result.append(value & 0x7F)
    return bytes(result)
length_prefix = varint_encode(len(message_bytes))
length_delimited_message = length_prefix + message_bytes

producer.produce(topic='my-topic', value=length_delimited_message, callback=delivery_report)

# Wait for any outstanding messages to be delivered
producer.flush()

print(f"Sent message with timestamp: {timestamp_in_seconds}")
```

**Expected behavior**

I would expect that the kafka table engine provides a method to feed in timestamps at sub-second precision.

**Error message and/or stacktrace**

My above code does not throw any errors, but does not allow me to encode sub-second precision timestamps.
