### ISSUE TITLE
Can't add Table  Get Time out

### ISSUE THREAD

**Issue by DanTaliaL** [ClickHouse/ClickHouse#70121]
### Question

I set up ClickHouse using Docker Compose, but I encounter a problem when I try to use the engine ReplicatedReplacingMergeTree while creating a table. I get a timeout, and when I check the databases, I see that they are all marked as read-only. However, if I use ReplacingMergeTree, the insertion works without issues. What could be the reason for this? (I checked the containers, and they can ping each other.) Here’s my config file:

docker-compose

```
services:
  clickhouse-main:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-main
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data_main:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3      

  clickhouse-replica:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-replica
    restart: always
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_data_replica:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    environment:
      CLICKHOUSE_REPLICA: "1"
      CLICKHOUSE_MAIN_HOST: "clickhouse-main"
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3  

  clickhouse-main-2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-main-2
    restart: always
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data_main-2:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3      

  clickhouse-replica-2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-replica-2
    restart: always
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - clickhouse_data_replica-2:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    environment:
      CLICKHOUSE_REPLICA: "1"
      CLICKHOUSE_MAIN_HOST: "clickhouse-main"
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3  

  zoo1:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo1
    restart: always
    environment:
      KEEPER_ID: "1"
    ports:
      - "2181:2181"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork

  zoo2:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo2
    restart: always
    environment:
      KEEPER_ID: "2" 
    ports:
      - "2182:2181"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork
      
  zoo3:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo3
    restart: always
    ports:
      - "2183:2181"
    environment:
      KEEPER_ID: "3"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork      

networks:
  mynetwork:

volumes:
  clickhouse_data_main:
  clickhouse_data_replica:
  clickhouse_data_main-2:
  clickhouse_data_replica-2:

```

clickhouse_config

```
<?xml version="1.0"?>
<clickhouse>
    <logger>
        <log>/var/log/clickhouse-server/logger.log</log>
        <errorlog>/var/log/clickhouse-server/logger.errorlog</errorlog>
    </logger>
		
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>

    <!-- <max_connections>4096</max_connections> -->
    <!-- <keep_alive_timeout>3</keep_alive_timeout> -->
    <!-- <max_concurrent_queries>100</max_concurrent_queries> -->
    <!-- <uncompressed_cache_size>8589934592</uncompressed_cache_size> -->
    <!-- <mark_cache_size>5368709120</mark_cache_size> -->

    <path>/var/lib/clickhouse/</path>
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
    <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>

	<macros>
		<replica1>replica1</replica1>
		<layer1>1</layer1>
		<shard1>shard1</shard1>
		<replica2>replica2</replica2>
		<layer2>2</layer2>
		<shard2>shard2</shard2>
    </macros>
	

	<users_config>users.xml</users_config>

	<distributed_ddl>
		<max_partitions_per_insert_block>1000</max_partitions_per_insert_block>
	</distributed_ddl>
	
	<remote_servers>
		<my_cluster>
			<shard>
				<replica>
					<host>clickhouse-main</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>clickhouse-replica</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<replica>
					<host>clickhouse-main-2</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>clickhouse-replica-2</host>
					<port>9000</port>
				</replica>
			</shard>
		</my_cluster>
	</remote_servers>

    <zookeeper>
		<node index="1">
			<host>zoo1</host>
			<port>9181</port>
		</node>
		<node index="2">
			<host>zoo2</host>
			<port>9181</port>
		</node>
		<node index="3">
			<host>zoo3</host>
			<port>9181</port>
		</node>		
    </zookeeper>
		

</clickhouse>
```

keeper_config

```
<clickhouse>
    <logger>
        <level>trace</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
    </logger>

    <max_connections>4096</max_connections>

    <keeper_server>
            <tcp_port>8181</tcp_port>
            <server_id from_env="KEEPER_ID" />

            <log_storage_path>/var/lib/clickhouse/coordination/logs</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
                <compress_logs>false</compress_logs>
            </coordination_settings>

            <hostname_checks_enabled>true</hostname_checks_enabled>
            <raft_configuration>
			
        <server>
            <id>1</id>
            <hostname>zoo1</hostname>
            <port>9181</port>
        </server>
        <server>
            <id>2</id>
            <hostname>zoo2</hostname>
            <port>9181</port>
        </server>
        <server>
            <id>3</id>
            <hostname>zoo3</hostname>
            <port>9181</port>
        </server>
            </raft_configuration>
    </keeper_server>


    <openSSL>
      <server>
            <!-- Used for secure tcp port -->
            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
            <!-- <certificateFile>/etc/clickhouse-keeper/server.crt</certificateFile> -->
            <!-- <privateKeyFile>/etc/clickhouse-keeper/server.key</privateKeyFile> -->
            <!-- dhparams are optional. You can delete the <dhParamsFile> element.
                 To generate dhparams, use the following command:
                  openssl dhparam -out /etc/clickhouse-keeper/dhparam.pem 4096
                 Only file format with BEGIN DH PARAMETERS is supported.
              -->
            <!-- <dhParamsFile>/etc/clickhouse-keeper/dhparam.pem</dhParamsFile> -->
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>
    </openSSL>

</clickhouse>
```

user-config
```
<clickhouse>
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>1</use_uncompressed_cache>
            <load_balancing>random</load_balancing>
            <log_queries>1</log_queries>		
        </default>
        <readonly>
            <readonly>1</readonly>
        </readonly>
    </profiles>


    <users>    
        <default>     
            <password></password>         
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
            <access_management>1</access_management>
            <named_collection_control>1</named_collection_control>
        </default>
    </users>

    <quotas>   
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse>
```

**Comment by Felixoid** [comment]
Hi hi. You forgot to add `user_config.xml` to the question

**Comment by Felixoid** [comment]
and query to test the issue, please

**Comment by DanTaliaL** [comment]
> and query to test the issue, please

Hi, I completely forgot about the user-config (added it).

Here is an example of creating a table.

I only use Replacing (it works):
`
CREATE TABLE IF NOT EXISTS admin_history_shard (
    _id UUID,
    _userId UUID,
    Action Nullable(String),
    DateOfAction Nullable(DateTime),
    Version Int32
) ENGINE = ReplacingMergeTree(Version)
ORDER BY _id;
`

TimeOut
`
CREATE TABLE IF NOT EXISTS admin_history_test (
    _id UUID,
    _userId UUID,
    Action Nullable(String),
    DateOfAction Nullable(DateTime),
    Version Int32
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{layer1}-{shard1}/admin_history_test', '{replica1}', Version)
ORDER BY _id;
`

**Comment by Felixoid** [comment]
```
SELECT *
FROM system.zookeeper
WHERE path = '/'
```

It timeouts as well. I execute it on the clickhouse-main container.

and here's why:

```
 <keeper_server>
            <tcp_port>8181</tcp_port>
```

https://github.com/ClickHouse/ClickHouse/blob/a261c0a77ebd9c17dc7e16e30b8f3f0363b5b9b1/programs/keeper/keeper_config.xml#L31

Not sure why you're changed it, but this is the reason

**Comment by Felixoid** [comment]
TBH, the configs look entirely wrong. You use random ports in the keeper configs, they don't match the clickhouse ports..

Here are the final configs that work. I've fixed the ports, and added `<listen_host>::</listen_host>` to the keeper config.

```xml
<clickhouse>
    <logger>
        <level>trace</level>
        <log>/var/log/clickhouse-keeper/clickhouse-keeper.log</log>
        <errorlog>/var/log/clickhouse-keeper/clickhouse-keeper.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
    </logger>

    <max_connections>4096</max_connections>

    <listen_host>::</listen_host>
    <keeper_server>
            <tcp_port>9181</tcp_port>
            <server_id from_env="KEEPER_ID" />

            <log_storage_path>/var/lib/clickhouse/coordination/logs</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
                <compress_logs>false</compress_logs>
            </coordination_settings>

            <hostname_checks_enabled>true</hostname_checks_enabled>
            <raft_configuration>
                <server>
                    <id>1</id>
                    <hostname>zoo1</hostname>
                    <port>9234</port>
                </server>
                <server>
                    <id>2</id>
                    <hostname>zoo2</hostname>
                    <port>9234</port>
                </server>
                <server>
                    <id>3</id>
                    <hostname>zoo3</hostname>
                    <port>9234</port>
                </server>
            </raft_configuration>
    </keeper_server>


    <openSSL>
      <server>
            <!-- Used for secure tcp port -->
            <!-- openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt -->
            <!-- <certificateFile>/etc/clickhouse-keeper/server.crt</certificateFile> -->
            <!-- <privateKeyFile>/etc/clickhouse-keeper/server.key</privateKeyFile> -->
            <!-- dhparams are optional. You can delete the <dhParamsFile> element.
                 To generate dhparams, use the following command:
                  openssl dhparam -out /etc/clickhouse-keeper/dhparam.pem 4096
                 Only file format with BEGIN DH PARAMETERS is supported.
              -->
            <!-- <dhParamsFile>/etc/clickhouse-keeper/dhparam.pem</dhParamsFile> -->
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>
    </openSSL>

</clickhouse>
```

```xml
<?xml version="1.0"?>
<clickhouse>
    <logger>
        <log>/var/log/clickhouse-server/logger.log</log>
        <errorlog>/var/log/clickhouse-server/logger.errorlog</errorlog>
    </logger>
		
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>

    <!-- <max_connections>4096</max_connections> -->
    <!-- <keep_alive_timeout>3</keep_alive_timeout> -->
    <!-- <max_concurrent_queries>100</max_concurrent_queries> -->
    <!-- <uncompressed_cache_size>8589934592</uncompressed_cache_size> -->
    <!-- <mark_cache_size>5368709120</mark_cache_size> -->

    <path>/var/lib/clickhouse/</path>
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
    <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>

	<macros>
		<replica1>replica1</replica1>
		<layer1>1</layer1>
		<shard1>shard1</shard1>
		<replica2>replica2</replica2>
		<layer2>2</layer2>
		<shard2>shard2</shard2>
    </macros>
	

	<users_config>users.xml</users_config>

	<distributed_ddl>
		<max_partitions_per_insert_block>1000</max_partitions_per_insert_block>
	</distributed_ddl>
	
	<remote_servers>
		<my_cluster>
			<shard>
				<replica>
					<host>clickhouse-main</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>clickhouse-replica</host>
					<port>9000</port>
				</replica>
			</shard>
			<shard>
				<replica>
					<host>clickhouse-main-2</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>clickhouse-replica-2</host>
					<port>9000</port>
				</replica>
			</shard>
		</my_cluster>
	</remote_servers>

    <zookeeper>
		<node index="1">
			<host>zoo1</host>
			<port>9181</port>
		</node>
		<node index="2">
			<host>zoo2</host>
			<port>9181</port>
		</node>
		<node index="3">
			<host>zoo3</host>
			<port>9181</port>
		</node>		
    </zookeeper>
		

</clickhouse>
```

```yaml
services:
  clickhouse-main:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-main
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data_main:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse-replica:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-replica
    restart: always
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_data_replica:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    environment:
      CLICKHOUSE_REPLICA: "1"
      CLICKHOUSE_MAIN_HOST: "clickhouse-main"
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse-main-2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-main-2
    restart: always
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data_main-2:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  clickhouse-replica-2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-replica-2
    restart: always
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - clickhouse_data_replica-2:/var/lib/clickhouse
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./user-config.xml:/etc/clickhouse-server/users.xml
    environment:
      CLICKHOUSE_REPLICA: "1"
      CLICKHOUSE_MAIN_HOST: "clickhouse-main"
    networks:
      - mynetwork
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo1
    restart: always
    environment:
      KEEPER_ID: "1"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork

  zoo2:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo2
    restart: always
    environment:
      KEEPER_ID: "2"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork

  zoo3:
    image: clickhouse/clickhouse-keeper:latest
    container_name: zoo3
    restart: always
    environment:
      KEEPER_ID: "3"
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  clickhouse_data_main:
  clickhouse_data_replica:
  clickhouse_data_main-2:
  clickhouse_data_replica-2:
```
