### ISSUE TITLE
Exception: No Zookeeper config found when using S3Queue table engine

### ISSUE THREAD

**Issue by a-dragos** [ClickHouse/ClickHouse#70398]
### Question

Hello!

When I try to use a single clickhouse instance with S3Queue table engine and a named_collection, clickhouse fails to start due to missing Zookeeper configuration.
I create a `named_collections.xml`:
```xml
<clickhouse>
  <named_collections>
    <s3queue_nc>
      <url>'https://s3url/bucket-name/*.csv'</url>
     <user_environment_credentials>1</use_environment_credentials>
    </s3queue_nc>
  </named_collections>
</clickhouse>
```
and a table to stream data from S3:
```
CREATE TABLE s3queue_table
(
id String
name String
....
) engine S3Queue(s3queue_nc)
SETTINGS
mode = 'unordered',
after_processing = 'keep',
enable_logging_to_s3queue_log = 1
```
When I start the clickhouse-server in a docker container, I receive the following error:
```
DB::Exception Received from localhost:9000. DB::Exception: There is no Zookeeper configuration in server config. (NO_ELEMENTS_IN_CONFIG). (query CREATE TABLE s3queue_table ....)
```
Clickhouse version: 24.8.2.

There is a Zookeeper reference in the docs [mode](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3queue#mode), but is Zookeeper mandatory for a single clickhouse instance scaled vertically? If not, how can I make clickhouse skip the Zookeeper config check ?

**Comment by alexey-milovidov** [comment]
Yes, S3Queue requires Keeper.
You can configure embedded Keeper to keep it under a single node.

Put this into `/etc/clickhouse-server/config.d/keeper_server.yaml`:
```
keeper_server:
    tcp_port: 9181
    server_id: 1
    
    # Only suitable for single-node configuration:
    heart_beat_interval_ms: 0
    election_timeout_lower_bound_ms: 0
    election_timeout_upper_bound_ms: 0

    raft_configuration:
        server:
            id: 1
            hostname: localhost
            port: 9234

    feature_flags:
        filtered_list: 1
        multi_read: 1
        check_not_exists: 1
        create_if_not_exists: 1
        remove_recursive: 1
```

Put this into `/etc/clickhouse-server/config.d/keeper_client.yaml`:
```
keeper:
    node:
        host: 127.0.0.1
        port: 9181
```
