### ISSUE TITLE
 Old Data Movement on TTL Volume Name Change with materialize_ttl_after_modify=0

### ISSUE THREAD

**Issue by YishayM** [ClickHouse/ClickHouse#71543]
**Describe what's wrong**
When changing only the volume name in a TTL expression, old data moves even with `materialize_ttl_after_modify=0`.

**Initial TTL**

```sql
TTL time + INTERVAL 1 SECOND TO VOLUME 'jbod_volume'
```
**Modification**
```sql
ALTER TABLE events MODIFY TTL time + INTERVAL 1 SECOND TO VOLUME 's3_volume'
SETTINGS materialize_ttl_after_modify=0;
```
**Result**
All old data in the table will move.

Does it reproduce on the most recent release?
Yes, reproduced on latest.

How to reproduce
ClickHouse server version: latest
Docker Compose configuration:
```yml
version: '3.8'
services:
  clickhouse01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./docker/clickhouse/config:/etc/clickhouse-server
      - ./docker/clickhouse/data1:/var/lib/clickhouse/data1:rw
      - ./docker/clickhouse/hot_data1:/hot_data1:rw
      - ./docker/clickhouse/s3:/s3:rw
```
Storage configuration (storage.xml):

```xml
<storage_configuration>
    <disks>
        <default>
            <keep_free_space_bytes>1024</keep_free_space_bytes>
        </default>
        <data1>
            <path>/data1/</path>
        </data1>
        <hot_data1>
            <path>/hot_data1/</path>
        </hot_data1>
        <s3>
            <path>/s3/</path>
        </s3>
    </disks>
    <policies>
        <jbod>
            <volumes>
                <hot_jbod_volume>
                    <disk>hot_data1</disk>
                </hot_jbod_volume>
                <jbod_volume>
                    <disk>data1</disk>
                </jbod_volume>
                <s3_volume>
                    <disk>s3</disk>
                </s3_volume>
            </volumes>
            <move_factor>0.1</move_factor>
        </jbod>
    </policies>
</storage_configuration>
```
**SQL statements:**
Create table:
```sql
CREATE TABLE events
(
    event String,
    time DateTime DEFAULT now(),
    value Int64
)
ENGINE = MergeTree
TTL time + INTERVAL 1 SECOND TO VOLUME 'jbod_volume'
ORDER BY (event, time)
SETTINGS storage_policy = 'jbod';
```
**Insert data:**
```sql
INSERT INTO events VALUES ('event', now() - INTERVAL 3 MINUTE, 0);
```
Verify data location:
```sql
SELECT disk_name, active, rows, name FROM system.parts WHERE table = 'events';
```

Modify TTL destination volume:

```sql
ALTER TABLE events MODIFY TTL time + INTERVAL 1 SECOND TO VOLUME 's3_volume'
SETTINGS materialize_ttl_after_modify=0;
```

**Expected behavior**

Existing data should stay on the data disk and *not move* to s3, but it does move to the new volume.
