### ISSUE TITLE
Can not reload/resume S3Queue when shutting down then restarting clickhouse + clickhouse-keeper : `"Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes"`

### ISSUE THREAD

**Issue by Atala** [ClickHouse/ClickHouse#71592]
FYI I fixed by adding a healthcheck in docker compose so clickhouse server waits or the keeper to be properly up.

Relevant lines in bold:
```
  clickhouse-server:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    ports:
      - 8124:8123
      - 9010:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/server/data:/var/lib/clickhouse
      - ./clickhouse/server/logs:/var/log/clickhouse-server
      - ./clickhouse/config/server/conf.d/:/etc/clickhouse-server/conf.d/
      # - ./config/users.xml:/etc/clickhouse-server/users.xml
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    **depends_on:
      clickhouse-keeper:
        condition: service_healthy** 
    env_file:
      - path: ./.env
      - path: ./.env.local

  clickhouse-keeper:
    build:
      dockerfile: './clickhouse/keeper/Dockerfile'
      context: '.'
    hostname: clickhouse-keeper
    volumes:
      - keeper0_data:/var/lib/clickhouse
      - ./clickhouse/keeper/logs:/var/log/clickhouse-keeper
      - ./clickhouse/config/keeper/conf.d/:/etc/clickhouse-keeper/conf.d/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    **healthcheck:
      test: ["CMD-SHELL", "if [ 1 == $(netstat -ltn | grep -c 9181) ]; then echo 0; else echo 1; fi;"]
      interval: 1s
      timeout: 5s
      retries: 5**
    env_file:
      - path: ./.env
      - path: ./.env.local
```

### Company or project name

CoopCycle

### Question

Hello,

I use clickhouse + clickhouse-keeper v24.10.1.2812 in docker compose.

I defined a S3Queue like this :
```
-- S3Queue
CREATE OR REPLACE TABLE tasksQueue (
	id Int32,
	order_id Nullable(Int32),
	order_code Nullable(String),
	order_total Nullable(Int32),
	order_revenue Nullable(Int32),
	type Enum('PICKUP' = 0, 'DROPOFF' = 1),
	address Tuple(
		contact Nullable(String),
		name Nullable(String),
		street String,
		description Nullable(String),
		lat Float32,
		lng Float32
	),
	after DateTime64(6),
	before DateTime64(6),
	status Enum('TODO' = 1, 'DOING' = 2, 'FAILED' = 3, 'DONE' = 4, 'CANCELLED' = 5),
	finished Nullable(DateTime64(6)),
	courier Nullable(String),
	organization Nullable(String)
) ENGINE = S3Queue('<path_to_data>')
SETTINGS mode = 'ordered';
```

When I create the table it starts downloading alright.
However if i shutdown both clickhouse and the keeper.
When I put it back up it doesn't seem to be able to resume the download. I tested the connection to the keeper from the server with telnet + ruok and I worked.

```
Cannot load data for command line suggestions: Code: 722. DB::Exception: Received from localhost:9010. DB::Exception: Waited job failed: Code: 696. DB::Exception: Load job 'startup table default.tasksQueue' -> Code: 695. DB::Exception: Load job 'load table default.tasksQueue' failed: Code: 999. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: 172.19.0.4:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.10.1.2812 (official build)), 172.19.0.4:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.10.1.2812 (official build)), 172.19.0.4:9181
Poco::Exception. Code: 1000, e.code() = 111, Connection refused (version 24.10.1.2812 (official build)), 172.19.0.4:9181
: Cannot attach table `default`.`tasksQueue` from metadata file /var/lib/clickhouse/store/e89/e895b00b-1369-42ab-b365-7d48ea418e57/tasksQueue.sql from query ATTACH TABLE default.tasksQueue UUID '56128ccb-fec6-42e6-9a06-88e0b2992aa5' (`id` Int32, `order_id` Nullable(Int32), `order_code` Nullable(String), `order_total` Nullable(Int32), `order_revenue` Nullable(Int32), `type` Enum8('PICKUP' = 0, 'DROPOFF' = 1), `address` Tuple(contact Nullable(String), name Nullable(String), street String, description Nullable(String), lat Float32, lng Float32), `after` DateTime64(6), `before` DateTime64(6), `status` Enum8('TODO' = 1, 'DOING' = 2, 'FAILED' = 3, 'DONE' = 4, 'CANCELLED' = 5), `finished` Nullable(DateTime64(6)), `courier` Nullable(String), `organization` Nullable(String)) ENGINE = S3Queue('<path>') SETTINGS mode = 'ordered'. (KEEPER_EXCEPTION),. (ASYNC_LOAD_WAIT_FAILED) (version 24.10.1.2812 (official build))

```

I use the following config docker compose, the server and the keeper [https://github.com/r0xsh/clickhouse-docker](https://github.com/r0xsh/clickhouse-docker)

any idea?

thanks!

**Comment by Atala** [comment]
FYI I fixed by adding a healthcheck in docker compose so clickhouse server waits or the keeper to be properly up.

Relevant lines in bold:
```
  clickhouse-server:
    image: clickhouse/clickhouse-server
    hostname: clickhouse
    ports:
      - 8124:8123
      - 9010:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/server/data:/var/lib/clickhouse
      - ./clickhouse/server/logs:/var/log/clickhouse-server
      - ./clickhouse/config/server/conf.d/:/etc/clickhouse-server/conf.d/
      # - ./config/users.xml:/etc/clickhouse-server/users.xml
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    **depends_on:
      clickhouse-keeper:
        condition: service_healthy** 
    env_file:
      - path: ./.env
      - path: ./.env.local

  clickhouse-keeper:
    build:
      dockerfile: './clickhouse/keeper/Dockerfile'
      context: '.'
    hostname: clickhouse-keeper
    volumes:
      - keeper0_data:/var/lib/clickhouse
      - ./clickhouse/keeper/logs:/var/log/clickhouse-keeper
      - ./clickhouse/config/keeper/conf.d/:/etc/clickhouse-keeper/conf.d/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    **healthcheck:
      test: ["CMD-SHELL", "if [ 1 == $(netstat -ltn | grep -c 9181) ]; then echo 0; else echo 1; fi;"]
      interval: 1s
      timeout: 5s
      retries: 5**
    env_file:
      - path: ./.env
      - path: ./.env.local
```
