### ISSUE TITLE
config.yaml file parsing for zookeepers to config.xml is not correct

### ISSUE THREAD

**Issue by vdegtyarevtv** [ClickHouse/ClickHouse#72247]
**How to reproduce**
I'm using a config.yaml file instead of a config.xml file and am having an issue with the zookeeper configuration. In your example,
```
# zookeeper:
#     - node:
#         host: example1
#         port: 2181
#     - node:
#         host: example2
#         port: 2181
#     - node:
#         host: example3
#         port: 2181
```
i did the same
```
zookeeper:
    - node:
        host: "zoo-1"
        port: 2181
    - node:
        host: "zoo-2"
        port: 2181
    - node:
        host: "zoo-3"
        port: 2181
```
However, I faced an issue where Clickhouse was trying to connect only to the first Zookeeper, and when zoo-1 went down, my replicated tables became readonly and Clickhouse was not attempting to connect to the other two Zookeepers.

I then checked the /var/lib/clickhouse/preprocessed_configs/config.xml file and saw that there was an issue with parsing the YAML file into XML.

```
    <zookeeper>
        <node>
            <host>zoo-1</host>
            <port>2181</port>
        </node>
    </zookeeper>
    <zookeeper>
        <node>
            <host>zoo-2</host>
            <port>2181</port>
        </node>
    </zookeeper>
    <zookeeper>
        <node>
            <host>zoo-3</host>
            <port>2181</port>
        </node>
    </zookeeper>
```
The same problem has been resolved here, but it hasn't for the zookeeper. https://github.com/ClickHouse/ClickHouse/pull/41044

So if i change my yaml file to

```
zookeeper:
      node:
        host: "zoo-1"
        port: 2181
      node:
        host: "zoo-2"
        port: 2181
      node:
        host: "zoo-3"
        port: 2181
```
the parsing is correct (but the syntax is not correct for a YAML file, and the linter will fail).

```
    <zookeeper>
        <node>
            <host>zoo-1</host>
            <port>2181</port>
        </node>
        <node>
            <host>zoo-2</host>
            <port>2181</port>
        </node>
        <node>
            <host>zoo-3</host>
            <port>2181</port>
        </node>
    </zookeeper>
```

* Which ClickHouse server version to use
```
SELECT version()

Query id: 6a92de7d-63ca-49c5-92a0-0c2a6879a9e2

   ┌─version()─┐
1. │ 24.9.2.42 │
   └───────────┘
```

**Comment by NeedPainkillers** [comment]
Same issue for raft_configuration in ClickHouse Keeper config with YAML. Only first server is parsed.

**Comment by vdegtyarevtv** [comment]
fixed it using
```
zookeeper:
    node:
      - host: "zoo-1"
        port: 2181
    node:
      -  host: "zoo-2"
         port: 2181
    node:
      -  host: "zoo-3"
         port: 2181
```

after that fix everything working fine. I guess you need to fix it in your example file https://github.com/ClickHouse/ClickHouse/blob/67cd772e6bbdead57430fd4f31363d79c28b0b9d/programs/server/config.yaml.example#L591-L600
