### ISSUE TITLE
Non-deterministic table scans depending on who/what triggered a query (major differences in IDENTICAL query execution with Cube.dev vs CH Cloud UI)

### ISSUE THREAD

**Issue by BeautyFades** [ClickHouse/ClickHouse#72620]
**Describe the bug**
I have a fact table that is joined with a few dimensional tables in ClickHouse. We use Cube.dev as a Semantics and API Layer, and our applications trigger requests to Cube, which in turn queries CH and responds back to the user once the query results are in.

Cube.dev exposes a playground to format and test queries. It basically translates a request body in JSON format into a SQL query and runs it in whatever source DW. 

I have set up a data model with a single fact and dim tables to replicate the issue. When running an unfiltered Cube query via Playground that is a simple ```SELECT {fields} FROM {fact} LEFT JOIN {dim} ON {condition} GROUP BY {...} ORDER BY {...}``` it runs as expected (unfiltered query, fetches all row in the fact table). 
When adding a filter to the dimension table in the data model, CH keeps on doing full table scans if the query was triggered by Cube, despite this not happening when triggering the **EXACT SAME SQL QUERIES** Cube generated, but manually in the via CH's UI (SQL Console).

When viewing CH's logs, it never partition prunes or optimizes Cube's filtered queries, doing a full table scan everytime. Looks like something happens with queries triggered by Cube specifically that disables or makes CH's query plan optimizer stop working.

**To Reproduce**
1. Create a trial ClickHouse cluster and a couple tables with some data on them. I'm trying to simulate a fact table with JOINs with a dimensional table. 
To do so just run the following block:
```
-- Create a dummy fact table
CREATE TABLE zz_fact (
    tenant_id String,
    user_id UUID,
    component_id UUID,
    dummy_value UInt8
)
ENGINE = MergeTree
PRIMARY KEY (tenant_id, user_id, component_id)
ORDER BY (tenant_id, user_id, component_id)
SETTINGS index_granularity = 8192;

-- Populate the dummy table with random data
INSERT INTO zz_fact
SELECT
    arrayElement([
        'TENANT 1', 
        'TENANT 2', 
        'TENANT 3', 
        'TENANT 4', 
        'TENANT 5', 
        'TENANT 6', 
        'TENANT 7', 
        'TENANT 8', 
        'TENANT 9', 
        'TENANT 0'
    ], 
    1 + (rand() % 10)) AS tenant_id,  -- Pick a random tenant_id from the array

    generateUUIDv4() AS user_id,
    generateUUIDv4() AS component_id,
    rand() % 2 AS dummy_value
FROM numbers(100000000);

-- Create a tenant table
CREATE TABLE zz_dim_tenants (
    tenant_id String,
    tenant_name String
)
ENGINE = MergeTree
PRIMARY KEY (tenant_id)
ORDER BY (tenant_id)
SETTINGS index_granularity = 8192;

-- Populate the dummy table with data
INSERT INTO zz_dim_tenants VALUES
('TENANT 1', 'Tenant 1'),
('TENANT 2', 'Tenant 2'),
('TENANT 3', 'Tenant 3'),
('TENANT 4', 'Tenant 4'),
('TENANT 5', 'Tenant 5'),
('TENANT 6', 'Tenant 6'),
('TENANT 7', 'Tenant 7'),
('TENANT 8', 'Tenant 8'),
('TENANT 9', 'Tenant 9'),
('TENANT 0', 'Tenant 0')
```

As you can see, the tables have a proper PK.

2. Create a Cube schema to query these tables via Cube. I'm using Cube v1.1.7 here. Refer to Cube docs for further instructions
Fact table Cube definition:
```
cubes:
  - name: zz_fact
    sql_table: zz_fact
    sql_alias: fact
    data_source: default
    refresh_key:
      every: 2 seconds

    joins:
      - name: zz_dim_tenants
        sql: "{CUBE}.tenant_id = {zz_dim_tenants}.tenant_id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: "{CUBE}.tenant_id || ' | ' || {CUBE}.user_id || ' | ' || {CUBE}.component_id"
        type: string
        primary_key: true
        shown: true

      - name: tenant_id
        sql: tenant_id
        type: string

      - name: user_id
        sql: user_id
        type: string

      - name: component_id
        sql: component_id
        type: string

      - name: dummy_value
        sql: dummy_value
        type: string

    measures:
      - name: count
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
```

And the dimensional table:
```
cubes:
  - name: zz_dim_tenants 
    sql_table: zz_dim_tenants 
    sql_alias: dim_tenants
    data_source: default
    refresh_key:
      every: 2 seconds

    joins: []

    dimensions:
      - name: tenant_id
        sql: tenant_id
        type: string
        primary_key: true
        shown: true

      - name: tenant_name
        sql: tenant_name
        type: string

    measures:
      - name: count
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
```

3. Set up the Cube instance with these Cubes and connect it to CH properly. Here's some dummy envs:
```
CUBEJS_DB_TYPE=clickhouse
CUBEJS_DB_HOST=xxx.us-east-1.aws.clickhouse.cloud
CUBEJS_DB_NAME=default
CUBEJS_DB_USER=default
CUBEJS_DB_PASS=<PASS>
CUBEJS_DB_PORT=<PORT>
CUBEJS_DB_SSL=true
```

4. Query this table via Cube with a query body exactly like:
```
{
  "limit": 5000,
  "measures": [
    "zz_fact.count"
  ],
  "dimensions": [
    "zz_dim_tenants.tenant_id",
    "zz_dim_tenants.tenant_name"
  ]
}
```
It should properly run and take at least around 3-6 seconds to run the counts on the 100M dataset.

5. Now add a tenant_id filter to the tenant dimension and re-run the query. This is the query:
```
{
  "limit": 5000,
  "measures": [
    "zz_fact.count"
  ],
  "dimensions": [
    "zz_dim_tenants.tenant_id",
    "zz_dim_tenants.tenant_name"
  ],
  "filters": [
    {
      "member": "zz_dim_tenants.tenant_id",
      "operator": "equals",
      "values": [
        "TENANT 1"
      ]
    }
  ]
}
```
You'll notice it takes the same amount of time to run this query, which is odd. It should've been quite a bit faster due to ClickHouse optimizing the query (not 10x, as there's Cube's overhead and round trip, but still!). I'll prove this soon.

6. Check ClickHouse logs for the query in ```system.query_logs```. I'm using this query to check:
```
SELECT type, hostname, event_time, query_duration_ms, read_rows, result_rows, query, `user`
FROM clusterAllReplicas(default, system, query_log) 
WHERE 1 = 1 
    AND user = 'default'
    AND event_time >= '2024-11-28'
    AND type = 'QueryFinish'
ORDER BY event_time DESC;
```

The results I have indicate that both the filtered and unfiltered queries read all 100M rows (full table scans). You can see that the unfiltered query (highlighted in red) is IDENTICAL to the filtered one (in yellow) EXCEPT for the ```WHERE``` clause with the ```tenant_id``` filter:
![image](https://github.com/user-attachments/assets/d04a0334-a2a7-470f-a818-40a08b23492f)
(I've gotten these SQL statements directly from the ```query_log``` table by right clicking on the cell and inspecting it).

7. **Now comes the weird part.** If I copy these two EXACT SQL statements without doing ANY modifications AT ALL to them and run them in the ClickHouse console, I get wildly different performances (yes, I tried with ```SETTINGS use_query_cache = false, enable_writes_to_query_cache = false;``` both at ```false``` and ```true``` values, just to be sure).

Unfiltered query, as expected, takes some time and scans all 100M rows, just like running it through Cube:
![image](https://github.com/user-attachments/assets/2f4d1525-3706-4d01-a980-9802be78a2ad)

However, the filtered query now properly prunes partitions and scans only the needed partitions. It scans 10M rows and runs 10x faster:
![image](https://github.com/user-attachments/assets/a3926b7c-4b66-4108-825b-9da810245275)

---
In summary, running queries via Cube disables ClickHouse's optimization and partition pruning. Why? Why does running the EXACT SAME query via Cube and via ClickHouse produce different results? Is Cube adding something to the query request that does not show up in CH logs that break its optimizer? If you try running CH'S ```EXPLAIN PLAN indexes=1``` on the query, it should be indeed pruning everything properly, it just doesn't when Cube triggers the query.

This only happens when there is a JOIN involved in the query, for some reason. I tried adding the filter directly in the fact table and it then pruned partitions properly. However, in my applications, I have to filter in the dimension tables.

Here's the output of the query logs comparing the filtered queries ran by hand (first line) and by Cube (second line). Note that again, both queries are identical. This contains my actual real-world query while this topic based on a reproduceable example of that.
[query logs_2024-11-28.csv](https://github.com/user-attachments/files/17953514/query.logs_2024-11-28.csv)

As noted in the logs, the main differences I see are the user who triggered the query, of course, and also the ```http_user_agent``` which is sqlui/1.0.17 when running queries manually, but clickhouse-js/1.7.0 when they are triggered by Cube. Could that cause weirdness with CH's query optimizer?

Is anyone else using Cube and facing similar issues?

**Expected behavior**
I'd expect the executed SQL that came from Cube to perform nearly as fast as running it via ClickHouse UI or via JDBC connection. And I'm not talking about latency or round trips. I'm talking the CH DW optimizer doing entirely different things when queries are triggered by Cube.

**Cube Version:**
v1.1.7. Also tested with v1.1.6.

**CH Version:**
Version 24.8

EDIT: Found this that might be interesting. From ```system.query_log``` ProfileEvents column:
![image](https://github.com/user-attachments/assets/cb90e9eb-0f5a-48fa-9fc6-3ea04587bcb0)
Indeed the Cube-fired query isn't using PKs for partition pruning despite the query being the exact same.

EDIT 2: I also tried with a smaller table with 10k rows and a lower index_granularity (2048). Same thing happens, both filtered and unfiltered queries are scanning all of the table when ran via Cube, but running the exact same query on the Cloud UI properly skips granules when filtered.
