### ISSUE TITLE
Unable to `CREATE USER` with appropriate configs set

### ISSUE THREAD

**Issue by marshallm94** [ClickHouse/ClickHouse#72976]
**Company or project name**

Personal (no company).

**Describe the unexpected behaviour**
I am unable to create a user despite having the appropriate configs set.

**How to reproduce**

1. Use the following files:
   - `docker-compose.yml`:
     ```yaml
     services:
       clickhouse:
         container_name: clickhouse-server
         image: clickhouse/clickhouse-server@sha256:f5b4c34c3e1f6612a6dbfe9946b3f125570e79e21dc90c56a6b33151f6335df3
         volumes:
           - clickhouse-data:/var/lib/clickhouse/
           - clickhouse-logs:/var/log/clickhouse-server/
           - clickhouse-access:/var/lib/clickhouse/access/
           - ./clickhouse-server/users.xml:/etc/clickhouse-server/users.xml
           - ./clickhouse-server/config.d/log-to-console.xml:/etc/clickhouse-server/config.d/log-to-console.xml
           - ./clickhouse-server/config.d/path.xml:/etc/clickhouse-server/config.d/path.xml
         ulimits:
           nofile:
             soft: 262144
             hard: 262144
         ports:
           # HOST_PORT:CONTAINER_PORT
           - 9000:9000

     volumes:
       clickhouse-data:
       clickhouse-logs:
       clickhouse-access:
     ```
   - `./clickhouse-server/users.xml`:
     ```xml
     <clickhouse>
       <profiles>
         <default></default>
       </profiles>

       <users>
         <default>
           <password></password>

           <networks>
               <ip>::/0</ip>
           </networks>

           <profile>default</profile>
           <quota>default</quota>

           <!-- Allows SQL-based RBAC: https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control -->
           <access_management>1</access_management>
           <named_collection_control>1</named_collection_control>
           <show_named_collections>1</show_named_collections>
           <show_named_collections_secrets>1</show_named_collections_secrets>
         </default>
       </users>
     </clickhouse>
     ```
   - `./clickhouse-server/config.d/log-to-console.xml` :
     ```xml
     <clickhouse>
         <logger>
             <console>true</console>
             <log remove="remove"/>
             <errorlog remove="remove"/>
         </logger>
     </clickhouse>
     ```
   - `./clickhouse-server/config.d/path.xml` :
     ```xml
     <clickhouse>
         <tmp_path replace="replace">./tmp/</tmp_path>
         <user_files_path replace="replace">./user_files/</user_files_path>
         <format_schema_path replace="replace">./format_schemas/</format_schema_path>
         <google_protos_path replace="replace">../../contrib/google-protobuf/src/</google_protos_path>
         <access_control_path replace="replace">./access/</access_control_path>
         <top_level_domains_path replace="replace">./top_level_domains/</top_level_domains_path>
     </clickhouse>
     ```

2. Run the container using `docker compose up`:
  - (Optional) If you would like a "clean slate" to work with, you can run the following:
    - **THIS WILL REMOVE ALL CONTAINERS, VOLUMES AND IMAGES YOU HAVE. USE WITH CAUTION**
      ```bash
      docker ps -a | grep -v CONTAINER | awk '{print $1}' | xargs docker rm && \
      docker images | grep -v "IMAGE ID" | awk '{print $3}' | xargs docker rmi && \
      docker volume ls | grep -v VOLUME | awk '{print $2}' | xargs docker volume rm
      ```

3. Connect to the server using `clickhouse client` (installed via Homebrew):
  - `clickhouse client --host=127.0.0.1 --port=9000 --user=default`

4. Using the client, attempt to run the following statement:
  ```sql
  CREATE USER tmp;
  ```

- Which ClickHouse server version to use
  - `version 24.12.1.263 (official build)`
- Which interface to use, if matters
  - Not Applcable
- Non-default settings, if any
  - See examples above.
- `CREATE TABLE` statements for all tables involved
  - Not Applcable
- Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
  - Not Applicable
- Queries to run that lead to unexpected result
  - See examples above.

**Expected behavior**
A user is created, that user can be used.

**Error message and/or stacktrace**
- Error from `clickhouse client`:
  ```sql
  550b46a1fa8b :) create user tmp;

  CREATE USER tmp IDENTIFIED WITH no_password

  Query id: 62dbc33b-bc4e-4c91-9070-486c62962439


  Elapsed: 0.005 sec. 

  Received exception from server (version 24.12.1):
  Code: 76. DB::Exception: Received from 127.0.0.1:9000. DB::ErrnoException. DB::ErrnoException: Cannot open file /var/lib/clickhouse/ac cess/a24bc50f-0d33-8a07-dbb1-9b6f22ea4bb2.tmp: , errno: 13, strerror: Permission denied. (CANNOT_OPEN_FILE)
  ```
- Stacktrace from server:
  ```bash
  clickhouse-server  | 2024.12.09 17:02:48.439497 [ 55 ] {62dbc33b-bc4e-4c91-9070-486c62962439} <Debug> executeQuery: (from 172.19.0.1:61338) create user tmp; (stage: Complete)
  clickhouse-server  | 2024.12.09 17:02:48.440209 [ 55 ] {62dbc33b-bc4e-4c91-9070-486c62962439} <Error> executeQuery: Code: 76. DB::ErrnoException: Cannot open file /var/lib/clickhouse/access/a24bc50f-0d33-8a07-dbb1-9b6f22ea4bb2.tmp: , errno: 13, strerror: Permission deni
  ed. (CANNOT_OPEN_FILE) (version 24.12.1.263 (official build)) (from 172.19.0.1:61338) (in query: create user tmp;), Stack trace (when copying this message, always include the lines below):
  clickhouse-server  | 
  clickhouse-server  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d38e5bb
  clickhouse-server  | 1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000082cd10c
  clickhouse-server  | 2. DB::ErrnoException::ErrnoException<String&>(int, int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000d3f0c5d
  clickhouse-server  | 3. void DB::ErrnoException::throwFromPath<String&>(int, String const&, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000d3efdc8
  clickhouse-server  | 4. DB::WriteBufferFromFile::WriteBufferFromFile(String const&, unsigned long, int, std::shared_ptr<DB::Throttler>, unsigned int, char*, unsigned long, bool, unsigned long) @ 0x000000000d53b609
  clickhouse-server  | 5. DB::DiskAccessStorage::writeAccessEntityToDisk(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, DB::IAccessEntity const&) const @ 0x0000000010705cbd
  clickhouse-server  | 6. DB::DiskAccessStorage::insertNoLock(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::shared_ptr<DB::IAccessEntity const> const&, bool, bool, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>*, bool) @ 0x000
  0000010703ffb
  clickhouse-server  | 7. DB::DiskAccessStorage::insertImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::shared_ptr<DB::IAccessEntity const> const&, bool, bool, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>*) @ 0x00000000107
  0596f
  clickhouse-server  | 8. DB::MultipleAccessStorage::insertImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::shared_ptr<DB::IAccessEntity const> const&, bool, bool, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>*) @ 0x0000000
  01076beaf
  clickhouse-server  | 9. DB::AccessControl::insertImpl(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::shared_ptr<DB::IAccessEntity const> const&, bool, bool, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>*) @ 0x0000000010684b8
  9
  clickhouse-server  | 10. DB::IAccessStorage::insert(std::vector<std::shared_ptr<DB::IAccessEntity const>, std::allocator<std::shared_ptr<DB::IAccessEntity const>>> const&, std::vector<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::allocator<StrongT
  ypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>>> const&, bool, bool) @ 0x000000001072dce0
  clickhouse-server  | 11. DB::InterpreterCreateUserQuery::execute() @ 0x0000000011e8588e
  clickhouse-server  | 12. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000011c9d666
  clickhouse-server  | 13. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000011c9879b
  clickhouse-server  | 14. DB::TCPHandler::runImpl() @ 0x0000000012ed8a7e
  clickhouse-server  | 15. DB::TCPHandler::run() @ 0x0000000012ef22b8
  clickhouse-server  | 16. Poco::Net::TCPServerConnection::start() @ 0x0000000015daa227
  clickhouse-server  | 17. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015daa6b9
  clickhouse-server  | 18. Poco::PooledThread::run() @ 0x0000000015d770fc
  clickhouse-server  | 19. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015d7569d
  clickhouse-server  | 20. ? @ 0x00007f96a3094ac3
  clickhouse-server  | 21. ? @ 0x00007f96a3126850
  ```

**Additional context**
  - Not Applicable.

**Comment by den-crane** [comment]
Why do you do this:

```
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-access:/var/lib/clickhouse/access/
```
Why it's two different mounts ?

During the start the container does `chown ... /var/lib/clickhouse/`  https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/entrypoint.sh#L81

If think in your case the `access` folder stays belong to the incorrect user because it's a mount point.

---
I don't that relative path is allowed here:

```
 <google_protos_path replace="replace">../../co
```

---

this is by default
```
      <access_management>1</access_management>
      <named_collection_control>1</named_collection_control>
      <show_named_collections>1</show_named_collections>
      <show_named_collections_secrets>1</show_named_collections_secrets>
```

---

I think it's a bad idea to replace vendor's users.xml

```
      - ./clickhouse-server/users.xml:/etc/clickhouse-server/users.xml
```

Why ?

----

**Comment by marshallm94** [comment]
@den-crane 

> This is by default:
> ```
> <access_management>1</access_management>
> <named_collection_control>1</named_collection_control>
> <show_named_collections>1</show_named_collections>
> <show_named_collections_secrets>1</show_named_collections_secrets>
> ```
> I think it's a bad idea to replace the vendors users.xml
> `      - ./clickhouse-server/users.xml:/etc/clickhouse-server/users.xml`

This is required to run `GRANT` statement on new users (https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control). When I run without this, the `GRANT` statements fail (to your credit though, a user **can** be created without that config file)

> I don't think that relative path is allowed here:
> ` <google_protos_path replace="replace">../../co`

Good catch - that was originally copied from [here](https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.d/path.xml). I trimmed it down to this:

```xml
<clickhouse>
    <access_control_path replace="replace">./access/</access_control_path>
</clickhouse>
```

> Why do you do this:
> ```
>   - clickhouse-data:/var/lib/clickhouse/
>   - clickhouse-access:/var/lib/clickhouse/access/
> ```

I think I tried that when I was in a "just throw the kitchen sink at this and see what happens" mood.

# Solved

Removing the `- clickhouse-access:/var/lib/clickhouse/access/` from the `docker-compose.yml` file seems to have solved my problem - thanks for pointing that out @den-crane!

For anyone that stumbles here (or my future dumbass self...):

- `docker-compose.yml`:
  ```yml
  services:
  clickhouse:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server@sha256:f5b4c34c3e1f6612a6dbfe9946b3f125570e79e21dc90c56a6b33151f6335df3
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      # needed for GRANT statements to work
      - ./clickhouse-server/users.xml:/etc/clickhouse-server/users.xml
      # sends logs to console aka docker logs
      - ./clickhouse-server/config.d/log-to-console.xml:/etc/clickhouse-server/config.d/log-to-console.xml
    ulimits:
      nofile:
        soft: 262144
        hard : 262144
    ports:
      # HOST_PORT:CONTAINER_PORT
      - 9000:9000

  volumes:
    clickhouse-data:
    clickhouse-logs:
  ```
- `./clickhouse-server/users.xml.yml`:
  ```yml
  <clickhouse>
    <profiles>
      <default></default>
    </profiles>

    <users>
      <default>
        <password></password>

        <networks>
            <ip>::/0</ip>
        </networks>

        <profile>default</profile>
        <quota>default</quota>

        <!-- Allows SQL-based RBAC: https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control -->
        <access_management>1</access_management>
        <named_collection_control>1</named_collection_control>
        <show_named_collections>1</show_named_collections>
        <show_named_collections_secrets>1</show_named_collections_secrets>
      </default>
    </users>
  </clickhouse>
  ```
- `./clickhouse-server/config.d/log-to-console.xml`:
  ```yml
  <clickhouse>
      <logger>
          <console>true</console>
          <log remove="remove"/>
          <errorlog remove="remove"/>
      </logger>
  </clickhouse>
  ```
