### ISSUE TITLE
Can't login with SHA256 Password

### ISSUE THREAD

**Issue by marshallm94** [ClickHouse/ClickHouse#73331]
**Company or project name**

Me (personal project).

**Describe the unexpected behaviour**
Logging into clickhouse via `clickhouse client` does not work when the user's password is stored via `<password_sha256_hex>...</password_sha256_hex>` config in `users.d/users.xml`.

**How to reproduce**

- 1. Create a test password:
  ```bash
  $ echo test | sha256sum | tr -d '-'
  f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
  ```
- 2. Put the previous hash into the `<password_sha256_hex>...</password_sha256_hex>` config:
  ```xml
  <!-- users.d/users.xml -->
  <clickhouse>
  <users>
    <clickhouse_admin>
           <password_sha256_hex>f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2</password_sha256_hex>
           <access_management>1</access_management>
           <named_collection_control>1</named_collection_control>
           <show_named_collections>1</show_named_collections>
           <show_named_collections_secrets>1</show_named_collections_secrets>
    </clickhouse_admin>
  </users>
  </clickhouse>
  ```
- 3. Run clickhouse using `docker compose up` and the following `docker-compose.yml`:

  ```yml
  services:
    clickhouse:
      container_name: clickhouse-server
      image: clickhouse/clickhouse-server@sha256:f5b4c34c3e1f6612a6dbfe9946b3f125570e79e21dc90c56a6b33151f6335df3
      volumes:
        - clickhouse-data:/var/lib/clickhouse/
        - clickhouse-logs:/var/log/clickhouse-server/
        - ./clickhouse-server/config.d/log-to-console.xml:/etc/clickhouse-server/config.d/log-to-console.xml
        - ./clickhouse-server/users.d/named-collections.xml:/etc/clickhouse-server/users.d/named-collections.xml
        - ./clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      ports:
        # HOST_PORT:CONTAINER_PORT
        - 9000:9000

  volumes:
    clickhouse-data:
    clickhouse-logs:
  ```

- 3. Attempt to login to clickhouse using `docker exec -it clickhouse-server clickhouse-client --user=clickhouse_admin`, and inputting "test" (no
     quotes) when prompted.
- 4. Observe the unexpected error message `Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: clickhouse_admin: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)`

**Expected behavior**
- I am able to login to clickhouse with the password "test"

**Error message and/or stacktrace**
- See above.

**Additional context**
- None.
