### ISSUE TITLE
Docker container failed to start when trying set `tcp_port` in config.xml

### ISSUE THREAD

**Issue by tnhgiang** [ClickHouse/ClickHouse#74199]
**Describe what's wrong**

When trying to set `tcp_port` to any numeric value, container will fail to create a new database

**Does it reproduce on the most recent release?**

Yes. This problem happens on the most recent release, specifically the version of 24.8

**Enable crash reporting**

Set `tcp_port` to any numeric value in `config.xml`

In `config.xml`
```xml
<clickhouse>
    <tcp_port>9001</tcp_port>
</clickhouse>
```

Error
```
dw-clickhouse  | /entrypoint.sh: create database 'nyc_taxi'
dw-clickhouse  | Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
```

**How to reproduce**
- ClickHouse docker image version: 24.8
- Docker compose file
```yaml
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: dw-clickhouse
    environment:
      CLICKHOUSE_DB: my_db
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: user123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
```
- `config.d/config.xml`
```xml
<clickhouse>
    <tcp_port>9001</tcp_port>
</clickhouse>
```
- Run `docker compose up`

**Expected behavior**

A ClickHouse container should successfully create a new user and database, and operate normally.

**Error message and/or stacktrace**

```
dw-clickhouse  | /entrypoint.sh: create new user 'user' instead 'default'
dw-clickhouse  | Processing configuration file '/etc/clickhouse-server/config.xml'.
dw-clickhouse  | Merging configuration file '/etc/clickhouse-server/config.d/config.xml'.
dw-clickhouse  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
dw-clickhouse  | Logging trace to /var/log/clickhouse-server/clickhouse-server.log
dw-clickhouse  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
dw-clickhouse  |
dw-clickhouse  | /entrypoint.sh: create database 'my_db'
dw-clickhouse  | Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
dw-clickhouse  |
dw-clickhouse exited with code 210
```
