### ISSUE TITLE
PVE LXC: MemoryWorker: Cannot use cgroups reader: Code: 107

### ISSUE THREAD

**Issue by xibaoning** [ClickHouse/ClickHouse#74210]
docker images:
       clickhouse/clickhouse-server   head-alpine   9f5a241480e3
docker:~# docker info
Client:
 Version:    26.1.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 26.1.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc version: 2c9f5602f0ba3d9da1c2596322dfc4e156844890
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-5-pve
 Operating System: Alpine Linux v3.21
 OSType: linux
 Architecture: x86_64
 CPUs: 14
 Total Memory: 32GiB
 Name: docker
 ID: ad4de2b6-3c49-4d72-a499-cbed2c070cd9
 Docker Root Dir: /data/docker-data
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.1ms.run/
 Live Restore Enabled: false

WARNING: No swap limit support

/////////////////////////////////////////////////////////////////////////////////////////////
clickhouse-server.err.log

2025.01.06 16:30:58.507837 [ 1 ] {} <Error> MemoryWorker: Cannot use cgroups reader: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d877fdb
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000086fe62c
2. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x000000000870b6ab
3. DB::MemoryWorker::MemoryWorker(unsigned long) @ 0x000000000d9b954d
4. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000db053db
5. Poco::Util::Application::run() @ 0x0000000016c72dc6
6. DB::Server::run() @ 0x000000000db00b70
7. mainEntryClickHouseServer(int, char**) @ 0x000000000dafdaf3
8. main @ 0x00000000086fa941
9. ? @ 0x000070196a2ead90
10. ? @ 0x000070196a2eae40
11. _start @ 0x000000000668802e
 (version 25.1.1.1881 (official build))

**Comment by hanfei1991** [comment]
AFAIK docker uses cgroup file from the host. Maybe your server does not contain cgroup files

**Comment by xibaoning** [comment]
thanks, worked, map "/sys/fs/cgroup"  
```yml
services:
  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    container_name: clickhouse
    restart: always
    privileged: true
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - /data/clickhouse-server/config.xml:/etc/clickhouse-server/config.xml:rw
      - /data/clickhouse-server/users.xml:/etc/clickhouse-server/users.xml:rw
      - /data/clickhouse-server/log:/var/log/clickhouse-server
      - data:/var/lib/clickhouse:rw
      - /sys/fs/cgroup:/sys/fs/cgroup   #map
volumes:
  data:
```
