### ISSUE TITLE
Prevent docker image from creating user

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#74775]
### Describe the unexpected behaviour

When passing CLICKHOUSE_USER and CLICKHOUSE_PASSWORD as envs to docker container it creates that user as default in users.d directory. Would be nice to skip that step during run container. I want to have envs to clickhouse-client but that user is managed by access_control_path

### How to reproduce

Tested with 24.8.11 tag but it is not related with any version because it is intentional basing on image description https://hub.docker.com/_/clickhouse

**Comment by rkozlo** [comment]
In entrypoint i can see such condition
```[ -n "$CLICKHOUSE_USER" ] && [ "$CLICKHOUSE_USER" != "default" ] || [ -n "$CLICKHOUSE_PASSWORD" ] || [ "$CLICKHOUSE_ACCESS_MANAGEMENT" != "0" ];```
so there is no env currently to skip creating xml with user

**Comment by geldot** [comment]
You can skip `entrypoint.sh` by overriding the entrypoint and just invoking clickhouse directly with something like the below, as the plan is to remove this script (see #73949). This will also avoid various problematic directory creation and permissions changes that can damage the database.

```yaml
services:
  clickhouse:
    environment:
      - CLICKHOUSE_WATCHDOG_ENABLE=0
    entrypoint: []
    command: clickhouse-server
```
