### ISSUE TITLE
How to increase default body max size http_max_field_value_size?

### ISSUE THREAD

**Issue by petehouston** [ClickHouse/ClickHouse#75958]
### Question

I'm trying to change this config but it doesn't work.

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
  namespace: "datastore"
spec:
#  troubleshoot: "yes"
  configuration:
    profiles:
      default/http_max_field_value_size: "100000000"
    users:
      admin/networks/ip: "::/0"
      admin/password: SecretDontTellXXX
      admin/profile: default
```

I'm having the issue form this ClickHouse issue and want to increase the size: https://github.com/ClickHouse/ClickHouse/issues/36783#issuecomment-2580058747

Anyone know how to set it?
