### ISSUE TITLE
DEFINER user's settings should take precedence over default profile settings

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#76186]
Suppose a setting is explicitly set to different values in `default` profile and some user's profile:
```yaml
profiles:
  default:
    max_block_size: 4321
  profile2:
    max_block_size: 1234
users:                                                                                                                                                                                                                                                                                
  default:                                                                                                                                                                                                                                                                            
    password:                                                                                                                                                                                                                                                                         
  user2:                                                                                                                                                                                                                                                                              
    password:                                                                                                                                                                                                                                                                         
    profile: profile2
```
Then refreshable MV (and probably regular MV too) uses the value from default profile instead of DEFINER's profile:
```sql
:) create materialized view a refresh every 1 second (x Int64) engine Memory definer user2 sql security definer as select max(blockSize()) as x from numbers(10000)
...
:) select * from a

SELECT *
FROM a

Query id: 86f00a9c-f604-498d-a0f8-2922341e994e

   ┌────x─┐
1. │ 4321 │
   └──────┘

1 row in set. Elapsed: 0.001 sec.
```
In contrast, if we remove the setting from default profile:
```yaml
profiles:
  default:
  profile2:
    max_block_size: 1234
```
then the value from DEFINER's profile is used:
```sql
:) select * from a

SELECT *
FROM a

Query id: 739bdead-5b1c-4f56-a97f-fbe204e6f826

   ┌────x─┐
1. │ 1234 │
   └──────┘

1 row in set. Elapsed: 0.001 sec.
```

The value from DEFINER's profile should take precedence over the default profile.

---

The problem is that `StorageInMemoryMetadata::getSQLSecurityOverriddenContext` re-applies "changed" settings from current context after applying settings from DEFINER's profile. But the default profile's settings are marked as changed (from their default values), so they get reapplied and override DEFINER's settings. I'm not sure how to fix this well, there doesn't seem to be an easy way to tell whether a setting is "changed" only because of default profile (shouldn't be reapplied) or also changed in some other higher-priority way (should be reapplied).
