### ISSUE TITLE
Refreshable Materialized views don't work when running with a shared volume in docker compose in Mac

### ISSUE THREAD

**Issue by xocasdashdash** [ClickHouse/ClickHouse#76653]
### Company or project name

Paddle - Testing out clickhouse

### Describe the unexpected behaviour

I'm exploring refreshable materialized views ([here](https://clickhouse.com/docs/materialized-view/refreshable-materialized-view)) for some logging application i'm building. 

When running with a shared volume in docker desktop in osx i've hit an issue when it's replacing the table:

```
lickhouse-1  | 2025.02.23 13:18:37.404414 [ 826 ] {aa8f0cc6-cfe9-4c79-a32a-28dc4aee89c3} <Warning> DatabaseAtomic (default): std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directory_symlink: File exists ["/var/lib/clickhouse/store/12a/12a382b1-5613-4745-bbfc-d190e75b4f4b"] ["/var/lib/clickhouse/data/default/%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef"], Stack trace (when copying this message, always include the lines below):
clickhouse-1  |
clickhouse-1  | 0. std::system_error::system_error(std::error_code, String const&) @ 0x0000000016dfa17c
clickhouse-1  | 1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:ne180100](String const&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000016db50d0
clickhouse-1  | 2. void std::__fs::filesystem::__throw_filesystem_error[abi:ne180100]<String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000016db4e04
clickhouse-1  | 3. std::__fs::filesystem::detail::ErrorHandler<void>::report(std::error_code const&) const @ 0x0000000016db31b8
clickhouse-1  | 4. std::__fs::filesystem::__create_directory_symlink(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000016db8b28
clickhouse-1  | 5. DB::DiskLocal::createDirectoriesSymlink(String const&, String const&) @ 0x00000000101ff60c
clickhouse-1  | 6. DB::DatabaseAtomic::tryCreateSymlink(std::shared_ptr<DB::IStorage> const&, bool) @ 0x00000000100cc060
clickhouse-1  | 7. DB::DatabaseAtomic::renameTable(std::shared_ptr<DB::Context const>, String const&, DB::IDatabase&, String const&, bool, bool) @ 0x00000000100ca6ec
clickhouse-1  | 8. DB::InterpreterRenameQuery::execute() @ 0x0000000010ab0888
clickhouse-1  | 9. DB::InterpreterCreateQuery::doCreateOrReplaceTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, DB::LoadingStrictnessLevel) @ 0x00000000108ae2e8
clickhouse-1  | 10. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x00000000108a8db4
clickhouse-1  | 11. DB::InterpreterCreateQuery::execute() @ 0x00000000108b8460
clickhouse-1  | 12. DB::StorageMaterializedView::prepareRefresh(bool, std::shared_ptr<DB::Context>, std::optional<DB::StorageID>&) const @ 0x00000000113d6124
clickhouse-1  | 13. DB::RefreshTask::refreshTask() @ 0x0000000011d77404
clickhouse-1  | 14. DB::BackgroundSchedulePool::threadFunction() @ 0x000000000fce9070
clickhouse-1  | 15. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne180100]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000fcea78c
clickhouse-1  | 16. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000c6638a0
clickhouse-1  | 17. void* std::__thread_proxy[abi:ne180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000c66a0dc
clickhouse-1  | 18. ? @ 0x000000000007d5c8
clickhouse-1  | 19. ? @ 0x00000000000e5edc
clickhouse-1  |
clickhouse-1  | Cannot print extra info for Poco::Exception (version 25.1.5.31 (official build))
clickhouse-1  | 2025.02.23 13:18:39.112143 [ 826 ] {aa8f0cc6-cfe9-4c79-a32a-28dc4aee89c3} <Error> StorageMaterializedView: Failed to drop temporary table after refresh: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/fcb/fcb1db24-3af9-4c3a-b70a-401a392e1dd6/%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.sql"] ["/var/lib/clickhouse/metadata_dropped/default.%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.0cde3eb1-31c8-4800-a7c6-06f46f6bd897.sql"], Stack trace (when copying this message, always include the lines below):
clickhouse-1  |
clickhouse-1  | 0. std::system_error::system_error(std::error_code, String const&) @ 0x0000000016dfa17c
clickhouse-1  | 1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:ne180100](String const&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000016db50d0
clickhouse-1  | 2. void std::__fs::filesystem::__throw_filesystem_error[abi:ne180100]<String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000016db4e04
clickhouse-1  | 3. std::__fs::filesystem::detail::ErrorHandler<void>::report(std::error_code const&) const @ 0x0000000016db31b8
clickhouse-1  | 4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000016dba468
clickhouse-1  | 5. DB::DiskLocal::replaceFile(String const&, String const&) @ 0x00000000101fb8fc
clickhouse-1  | 6. DB::DatabaseAtomic::dropTableImpl(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c9304
clickhouse-1  | 7. DB::DatabaseAtomic::dropTable(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c8c80
clickhouse-1  | 8. DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x00000000108c743c
clickhouse-1  | 9. DB::InterpreterDropQuery::execute() @ 0x00000000108c29bc
clickhouse-1  | 10. DB::StorageMaterializedView::dropTempTable(DB::StorageID, std::shared_ptr<DB::Context>) @ 0x00000000113d83ac
clickhouse-1  | 11. DB::RefreshTask::refreshTask() @ 0x0000000011d77cb8
clickhouse-1  | 12. DB::BackgroundSchedulePool::threadFunction() @ 0x000000000fce9070
clickhouse-1  | 13. void std::__function::__policy_invoker<void ()>::__call_impl[abi:ne180100]<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000fcea78c
clickhouse-1  | 14. ThreadPoolImpl<std::thread>::ThreadFromThreadPool::worker() @ 0x000000000c6638a0
clickhouse-1  | 15. void* std::__thread_proxy[abi:ne180100]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000000c66a0dc
clickhouse-1  | 16. ? @ 0x000000000007d5c8
clickhouse-1  | 17. ? @ 0x00000000000e5edc
clickhouse-1  |
clickhouse-1  | Cannot print extra info for Poco::Exception (version 25.1.5.31 (official build))
clickhouse-1  | 2025.02.23 13:19:35.173904 [ 813 ] {8dd134f2-41c9-4fa6-beb4-37b6072b3489} <Error> executeQuery: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/fcb/fcb1db24-3af9-4c3a-b70a-401a392e1dd6/%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.sql"] ["/var/lib/clickhouse/metadata_dropped/default.%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.0cde3eb1-31c8-4800-a7c6-06f46f6bd897.sql"]
clickhouse-1  | Cannot print extra info for Poco::Exception (version 25.1.5.31 (official build)) (from 172.18.0.1:63262) (query 1, line 1) (in query: drop table `.tmp.inner_id.27b1f75f-a685-4bda-a08a-56de179bbdef`), Stack trace (when copying this message, always include the lines below):
clickhouse-1  |
clickhouse-1  | 0. std::system_error::system_error(std::error_code, String const&) @ 0x0000000016dfa17c
clickhouse-1  | 1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:ne180100](String const&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000016db50d0
clickhouse-1  | 2. void std::__fs::filesystem::__throw_filesystem_error[abi:ne180100]<String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000016db4e04
clickhouse-1  | 3. std::__fs::filesystem::detail::ErrorHandler<void>::report(std::error_code const&) const @ 0x0000000016db31b8
clickhouse-1  | 4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000016dba468
clickhouse-1  | 5. DB::DiskLocal::replaceFile(String const&, String const&) @ 0x00000000101fb8fc
clickhouse-1  | 6. DB::DatabaseAtomic::dropTableImpl(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c9304
clickhouse-1  | 7. DB::DatabaseAtomic::dropTable(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c8c80
clickhouse-1  | 8. DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x00000000108c743c
clickhouse-1  | 9. DB::InterpreterDropQuery::execute() @ 0x00000000108c29bc
clickhouse-1  | 10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010dfd658
clickhouse-1  | 11. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000010df9c0c
clickhouse-1  | 12. DB::TCPHandler::runImpl() @ 0x0000000011ecf6a4
clickhouse-1  | 13. DB::TCPHandler::run() @ 0x0000000011eea308
clickhouse-1  | 14. Poco::Net::TCPServerConnection::start() @ 0x0000000014da66f8
clickhouse-1  | 15. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014da6c14
clickhouse-1  | 16. Poco::PooledThread::run() @ 0x0000000014d71e1c
clickhouse-1  | 17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d701f0
clickhouse-1  | 18. ? @ 0x000000000007d5c8
clickhouse-1  | 19. ? @ 0x00000000000e5edc
clickhouse-1  |
clickhouse-1  | 2025.02.23 13:19:35.175913 [ 813 ] {} <Error> TCPHandler: Code: 1001. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/fcb/fcb1db24-3af9-4c3a-b70a-401a392e1dd6/%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.sql"] ["/var/lib/clickhouse/metadata_dropped/default.%2Etmp%2Einner_id%2E27b1f75f%2Da685%2D4bda%2Da08a%2D56de179bbdef.0cde3eb1-31c8-4800-a7c6-06f46f6bd897.sql"]. (STD_EXCEPTION), Stack trace (when copying this message, always include the lines below):
clickhouse-1  |
clickhouse-1  | 0. std::system_error::system_error(std::error_code, String const&) @ 0x0000000016dfa17c
clickhouse-1  | 1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:ne180100](String const&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000016db50d0
clickhouse-1  | 2. void std::__fs::filesystem::__throw_filesystem_error[abi:ne180100]<String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x0000000016db4e04
clickhouse-1  | 3. std::__fs::filesystem::detail::ErrorHandler<void>::report(std::error_code const&) const @ 0x0000000016db31b8
clickhouse-1  | 4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000016dba468
clickhouse-1  | 5. DB::DiskLocal::replaceFile(String const&, String const&) @ 0x00000000101fb8fc
clickhouse-1  | 6. DB::DatabaseAtomic::dropTableImpl(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c9304
clickhouse-1  | 7. DB::DatabaseAtomic::dropTable(std::shared_ptr<DB::Context const>, String const&, bool) @ 0x00000000100c8c80
clickhouse-1  | 8. DB::InterpreterDropQuery::executeToTableImpl(std::shared_ptr<DB::Context const> const&, DB::ASTDropQuery&, std::shared_ptr<DB::IDatabase>&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>&) @ 0x00000000108c743c
clickhouse-1  | 9. DB::InterpreterDropQuery::execute() @ 0x00000000108c29bc
clickhouse-1  | 10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x0000000010dfd658
clickhouse-1  | 11. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000010df9c0c
clickhouse-1  | 12. DB::TCPHandler::runImpl() @ 0x0000000011ecf6a4
clickhouse-1  | 13. DB::TCPHandler::run() @ 0x0000000011eea308
clickhouse-1  | 14. Poco::Net::TCPServerConnection::start() @ 0x0000000014da66f8
clickhouse-1  | 15. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014da6c14
clickhouse-1  | 16. Poco::PooledThread::run() @ 0x0000000014d71e1c
clickhouse-1  | 17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d701f0
clickhouse-1  | 18. ? @ 0x000000000007d5c8
clickhouse-1  | 19. ? @ 0x00000000000e5edc
clickhouse-1  |
```

This is the docker-compose.yaml file:

```yaml
clickhouse:
    image: clickhouse-local
    build:
      context: .
      dockerfile_inline: |
        FROM clickhouse/clickhouse-server:latest
        RUN mkdir -p /etc/clickhouse-server/certs
        COPY ./certs/clickhouse.paddle.local/* /etc/clickhouse-server/certs/
        RUN chown clickhouse:clickhouse -R /etc/clickhouse-server/certs
        RUN chmod 600 /etc/clickhouse-server/certs/*
        RUN chmod 755 /etc/clickhouse-server/certs
        RUN ls -laht /etc/clickhouse-server/certs
    ports:
      - "9000:9000" # Clickhouse native port
      - "9440:9440" # Clickhouse native secure port
      - "8123:8123" # Clickhouse HTTP port
      - "18443:8443" # Clickhouse HTTPs port
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse # Persist data
      - ./logs/clickhouse-main:/var/log/clickhouse-server/
      - ./scripts/clickhouse/sql:/docker-entrypoint-initdb.d/ # Run SQL script on startup
      - ./clickhouse/config:/etc/clickhouse-server/config.d # Mount all the config files
```

Basically i think that the way osx sets up file sharing don't work with how clickhouse deletes a table. 

I've managed to reproduce the issue by creating a simple table:

```
CREATE TABLE IF NOT EXISTS geoip
(
	`cidr` String,
	`latitude` Float64,
	`longitude` Float64,
	`country_code` String
)
ENGINE = MergeTree
ORDER BY cidr;
```

and then running this:
```
CREATE OR REPLACE TABLE geoip
(
	`cidr` String,
	`latitude` Float64,
	`longitude` Float64,
	`country_code` String
)
ENGINE = MergeTree
ORDER BY cidr;
```

With this output in clickhouse client:
```
Received exception from server (version 25.1.5):
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/fcb/fcb1db24-3af9-4c3a-b70a-401a392e1dd6/_tmp_replace_33b24c4def9a5714_iqakeksk2eecb82a.sql"] ["/var/lib/clickhouse/metadata_dropped/default._tmp_replace_33b24c4def9a5714_iqakeksk2eecb82a.12a382b1-5613-4745-bbfc-d190e75b4f4b.sql"]. (STD_EXCEPTION)
```

Once i remove the volume mount, everything works as expected

### How to reproduce

create a docker-compose.yaml file with the following:
```yaml
services:
  clickhouse:
    image: clickhouse-local
    build:
      context: .
      dockerfile_inline: |
        FROM clickhouse/clickhouse-server:latest
        RUN mkdir -p /etc/clickhouse-server/certs
        COPY ./certs/clickhouse.paddle.local/* /etc/clickhouse-server/certs/
        RUN chown clickhouse:clickhouse -R /etc/clickhouse-server/certs
        RUN chmod 600 /etc/clickhouse-server/certs/*
        RUN chmod 755 /etc/clickhouse-server/certs
        RUN ls -laht /etc/clickhouse-server/certs
    ports:
      - "9000:9000" # Clickhouse native port
      - "9440:9440" # Clickhouse native secure port
      - "8123:8123" # Clickhouse HTTP port
      - "18443:8443" # Clickhouse HTTPs port
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse # Persist data
      - ./logs/clickhouse-main:/var/log/clickhouse-server/
      - ./scripts/clickhouse/sql:/docker-entrypoint-initdb.d/ # Run SQL script on startup
      - ./clickhouse/config:/etc/clickhouse-server/config.d # Mount all the config files
```

Have a script in `./scripts/clickhouse/sql` that creates a table like this:

```

CREATE TABLE IF NOT EXISTS geoip
(
	`cidr` String,
	`latitude` Float64,
	`longitude` Float64,
	`country_code` String
)
ENGINE = MergeTree
ORDER BY cidr;

```

Connect with clickhouse-client and run this:
```

CREATE OR REPLACE TABLE geoip
(
	`cidr` String,
	`latitude` Float64,
	`longitude` Float64,
	`country_code` String
)
ENGINE = MergeTree
ORDER BY cidr;

```

### Error message and/or stacktrace

Logs are here https://gist.github.com/xocasdashdash/2a3fcd42dadf508dd93d8dc7d68b94eb
