### ISSUE TITLE
ReplacingMergeTree does not work in Docker image

### ISSUE THREAD

**Issue by enzoferey** [ClickHouse/ClickHouse#77188]
### Company or project name

https://www.getcargo.io/

### Describe the unexpected behaviour

Hi !

The `ReplacingMergeTree` engine does not seem to work on my local machine while it does in the machines of my teammates. When querying records on a table multiple records are being returned 

I'm on M1 Pro chip + Sequoia 15.3.1.

### How to reproduce

We have added the ClickHouse image on our Docker compose file as following:

```
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: cargo-clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
```

And then created a table like this:

```
create table orchestration.runs (
        uuid UUID,
        workspace_uuid UUID,
        workflow_uuid UUID,
        batch_uuid UUID,
        release_uuid UUID,
        temporal_workflow_id UUID,
        record_id String,
        context_s3_filename String,
        error_message Nullable(String),
        finished_at Nullable(DateTime64),
        executions Nested (
          node_uuid UUID,
          node_slug String,
          node_kind Enum(
            'native',
            'connector',
            'tool'
          ),
          node_action_slug String,
          node_connector_uuid Nullable(UUID),
          node_integration_slug Nullable(String),
          node_tool_uuid Nullable(UUID),
          node_release_uuid Nullable(UUID),
          node_batch_uuid Nullable(UUID),
          node_child_index Nullable(Int32),
          next_node_uuid Nullable(UUID),
          status Enum(
            'error',
            'pending',
            'success'
          ),
          error_message Nullable(String),
          title Nullable(String),
          icon_url Nullable(String),
          credits_used_count Float32
        ),
        status Enum(
          'error',
          'pending',
          'skipped',
          'running',
          'success',
          'cancelled', 
          'idle'
        ),
        created_at DateTime64,
        updated_at DateTime64,
        computed_configs_s3_filename String,
        record_title String,
        deleted_at Nullable(DateTime64),
        group Tuple(
          batch_uuid Nullable(UUID),
          run_uuid Nullable(UUID),
          node_uuid Nullable(UUID)
        )
      )
      engine = ReplacingMergeTree(updated_at)
      order by (workspace_uuid, workflow_uuid, batch_uuid, uuid, created_at)
```

### Expected behavior

Get records properly merged.
