### ISSUE TITLE
Segmentation fault when querying table with SET index and WHERE 0 = 1 (ClickHouse 25.4.3.22)

### ISSUE THREAD

**Issue by Schum-io** [ClickHouse/ClickHouse#80598]
### Company or project name

Environment
	•	ClickHouse version: 25.4.3.22
	•	OS: Ubuntu 22.04 LTS (Linux)

### Describe what's wrong

ClickHouse crashes with a segmentation fault when executing a simple SELECT on a table that has a SET‐type index defined, combined with a WHERE clause that always evaluates to false. Removing the index or changing the WHERE clause prevents the crash.

### Does it reproduce on the most recent release?

Yes

### How to reproduce

Reproduction steps

1. Create a table with a SET index on fail_column_id:
```sql
CREATE TABLE default.sample_table
(
    `started_datetime` DateTime,
    `id` String,
    `fail_column_id` String,
    `participants.player_id` Array(String),
    INDEX IdxLeagueID fail_column_id TYPE set(1500) GRANULARITY 1
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(started_datetime)
ORDER BY (id, started_datetime)
SETTINGS index_granularity = 8192;
```

2. Insert sample data:
```sql
INSERT INTO default.sample_table VALUES
    (now(), 'id1', 'fail_column_id1', ['player_id1']),
    (now(), 'id2', 'fail_column_id2', ['player_id2']),
    (now(), 'id3', 'fail_column_id3', ['player_id3']);
```
3. Create a dictionary so that the DDL above matches your production setup:
```sql
CREATE TABLE default.sample_dict__src
(
    id         UInt64,
    `group`    String,
    date_start Date,
    date_end   Date
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO default.sample_dict__src VALUES
    (1, 'clickhouse', now(), toDate(now()) + 1);

CREATE DICTIONARY default.sample__dict
(
    id         UInt64,
    `group`    String,
    date_start Date,
    date_end   Date
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' DB 'default' USER 'default' PORT 9000 TABLE 'sample_dict__src'))
LIFETIME(MIN 2700 MAX 3600)
LAYOUT(COMPLEX_KEY_RANGE_HASHED())
RANGE(MIN date_start MAX date_end);
```

4. Run the problematic query:
```sql
SELECT *
FROM (
    WITH
        1 AS Period,
        toDate(started_datetime) AS Day
    SELECT
        id,
        P.player_id AS pid
        ,dictGet(
            'default.sample__dict',
            'group',
             pid,
            Day
        ) AS group_value
    FROM default.sample_table
    ARRAY JOIN participants AS P
    WHERE
         started_datetime >= today() - INTERVAL Period DAY
) AS reproducible
WHERE 0 = 1
```

### Expected behavior

The query should simply return zero rows without crashing the server.

### Error message and/or stacktrace

Received signal Segmentation fault (11)
[clickhouse-1-4] 2025.05.20 14:28:18.665724 [ 693829 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
[...]
DB::ActionsDAG::removeUnusedActions(std::unordered_set<DB::ActionsDAG::Node const*> const&, bool) @ 0x00000000128361b6
DB::MergeTreeIndexSet::createIndexCondition(DB::ActionsDAG const*, std::shared_ptr<DB::Context const>) const @ 0x000000001437222f
DB::buildIndexes(...) @ 0x0000000014ead4bb
DB::ReadFromMergeTree::applyFilters(DB::ActionDAGNodes) @ 0x0000000014eac042
[...]

### Additional context

	•	Dropping the SET index (i.e. removing the INDEX IdxLeagueID ... TYPE set) makes the crash go away.
	•	Changing or removing the WHERE 0 = 1 clause also prevents the crash.

**Comment by Schum-io** [comment]
A segmentation fault occurs when setting <enable_analyzer>0</enable_analyzer> in the configuration, or when using SETTINGS enable_analyzer = 0 in a query.

my docker compose file:
```yaml
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.4.3.22
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./config:/etc/clickhouse-server
      - ./logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
      - "9009:9009"   # Interserver HTTP
    networks:
      - clickhouse-net

networks:
  clickhouse-net:
    driver: bridge
```
