### ISSUE TITLE
Performance Regression After ClickHouse Upgrade (24.3 → 25.5)

### ISSUE THREAD

**Issue by granescb** [ClickHouse/ClickHouse#82506]
### Company or project name

Improvado

## Overview
We're experiencing performance issues after upgrading from ClickHouse 24.3 to 25.5. Performance degradation began in version 24.6 and persists in 25.5.

## Our case
1. Create temporary MergeTree and Memory tables  
2. Insert data from a `.gz` file into the temporary MergeTree table  
3. Analyze data from the MergeTree table via select
4. Insert some analysis data intothe  Memory table
5. Insert processed data into the main partitioned table 
6. Delete temporary tables 

## Observed Behavior
- **Thread utilization**:  
  - Version 24.3 efficiently uses all 24 CPU cores  
  - Version 25.5 fails to utilize available 24 CPU cores fully  
  - The same behavior with performance degradation using the `max_threads = 1` setting
- **Thread metrics**:  
  - `GlobalThread` from `system.metric_log` was divided twice in the new version. 
  - `peak_threads_usage` in `system.query_log` shows inconsistent values for identical queries (21(25.5) vs 38(24.3))  
- **Visual evidence**: 
Here is the screenshot of the visualization of some Clickhouse metrics (left part - 25.5, right part 24.3)
![Image](https://github.com/user-attachments/assets/c56e1cfc-7287-47a0-b4e1-57fa5eab4303)

## Attempted Fixes
The following settings were applied without resolving the issues:

### Session Settings
```
default/move_all_conditions_to_prewhere: "0"
default/enable_multiple_prewhere_read_steps: "0"
default/move_primary_key_columns_to_end_of_prewhere: "0"
default/allow_experimental_analyzer: "0"
default/enable_analyzer: "0"
```

### Server Settings
```
cgroups_memory_usage_observer_wait_time: "0"
async_load_databases: "0"
```

### Log settings
```
  <clickhouse>
    <asynchronous_metric_log remove="1"/>
    <query_thread_log remove="1"/>
    <query_views_log remove="1"/>
    <metric_log remove="1"/>
    <session_log remove="1"/>
    <part_log remove="1"/>
    <text_log remove="1"/>
    <trace_log remove="1"/>
    <processors_profile_log remove="1"/>
  </clickhouse>
```

### Which ClickHouse versions are affected?

24.3-25.5

### How to reproduce

We tried to reproduce it locally with the same sample of data, but it's reproducing only in the production environment.

### Expected performance

We expect the same performance for 25.5 as it was for 24.3 or better.

## Context
These settings are configured via our `ClickhouseInstallation` resources.

```
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse-staging
  namespace: clickhouse-staging
spec:
  configuration:
    files:
      config.d/user_directories.xml: |
        <?xml version="1.0"?>
        <clickhouse>
          <user_directories replace="replace">
            <users_xml>
              <path>/etc/clickhouse-server/users.xml</path>
            </users_xml>
            <replicated>
              <zookeeper_path>/clickhouse/access/</zookeeper_path>
            </replicated>
            <local_directory>
              <path>/var/lib/clickhouse/access/</path>
            </local_directory>
          </user_directories>
        </clickhouse>
    clusters:
      - name: storage
        secret:
          valueFrom:
            secretKeyRef:
              name: "clickhouse-main-distributed-secret"
              key: "secret"
        layout:
          shards:
            - replicasCount: 1
        templates:
          podTemplate: storage-pod
          volumeClaimTemplate: ch-staging
          serviceTemplate: storage-svc
        settings:
          max_server_memory_usage: "300000000000"
    profiles:
      default/max_distributed_connections: "6144"
      default/distributed_connections_pool_size: "6144"
      default/allow_deprecated_database_ordinary: "1"
      default/timeout_before_checking_execution_speed: "1800"
      default/output_format_parquet_compression_method: snappy
      default/output_format_parquet_version: "1.0"
      default/aggregation_memory_efficient_merge_threads: "4"
      default/distributed_aggregation_memory_efficient: "1"
      default/input_format_defaults_for_omitted_fields: "1"
      default/input_format_null_as_default: "1"
      default/input_format_skip_unknown_fields: "1"
      default/max_alter_threads: "8"
      default/max_bytes_before_external_group_by: "10000000000"
      default/max_execution_time: "7200"
      default/max_memory_usage: "75161927680"
      default/max_partitions_per_insert_block: "0"
      default/format_csv_allow_single_quotes: "0"
      default/optimize_on_insert: "0"
      default/queue_max_wait_ms: "600000"
      default/local_filesystem_read_method: "pread"
      default/max_query_size: "10485760"
      default/insert_quorum: "2"
      default/select_sequential_consistency: "0"
      default/insert_quorum_parallel: "1"
      default/database_replicated_allow_replicated_engine_arguments: "1"
      default/move_all_conditions_to_prewhere: "0"
      default/enable_multiple_prewhere_read_steps: "0"
      default/move_primary_key_columns_to_end_of_prewhere: "0"
      default/allow_experimental_analyzer: "0"
    settings:
      async_load_databases: "0"
      max_table_size_to_drop: "0"
      max_partition_size_to_drop: "0"
      compression/case/method: zstd
      logger/level: information
      logger/log: /var/lib/clickhouse/logs/clickhouse-server.log
      logger/errorlog: /var/lib/clickhouse/logs/clickhouse-server.err.log
      max_concurrent_queries: "200"
      prometheus/asynchronous_metrics: "true"
      prometheus/endpoint: /metrics
      prometheus/events: "true"
      prometheus/metrics: "true"
      prometheus/port: "8001"
      access_control/zookeeper_path: /clickhouse/access/
      max_connections: "6144"
      query_log/engine: "ENGINE = MergeTree PARTITION BY toMonday(event_date) ORDER BY (event_time) TTL event_date + INTERVAL 60 DAY"
      part_log/engine: "ENGINE = MergeTree PARTITION BY (event_date) ORDER BY (event_time) TTL event_date + INTERVAL 30 DAY"
      trace_log/engine: "ENGINE = MergeTree PARTITION BY (event_date) ORDER BY (event_time) TTL event_date + INTERVAL 30 DAY"
      asynchronous_insert_log/partition_by: "event_date"
      asynchronous_insert_log/ttl: "event_date + INTERVAL 3 DAY"
      asynchronous_metric_log/partition_by: "toMonday(event_date)"
      asynchronous_metric_log/ttl: "event_date + INTERVAL 14 DAY"
      backup_log/ttl: "event_date + INTERVAL 365 DAY"
      blob_storage_log/partition_by: "toMonday(event_date)"
      blob_storage_log/ttl: "event_date + INTERVAL 30 DAY"
      crash_log/ttl: "event_date + INTERVAL 365 DAY"
      metric_log/partition_by: "toYYYYMM(event_date)"
      metric_log/ttl: "event_date + INTERVAL 30 DAY"
      processors_profile_log/partition_by: "toMonday(event_date)"
      processors_profile_log/ttl: "event_date + INTERVAL 30 DAY"
      query_views_log/partition_by: "toYYYYMM(event_date)"
      query_views_log/ttl: "event_date + INTERVAL 30 DAY"
      session_log/partition_by: "toYYYYMM(event_date)"
      session_log/ttl: "event_date + INTERVAL 365 DAY"
    users:
      default/access_management: 1
      default/named_collection_control: 1
      default/show_named_collections: 1
      default/show_named_collections_secrets: 1
      default/password: _removed_
      default/password_sha256_hex: <some_hex>
      default/profile: default
      default/quota: default
    zookeeper:
      nodes:
        - host: chk-ch-keeper-staging-main-0-0.clickhouse-staging.svc
          port: 2181
  stop: "false"
  defaults:
    templates:
      dataVolumeClaimTemplate: ch-staging
      podTemplate: storage-pod
      shardServiceTemplate: shard-svc
  templates:
    podTemplates:
      - name: storage-pod
        podDistribution:
          - type: ShardAntiAffinity
        metadata:
          labels:
            app.improvado.io/podmonitor: clickhouse
          annotations:
            karpenter.sh/do-not-disrupt: "true"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
            topology.ebs.csi.aws.com/zone: us-east-1b
            karpenter.sh/capacity-type: on-demand
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.5.1.2782
              command:
                - /usr/bin/clickhouse-server
                - --config-file=/etc/clickhouse-server/config.xml
              ports:
                - containerPort: 8123
                  name: clickhouse-http
                - containerPort: 8001
                  name: metrics-http
                - containerPort: 9000
                  name: clickhouse-tcp
              startupProbe:
                failureThreshold: 100
                httpGet:
                  path: /ping
                  port: clickhouse-http
                initialDelaySeconds: 60
                periodSeconds: 60
              livenessProbe:
                failureThreshold: 30
                httpGet:
                  path: /ping
                  port: clickhouse-http
                initialDelaySeconds: 60
                periodSeconds: 60
              resources:
                requests:
                  cpu: "24"
                  memory: 256Gi
                limits:
                  cpu: "24"
                  memory: 256Gi
              volumeMounts:
                - name: dsas-efs
                  mountPath: /var/lib/clickhouse/user_files
                  subPath: store
          volumes:
            - name: dsas-efs
              persistentVolumeClaim:
                claimName: dsas-efs-for-clickhouse-staging
    volumeClaimTemplates:
      - name: default
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: ch-staging
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: gp3
    serviceTemplates:
      - name: storage-svc
        generateName: "{chi}"
        metadata:
          labels:
            clickhouse.altinity.com/Service: chi
            clickhouse.altinity.com/app: chop
            clickhouse.altinity.com/chi: clickhouse-staging
            clickhouse.altinity.com/namespace: clickhouse
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP
      - name: shard-svc
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
```

This is query_log result with the performance result

[25.5_queries.csv](https://github.com/user-attachments/files/20868373/25.5_queries.csv)
[24.3_queries.csv](https://github.com/user-attachments/files/20868374/24.3_queries.csv)

This is a comparison of queries with SETTINGS `max_threads = 1`. Even with 1 thread, we still have difference in performance between versions

[25.5-24.3_compare_1_thread.csv](https://github.com/user-attachments/files/20868385/25.5-24.3_compare_1_thread.csv)
