### ISSUE TITLE
Clickhouse in docker at debian 9 startup fail

### ISSUE THREAD

**Issue by deadstar2011** [ClickHouse/ClickHouse#9837]
**Describe the bug**
Hi. Try to use docker image yandex/clickhouse-server:20.1 with docker-compose file:

```
version: "3.7"
services:
  clickhouse:
    image: yandex/clickhouse-server:20.1
    ports:
      - "9000:9000"
    volumes:
      - "../_data/clickhouse/:/var/lib/clickhouse"
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml"
```

and get startup error:

docker logs develop_clickhouse_1
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.

Thats only on debian9 server. At ubuntu 16.04 and 19.10 same compose file works fine.

Error drops at entrypoint.sh:
```
LOG_PATH="$(clickhouse extract-from-config --config-file $CLICKHOUSE_CONFIG --key=logger.log || true)"
LOG_DIR="$(dirname $LOG_PATH || true)"
ERROR_LOG_PATH="$(clickhouse extract-from-config --config-file $CLICKHOUSE_CONFIG --key=logger.errorlog || true)"
ERROR_LOG_DIR="$(dirname $ERROR_LOG_PATH || true)"
```

Logger config:
```
<logger>
        <!-- Possible levels: https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Logger.h#L105 -->
        <level>trace</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
        <!-- <console>1</console> --> <!-- Default behavior is autodetection (log to console if not daemon mode and is tty) -->
</logger>
```
